// <auto-generated> by scripts/gen-cobol-words.ps1 — DO NOT EDIT; re-run the script.
// Source: tests/version-matrix/cobol-words.json — cobolWord from the nameSlot=true rows, reservedGatedWord
// from the reservationGated=true rows. CobolWordsDriftTests asserts agreement with BOTH.
// The context-sensitive user-word list: tokens that are keywords in context but legal user-defined
// words in a name slot. Imported by CobolParserCore.g4; the retired hand-written rules lived there.
parser grammar CobolWords;

options { tokenVocab = CobolLexer; }

cobolWord
    : IDENTIFIER
    | {!keywordContinuesHere()}? APPLY
    | {!keywordContinuesHere()}? ARITHMETIC
    | {!keywordContinuesHere()}? AUTO
    | {!keywordContinuesHere()}? AUTOMATIC
    | {!keywordContinuesHere()}? AWAY_FROM_ZERO
    | {!keywordContinuesHere()}? BACKGROUND_COLOR
    | {!keywordContinuesHere()}? BACKWARD
    | {!keywordContinuesHere()}? BELL
    | {!keywordContinuesHere()}? BINARY_ENCODING
    | {!keywordContinuesHere()}? BIT
    | {!keywordContinuesHere()}? BLINK
    | {!keywordContinuesHere()}? BYTES
    | {!keywordContinuesHere()}? CAPACITY
    | {!keywordContinuesHere()}? CYCLE
    | {!keywordContinuesHere()}? DECIMAL_ENCODING
    | {!keywordContinuesHere()}? ENTRY_CONVENTION
    | {!keywordContinuesHere()}? EOL
    | {!keywordContinuesHere()}? EOS
    | {!keywordContinuesHere()}? ERASE
    | {!keywordContinuesHere()}? FLOAT_BINARY
    | {!keywordContinuesHere()}? FLOAT_DECIMAL
    | {!keywordContinuesHere()}? FOREGROUND_COLOR
    | {!keywordContinuesHere()}? FOREVER
    | {!keywordContinuesHere()}? FULL_
    | {!keywordContinuesHere()}? HIGHLIGHT
    | {!keywordContinuesHere()}? HIGH_ORDER_LEFT
    | {!keywordContinuesHere()}? HIGH_ORDER_RIGHT
    | {!keywordContinuesHere()}? IGNORING
    | {!keywordContinuesHere()}? IMPLEMENTS
    | {!keywordContinuesHere()}? INITIALIZED
    | {!keywordContinuesHere()}? INTERMEDIATE
    | {!keywordContinuesHere()}? INTRINSIC
    | {!keywordContinuesHere()}? LENGTH
    | {!keywordContinuesHere()}? LOWLIGHT
    | {!keywordContinuesHere()}? MANUAL
    | {!keywordContinuesHere()}? NATIONAL
    | {!keywordContinuesHere()}? NEAREST_AWAY_FROM_ZERO
    | {!keywordContinuesHere()}? NEAREST_EVEN
    | {!keywordContinuesHere()}? NEAREST_TOWARD_ZERO
    | {!keywordContinuesHere()}? NORMAL
    | {!keywordContinuesHere()}? NUMBERS
    | {!keywordContinuesHere()}? ONLY
    | {!keywordContinuesHere()}? PARAGRAPH
    | {!keywordContinuesHere()}? PARSE
    | {!keywordContinuesHere()}? PREVIOUS
    | {!keywordContinuesHere()}? PROCESSING
    | {!keywordContinuesHere()}? PROHIBITED
    | {!keywordContinuesHere()}? RECURSIVE
    | {!keywordContinuesHere()}? REQUIRED
    | {!keywordContinuesHere()}? REVERSE_VIDEO
    | {!keywordContinuesHere()}? ROUNDING
    | {!keywordContinuesHere()}? SECONDS
    | {!keywordContinuesHere()}? SECURE
    | {!keywordContinuesHere()}? SIGNED
    | {!keywordContinuesHere()}? STANDARD_BINARY
    | {!keywordContinuesHere()}? STANDARD_DECIMAL
    | {!keywordContinuesHere()}? STATEMENT
    | {!keywordContinuesHere()}? STRONG
    | {!keywordContinuesHere()}? TOWARD_GREATER
    | {!keywordContinuesHere()}? TOWARD_LESSER
    | {!keywordContinuesHere()}? TRUNCATION
    | {!keywordContinuesHere()}? UNDERLINE_
    | {!keywordContinuesHere()}? UNSIGNED
    | {!keywordContinuesHere()}? YYYYDDD
    | {!keywordContinuesHere()}? YYYYMMDD
    ;

// The DECLARATION home of every reservation-gated word (kb/Work PB300/PB137/PB693/PB655). A gated word
// is never a cobolWord; the TOKEN-LEVEL gate (ReservationGateRewriter) retypes it to IDENTIFIER where
// §8.9 leaves it free AND a definition slot below matched it. Where §8.9 reserves it, the match stands
// and VersionConformancePass.VisitReservedGatedWord — the ONE funnel arm — answers COBOLNET0901: every
// use of this rule is a definition slot, so a new slot needs no new C#.
reservedGatedWord
    : ( ACTIVE_CLASS
      | ADDRESS
      | ALIGNED
      | ALLOCATE
      | ALTER
      | AS
      | AUTHOR
      | BASED
      | BINARY_CHAR
      | BINARY_DOUBLE
      | BINARY_LONG
      | BINARY_SHORT
      | BOOLEAN
      | B_AND
      | B_NOT
      | B_OR
      | B_SHIFT_L
      | B_SHIFT_LC
      | B_SHIFT_R
      | B_SHIFT_RC
      | B_XOR
      | CLASS_ID
      | CLOCK_UNITS
      | COL
      | COLS
      | COLUMN
      | COLUMNS
      | COMMIT
      | CONDITION
      | CONSTANT
      | CRT
      | CURSOR
      | DATA_POINTER
      | DATE_COMPILED
      | DATE_WRITTEN
      | DEBUGGING
      | DEFAULT
      | DESTINATION
      | EC
      | EDITING
      | END_ACCEPT
      | END_DISPLAY
      | END_RECEIVE
      | END_SEND
      | ENTER
      | EO
      | EVERY
      | EXCLUSIVE_OR
      | FACTORY
      | FARTHEST_FROM_ZERO
      | FINALLY
      | FLOAT_BINARY_128
      | FLOAT_BINARY_32
      | FLOAT_BINARY_64
      | FLOAT_DECIMAL_16
      | FLOAT_DECIMAL_34
      | FLOAT_EXTENDED
      | FLOAT_INFINITY
      | FLOAT_LONG
      | FLOAT_NOT_A_NUMBER
      | FLOAT_NOT_A_NUMBER_QUIET
      | FLOAT_NOT_A_NUMBER_SIGNALING
      | FLOAT_SHORT
      | FORMAT
      | FREE
      | FUNCTION_ID
      | FUNCTION_POINTER
      | GET
      | GOBACK
      | GROUP_USAGE
      | INHERITS
      | INSTALLATION
      | INTERFACE
      | INTERFACE_ID
      | INVOKE
      | IN_ARITHMETIC_RANGE
      | LABEL
      | LOCAL_STORAGE
      | LOCATION
      | MESSAGE
      | MESSAGE_TAG
      | METHOD
      | METHOD_ID
      | MULTIPLE
      | NATIONAL_EDITED
      | NEAREST_TO_ZERO
      | NULL_
      | OBJECT
      | OBJECT_REFERENCE
      | OPTIONS
      | ORDER
      | OVERRIDE
      | PADDING
      | POSITION
      | PRESENT
      | PROCEDURES
      | PROCEED
      | PROGRAM_POINTER
      | PROPERTY
      | PROTOTYPE
      | RAISE
      | RAISING
      | RECEIVE
      | REFERENCES
      | REPOSITORY
      | RERUN
      | RESUME
      | RETRY
      | RETURNING
      | REVERSED
      | ROLLBACK
      | SCREEN
      | SECURITY
      | SELF
      | SEND
      | SHARING
      | SOURCES
      | SUPER
      | TAPE
      | TYPEDEF
      | UNLOCK
      | VALID
      | VALIDATE
      | VALIDATE_STATUS
      | VAL_STATUS
      | XOR
      ) { gatedDeclaration(TokenStream.LT(-1)); }
    ;
