// <auto-generated> by scripts/gen-cobol-words.ps1 — DO NOT EDIT; re-run the script.
// Source: tests/version-matrix/cobol-words.json — cobolWord from the nameSlot=true rows, reservedGatedWord
// from the reservationGated=true rows. CobolWordsDriftTests asserts agreement with BOTH.
// The context-sensitive user-word list: tokens that are keywords in context but legal user-defined
// words in a name slot. Imported by CobolParserCore.g4; the retired hand-written rules lived there.
parser grammar CobolWords;

options { tokenVocab = CobolLexer; }

cobolWord
    : IDENTIFIER
    | APPLY
    | ARITHMETIC
    | {userWordHere("AS")}? AS
    | AUTO
    | AUTOMATIC
    | BACKGROUND_COLOR
    | BELL
    | BINARY_ENCODING
    | BIT
    | BLINK
    | {userWordHere("B_AND")}? B_AND
    | {userWordHere("B_NOT")}? B_NOT
    | {userWordHere("B_OR")}? B_OR
    | {userWordHere("B_XOR")}? B_XOR
    | {userWordHere("CLOCK_UNITS")}? CLOCK_UNITS
    | {userWordHere("COL")}? COL
    | {userWordHere("COLS")}? COLS
    | {userWordHere("COLUMN")}? COLUMN
    | {userWordHere("COLUMNS")}? COLUMNS
    | {userWordHere("COMMIT")}? COMMIT
    | {userWordHere("CONDITION")}? CONDITION
    | {userWordHere("CONSTANT")}? CONSTANT
    | {userWordHere("CRT")}? CRT
    | {userWordHere("CURSOR")}? CURSOR
    | {userWordHere("DEBUGGING")}? DEBUGGING
    | DECIMAL_ENCODING
    | {userWordHere("DEFAULT")}? DEFAULT
    | {userWordHere("DESTINATION")}? DESTINATION
    | {userWordHere("EC")}? EC
    | {userWordHere("EDITING")}? EDITING
    | {userWordHere("END_RECEIVE")}? END_RECEIVE
    | {userWordHere("END_SEND")}? END_SEND
    | {userWordHere("ENTER")}? ENTER
    | ENTRY_CONVENTION
    | {userWordHere("EO")}? EO
    | EOL
    | EOS
    | ERASE
    | {userWordHere("EVERY")}? EVERY
    | {userWordHere("EXCLUSIVE_OR")}? EXCLUSIVE_OR
    | {userWordHere("FACTORY")}? FACTORY
    | FLOAT_BINARY
    | FLOAT_DECIMAL
    | FOREGROUND_COLOR
    | FOREVER
    | {userWordHere("FORMAT")}? FORMAT
    | FULL_
    | {userWordHere("FUNCTION_POINTER")}? FUNCTION_POINTER
    | {userWordHere("GET")}? GET
    | {userWordHere("GROUP_USAGE")}? GROUP_USAGE
    | HIGHLIGHT
    | HIGH_ORDER_LEFT
    | HIGH_ORDER_RIGHT
    | IGNORING
    | IMPLEMENTS
    | {userWordHere("INTERFACE")}? INTERFACE
    | INTERMEDIATE
    | LENGTH
    | {userWordHere("LOCATION")}? LOCATION
    | LOWLIGHT
    | MANUAL
    | {userWordHere("MESSAGE")}? MESSAGE
    | NATIONAL
    | NORMAL
    | NUMBERS
    | ONLY
    | {userWordHere("ORDER")}? ORDER
    | {userWordHere("OVERRIDE")}? OVERRIDE
    | {userWordHere("PADDING")}? PADDING
    | PARSE
    | {userWordHere("PRESENT")}? PRESENT
    | {userWordHere("PROCEDURES")}? PROCEDURES
    | PROCESSING
    | {userWordHere("PROGRAM_POINTER")}? PROGRAM_POINTER
    | {userWordHere("PROPERTY")}? PROPERTY
    | {userWordHere("PROTOTYPE")}? PROTOTYPE
    | {userWordHere("RAISE")}? RAISE
    | {userWordHere("RAISING")}? RAISING
    | {userWordHere("RECEIVE")}? RECEIVE
    | {userWordHere("REFERENCES")}? REFERENCES
    | REQUIRED
    | {userWordHere("RERUN")}? RERUN
    | {userWordHere("RESUME")}? RESUME
    | {userWordHere("RETRY")}? RETRY
    | REVERSE_VIDEO
    | {userWordHere("ROLLBACK")}? ROLLBACK
    | ROUNDING
    | {userWordHere("SCREEN")}? SCREEN
    | SECONDS
    | SECURE
    | {userWordHere("SEND")}? SEND
    | {userWordHere("SHARING")}? SHARING
    | STANDARD_BINARY
    | STANDARD_DECIMAL
    | STATEMENT
    | UNDERLINE_
    | {userWordHere("UNLOCK")}? UNLOCK
    | {userWordHere("VALID")}? VALID
    | {userWordHere("VALIDATE")}? VALIDATE
    | {userWordHere("VALIDATE_STATUS")}? VALIDATE_STATUS
    | {userWordHere("VAL_STATUS")}? VAL_STATUS
    | {userWordHere("XOR")}? XOR
    ;

// The DECLARATION-position twin of the gated cobolWord alternatives (kb/Work PB300/PB137/PB693): the
// SAME derived rows under the INVERSE predicate, so `01 <word> PIC X.` and `PROGRAM-ID. <word>.`
// still PARSE where §8.9 reserves the word and the funnel answers with a targeted COBOLNET0901
// instead of a parse error. VersionConformancePass.VisitReservedGatedWord is the ONE funnel arm:
// every use of this rule is a definition slot, so a new slot needs no new C# (kb/Work PB693).
reservedGatedWord
    : {!userWordHere("AS")}? AS
    | {!userWordHere("B_AND")}? B_AND
    | {!userWordHere("B_NOT")}? B_NOT
    | {!userWordHere("B_OR")}? B_OR
    | {!userWordHere("B_XOR")}? B_XOR
    | {!userWordHere("CLOCK_UNITS")}? CLOCK_UNITS
    | {!userWordHere("COL")}? COL
    | {!userWordHere("COLS")}? COLS
    | {!userWordHere("COLUMN")}? COLUMN
    | {!userWordHere("COLUMNS")}? COLUMNS
    | {!userWordHere("COMMIT")}? COMMIT
    | {!userWordHere("CONDITION")}? CONDITION
    | {!userWordHere("CONSTANT")}? CONSTANT
    | {!userWordHere("CRT")}? CRT
    | {!userWordHere("CURSOR")}? CURSOR
    | {!userWordHere("DEBUGGING")}? DEBUGGING
    | {!userWordHere("DEFAULT")}? DEFAULT
    | {!userWordHere("DESTINATION")}? DESTINATION
    | {!userWordHere("EC")}? EC
    | {!userWordHere("EDITING")}? EDITING
    | {!userWordHere("END_RECEIVE")}? END_RECEIVE
    | {!userWordHere("END_SEND")}? END_SEND
    | {!userWordHere("ENTER")}? ENTER
    | {!userWordHere("EO")}? EO
    | {!userWordHere("EVERY")}? EVERY
    | {!userWordHere("EXCLUSIVE_OR")}? EXCLUSIVE_OR
    | {!userWordHere("FACTORY")}? FACTORY
    | {!userWordHere("FORMAT")}? FORMAT
    | {!userWordHere("FUNCTION_POINTER")}? FUNCTION_POINTER
    | {!userWordHere("GET")}? GET
    | {!userWordHere("GROUP_USAGE")}? GROUP_USAGE
    | {!userWordHere("INTERFACE")}? INTERFACE
    | {!userWordHere("LOCATION")}? LOCATION
    | {!userWordHere("MESSAGE")}? MESSAGE
    | {!userWordHere("ORDER")}? ORDER
    | {!userWordHere("OVERRIDE")}? OVERRIDE
    | {!userWordHere("PADDING")}? PADDING
    | {!userWordHere("PRESENT")}? PRESENT
    | {!userWordHere("PROCEDURES")}? PROCEDURES
    | {!userWordHere("PROGRAM_POINTER")}? PROGRAM_POINTER
    | {!userWordHere("PROPERTY")}? PROPERTY
    | {!userWordHere("PROTOTYPE")}? PROTOTYPE
    | {!userWordHere("RAISE")}? RAISE
    | {!userWordHere("RAISING")}? RAISING
    | {!userWordHere("RECEIVE")}? RECEIVE
    | {!userWordHere("REFERENCES")}? REFERENCES
    | {!userWordHere("RERUN")}? RERUN
    | {!userWordHere("RESUME")}? RESUME
    | {!userWordHere("RETRY")}? RETRY
    | {!userWordHere("ROLLBACK")}? ROLLBACK
    | {!userWordHere("SCREEN")}? SCREEN
    | {!userWordHere("SEND")}? SEND
    | {!userWordHere("SHARING")}? SHARING
    | {!userWordHere("UNLOCK")}? UNLOCK
    | {!userWordHere("VALID")}? VALID
    | {!userWordHere("VALIDATE")}? VALIDATE
    | {!userWordHere("VALIDATE_STATUS")}? VALIDATE_STATUS
    | {!userWordHere("VAL_STATUS")}? VAL_STATUS
    | {!userWordHere("XOR")}? XOR
    ;
