#!/usr/bin/env python3
"""The drift-rule index: every *DriftTests class's rule, and the repo paths it scans — ONE generated view.

    python scripts/spec/drift_rules.py                 # regenerate docs/DRIFT_RULES.md
    python scripts/spec/drift_rules.py --check         # exit 1 if docs/DRIFT_RULES.md is stale (CI `audits` job)
    python scripts/spec/drift_rules.py <path> [...]    # the drift rules that govern these files — run BEFORE editing

Why (owner, 2026-09-25): 216 drift tests each carry their rule in their own <summary>, but no skill surfaced them, so
agents learned each rule only by tripping it at the gate. The rule stays in ONE place — the test that enforces it — and
this script derives the index and answers "which rules govern the file I am about to edit" from the tests themselves.

A file is governed SPECIFICALLY by a drift test when the test names that file, or a directory at least SPECIFIC_DEPTH
segments deep above it (through TestRepo.X(...) segments or a repo-relative string literal), or when the test's rule
text names the file's basename. A test that scans only a whole tree above it (src/<project>, tests, docs) is listed as a
TREE-WIDE SWEEP — it still applies, but it is not the first thing to read.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "DRIFT_RULES.md"
HELPERS = {"Src": "src", "Tests": "tests", "Docs": "docs", "Scripts": "scripts", "Specs": "specs",
           "VersionMatrix": "tests/version-matrix", "Nist": "tests/nist", "At": ""}
CALL = re.compile(r"TestRepo\.(" + "|".join(HELPERS) + r")\(([^()]*)\)")
LITERAL = re.compile(r'"((?:src|tests|docs|scripts|specs|kb|grammars|\.github|adjudication)/[^"\s{}*]+)"')
SUMMARY = re.compile(r"///\s*<summary>(.*?)</summary>", re.S)
CLASS = re.compile(r"\bclass\s+(\w*DriftTests)\b")
CREF = re.compile(r'<(?:see|seealso)\s+(?:cref|langword|href)="(?:[A-Z]:)?([^"]+)"\s*/>')
PARAMREF = re.compile(r'<(?:paramref|typeparamref)\s+name="([^"]+)"\s*/>')
TAG = re.compile(r"<[^>]+>")
SPECIFIC_DEPTH = 3   # src/<project> (2 segments) is a tree-wide sweep; src/<project>/<dir> and deeper are specific


def drift_files():
    # Sort on the repo-relative POSIX string: Path ordering is case-INsensitive on Windows and case-sensitive on
    # Linux, so sorting Path objects made the generated index differ between a local run and CI.
    for f in sorted((ROOT / "tests").rglob("*DriftTests.cs"), key=lambda p: p.relative_to(ROOT).as_posix()):
        parts = set(f.relative_to(ROOT).parts)
        if "bin" in parts or "obj" in parts:
            continue
        yield f


def rule_of(text):
    """The class summary as one line: references kept by name, other XML stripped, whitespace collapsed, cut at the
    first sentence end past 60 characters (and at 400)."""
    m = SUMMARY.search(text)
    if not m:
        return ""
    s = re.sub(r"\s*///\s?", " ", m.group(1))
    s = CREF.sub(lambda c: c.group(1).split("(")[0].split(".")[-1], s)
    s = PARAMREF.sub(lambda c: c.group(1), s)
    s = TAG.sub("", s).replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")
    s = re.sub(r"\s+", " ", s).strip()
    cut = re.search(r"(?<=[.!?])\s", s[60:])
    s = s[: 60 + cut.start()] if cut else s
    return s[:400] + ("…" if len(s) > 400 else "")


def paths_of(text):
    seen = []
    for helper, args in CALL.findall(text):
        segs = re.findall(r'"([^"]+)"', args)
        p = "/".join(([HELPERS[helper]] if HELPERS[helper] else []) + segs).strip("/")
        if p and p not in seen:
            seen.append(p)
    for lit in LITERAL.findall(text):
        lit = lit.rstrip("/.,;:")
        if lit not in seen:
            seen.append(lit)
    return seen


def index():
    rows = []
    for f in drift_files():
        text = f.read_text(encoding="utf-8", errors="replace")
        m = CLASS.search(text)
        rows.append({"test": m.group(1) if m else f.stem, "file": f.relative_to(ROOT).as_posix(),
                     "rule": rule_of(text), "paths": paths_of(text)})
    return rows


def render(rows):
    out = ["# Drift rules — generated index",
           "",
           "<!-- GENERATED by scripts/spec/drift_rules.py — do not edit by hand; the CI `audits` job fails when stale. -->",
           "",
           "Every `*DriftTests` class enforces ONE structural rule, and that rule's single home is the test's `<summary>`.",
           "This page is derived from them. **Before editing a file, ask which rules govern it:**",
           "`python scripts/spec/drift_rules.py <path>` (specific rules first, then the tree-wide sweeps).",
           "",
           f"{len(rows)} drift tests.",
           "",
           "| Drift test | Rule | Scans |",
           "|---|---|---|"]
    for r in rows:
        rule = r["rule"].replace("|", "\\|") or "⚠ no `<summary>` — the rule is undocumented"
        scans = ", ".join(f"`{p}`" for p in r["paths"][:6]) + (" …" if len(r["paths"]) > 6 else "")
        out.append(f"| [{r['test']}](../{r['file']}) | {rule} | {scans or '—'} |")
    return "\n".join(out) + "\n"


def governing(rows, target):
    rel = pathlib.Path(target).resolve()
    try:
        rel = rel.relative_to(ROOT).as_posix()
    except ValueError:
        rel = pathlib.PurePosixPath(target).as_posix()
    base = pathlib.PurePosixPath(rel).name
    stem = pathlib.PurePosixPath(rel).stem
    specific, sweeps = [], []
    for r in rows:
        under = [p for p in r["paths"] if rel == p or rel.startswith(p.rstrip("/") + "/")]
        deep = any(p == rel or len(p.split("/")) >= SPECIFIC_DEPTH for p in under)
        by_name = len(stem) > 3 and re.search(r"\b" + re.escape(stem) + r"\b", r["rule"]) is not None
        if deep or by_name or base == pathlib.PurePosixPath(r["file"]).name:
            specific.append(r)
        elif under:
            sweeps.append(r)
    return rel, specific, sweeps


def main(argv):
    rows = index()
    text = render(rows)
    if argv[:1] == ["--check"]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"docs/DRIFT_RULES.md is STALE — run: python scripts/spec/drift_rules.py  ({len(rows)} drift tests)")
            return 1
        undocumented = [r["test"] for r in rows if not r["rule"]]
        if undocumented:   # a drift test's rule has ONE home, its <summary>; a test without one enforces an unwritten rule
            print(f"{len(undocumented)} drift test(s) state no rule — add a class <summary>: {', '.join(undocumented)}")
            return 1
        print(f"docs/DRIFT_RULES.md current — {len(rows)} drift tests, every one with its rule")
        return 0
    if argv:
        for target in argv:
            rel, specific, sweeps = governing(rows, target)
            print(f"== {rel}: {len(specific)} specific drift rule(s)")
            for r in specific:
                print(f"  {r['test']}  ({r['file']})\n    {r['rule'] or '(no summary — read the test)'}")
            if sweeps:
                print(f"  + {len(sweeps)} tree-wide sweep(s) also scan it: " + ", ".join(r["test"] for r in sweeps))
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()} — {len(rows)} drift tests")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
