#!/usr/bin/env python3
"""Prepare a Phase-B adjudication batch: one input file per SUBJECT, holding the full text of its rules.

    python scripts/spec/phase_b_batch.py 15.32-15.44           # a clause range
    python scripts/spec/phase_b_batch.py 14.9.1 14.9.2         # explicit clauses
    python scripts/spec/phase_b_batch.py 15.32-15.44 --out DIR # somewhere other than the default scratchpad

⛔ ONE AGENT, ONE INPUT FILE — never "read the shared catalog and take element k". Agents miscount the index, and
one fan-out cost four double-processed clusters and five skipped entirely (`feedback_agent_dispatch`). This writes
a self-contained file per subject and prints the slug list to paste into the workflow script.

⚠ ALREADY-ADJUDICATED RULES ARE EXCLUDED automatically — a rule with a verdict in the inventory is not re-issued,
so re-running after a partial batch is safe and resumable.

WHY THIS IS A SCRIPT AND NOT PASTED PYTHON. The first three batches were generated by inline snippets, which meant
the filter logic was retyped each time and the exclusion rule lived only in a transcript. The batches are the
project's road to v1.0 and there will be dozens; the generator belongs in the repo with them.

THE PROMPT THAT DRIVES THE AGENTS lives with the workflow, not here — see
`docs/rearchitecture/DESIGN-spec-conformance-review.md` §8, which records what a batch prompt MUST carry (the
spec-derived test-ref rule, the "editions never from the catalog row" warning, the CONFORMS-costs-something rule,
and the adversarial refute stage).
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
CATALOG = REPO / "docs" / "rearchitecture" / "spec-rule-catalog.json"
INVENTORY = REPO / "tests" / "version-matrix" / "traceability-inventory.json"
DEFAULT_OUT = REPO / "scratchpad" / "phase-b"


def clause_key(c: str) -> tuple:
    return tuple(int(p) if p.isdigit() else 0 for p in c.split("."))


def in_range(section: str, lo: str, hi: str) -> bool:
    k = clause_key(section)
    return clause_key(lo) <= k[: len(clause_key(lo))] and k[: len(clause_key(hi))] <= clause_key(hi)


def selected(section: str, specs: list[str]) -> bool:
    for spec in specs:
        if "-" in spec:
            lo, hi = spec.split("-", 1)
            if in_range(section, lo, hi):
                return True
        elif section == spec or section.startswith(spec + "."):
            return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("clauses", nargs="+", help="clauses or ranges, e.g. 15.32-15.44 or 14.9.1")
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    rules = json.loads(CATALOG.read_text(encoding="utf-8"))["rules"]
    done = {r["rule-id"] for r in json.loads(INVENTORY.read_text(encoding="utf-8")) if r.get("verdict")}

    chosen = [r for r in rules if selected(r["section"], args.clauses) and r["id"] not in done]
    skipped = sum(1 for r in rules if selected(r["section"], args.clauses) and r["id"] in done)
    if not chosen:
        print(f"nothing to do — {skipped} rule(s) in that range already carry a verdict")
        return 0

    by_subject: dict[str, list[dict]] = collections.defaultdict(list)
    for r in chosen:
        by_subject[r["subject"]].append(r)

    args.out.mkdir(parents=True, exist_ok=True)
    slugs = []
    for subject, rows in sorted(by_subject.items()):
        slug = subject.replace(" function", "").lower().replace(" ", "-").replace("/", "-")
        (args.out / f"in-{slug}.json").write_text(json.dumps({
            "subject": subject,
            "clauses": sorted({r["section"] for r in rows}, key=clause_key),
            "rules": [{"rule-id": r["id"], "kind": r["kind"], "section": r["section"], "text": r["text"]}
                      for r in sorted(rows, key=lambda x: (x["kind"], x["id"]))],
        }, indent=1, ensure_ascii=False), encoding="utf-8")
        slugs.append(slug)

    print(f"{len(chosen)} rule(s) over {len(slugs)} subject(s); {skipped} already adjudicated and skipped")
    print(f"input files -> {args.out}")
    print("\nslug list for the workflow script:\n")
    print(json.dumps(slugs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
