#!/usr/bin/env python3
"""Prepare a Phase-B adjudication batch: one input file per SUBJECT, holding the full text of its rules.

    python scripts/spec/phase_b_batch.py 15.32-15.44             # a clause range
    python scripts/spec/phase_b_batch.py 14.9.1 14.9.2           # explicit clauses
    python scripts/spec/phase_b_batch.py 14 --max-rules 20        # a whole clause, agent-sized
    python scripts/spec/phase_b_batch.py 15.32-15.44 --out DIR    # somewhere other than the default scratchpad

⚠ ONE SUBJECT IS NOT ALWAYS ONE AGENT. The `subject` key is the statement name in §14 and the clause name in
§13, so it generalises past §15's functions — but the SIZE does not. The four §15 batches that have actually run
topped out at 18 rules per agent; SET carries 98, PICTURE 72, SPECIAL-NAMES 81. `--max-rules` (default 20) splits
an oversized subject at CLAUSE boundaries (`.2` format / `.3` syntax rules / `.4` general rules are different
questions, so the seam is free), leaves a fitting subject WHOLE, and gives each part its siblings and the whole
subject's clause map so no agent adjudicates a slice believing it is the set.

⛔ ONE AGENT, ONE INPUT FILE — never "read the shared catalog and take element k". Agents miscount the index, and
one fan-out cost four double-processed clusters and five skipped entirely (`feedback_agent_dispatch`). This writes
a self-contained file per subject and prints the slug list to paste into the workflow script.

⚠ ALREADY-ADJUDICATED RULES ARE EXCLUDED automatically — a rule with a verdict in the inventory is not re-issued,
so re-running after a partial batch is safe and resumable.

⭐ EVERY FILE ALSO CARRIES A DOSSIER — the discovery the agent would otherwise repeat. Batch 8 (2026-09-01) spent
574M cache-read tokens over 39 agents for 224 rows, and the bulk of each agent's ~120 turns was the SAME three
greps: where is the grammar rule, where is the binder/emitter, where are the tests. That search has one answer per
subject and it was being bought 39 times. The dossier computes it once, from the catalog's own `subject` field and
the subject's clause numbers, and pastes it into every part file: grammar rules, citing source files, citing tests,
the `docs/CONFORMANCE.md` determinations, the `kb/Work/` notes that already own these rows, and the citing
`docs/DIAGNOSTICS.md` entries. **The agent's job becomes VERIFY, not SEARCH.** `--no-dossier` turns it off.

⛔ THE DOSSIER IS A MAP, NOT THE TERRITORY, AND ITS SILENCE IS NOT EVIDENCE. It is a keyword-and-citation
selector, so it is evidence about what it RETURNED and says nothing about what it dropped
(`feedback_measure_the_selectors_complement`: `work.py next`'s own filter hid nine harmful items for months while
looking perfectly healthy). An empty `grammar` list means "this derivation found none", never "the compiler has
none" — a §8 concept subject has no keyword to search with at all. Every file therefore repeats that sentence to
the agent in `how-to-read`, so a NOT-IMPLEMENTED verdict is never returned on the dossier's silence alone.

WHY THIS IS A SCRIPT AND NOT PASTED PYTHON. The first three batches were generated by inline snippets, which meant
the filter logic was retyped each time and the exclusion rule lived only in a transcript. The batches are the
project's road to v1.0 and there will be dozens; the generator belongs in the repo with them.

THE PROMPT THAT DRIVES THE AGENTS lives with the workflow, not here — see
`docs/rearchitecture/DESIGN-spec-conformance-review.md` §8, which records what a batch prompt MUST carry (the
spec-derived test-ref rule, the "editions never from the catalog row" warning, the CONFORMS-costs-something rule,
and the adversarial refute stage), and §9 for the dossier's contract.
"""
from __future__ import annotations

import argparse
import collections
import functools
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
CATALOG = REPO / "docs" / "rearchitecture" / "spec-rule-catalog.json"
INVENTORY = REPO / "tests" / "version-matrix" / "traceability-inventory.json"
CONFORMANCE_DOC = REPO / "docs" / "CONFORMANCE.md"
DIAGNOSTICS_DOC = REPO / "docs" / "DIAGNOSTICS.md"
DEFAULT_OUT = REPO / "scratchpad" / "phase-b"

# The register's frontmatter parser already exists, one file over, in `work.py`. Import it rather than writing a
# second one: the same format parsed in two places is CLAUDE.md rule 8's failure one level down — `spec_refs`
# would grow a field here and not there, and the dossier would quietly stop seeing the notes that own its rows.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import work  # noqa: E402  (path must be set first)


def clause_key(c: str) -> tuple:
    return tuple(int(p) if p.isdigit() else 0 for p in c.split("."))


def in_range(section: str, lo: str, hi: str) -> bool:
    k = clause_key(section)
    return clause_key(lo) <= k[: len(clause_key(lo))] and k[: len(clause_key(hi))] <= clause_key(hi)


def selected(section: str, specs: list[str]) -> bool:
    for spec in specs:
        if "-" in spec:
            lo, hi = spec.split("-", 1)
            if in_range(section, lo, hi):
                return True
        elif section == spec or section.startswith(spec + "."):
            return True
    return False


#: The most rules one agent is given. §15's batches — the four that have actually run, adversarially refuted —
#: topped out at 18 rules per agent, so 20 is "the proven shape, rounded up", not a guess. §14 and §13 are a
#: different scale entirely: SET carries 98 rules, PICTURE 72, SPECIAL-NAMES 81.
DEFAULT_MAX_RULES = 20


def partition(rows: list[dict], cap: int) -> list[list[dict]]:
    """Split one subject's rules into agent-sized files — BY CLAUSE first, then by size.

    ⭐ THE CLAUSE BOUNDARY IS THE RIGHT SEAM, and it is free. Every construct in the standard is laid out the
    same way: `.2` the general format, `.3` the syntax rules, `.4` the general rules. Those are genuinely
    different questions — SR asks "does the grammar admit exactly this?", GR asks "does the implementation DO
    this?" — and splitting there also separates plan §5b's FMT+SR vein from its GR vein without anyone
    arranging it. An arbitrary chunk at rule 20 would cut a rule list mid-argument instead.

    ⚠ A SUBJECT THAT FITS IS NOT SPLIT AT ALL. §15's proven shape is one agent per function seeing ALL of its
    rules together, because a function's argument rules and returned-value rules interlock; splitting those
    would trade a measured-good shape for tidiness. Only an oversized subject is cut.
    """
    if len(rows) <= cap:
        return [rows]
    groups = [sorted((r for r in rows if r["section"] == s), key=lambda x: (x["kind"], x["id"]))
              for s in sorted({r["section"] for r in rows}, key=clause_key)]
    parts: list[list[dict]] = []
    pending: list[dict] = []
    for group in groups:
        if len(group) > cap:
            # Too big for one agent even as a single clause (SET's 53 syntax rules). Cut it into EVEN chunks —
            # not one full file plus a stub — so no agent gets a lopsided share of the same question.
            n = -(-len(group) // cap)
            size = -(-len(group) // n)
            chunks = [group[i:i + size] for i in range(0, len(group), size)]
            # ⚠ Absorb anything pending into the first chunk if it fits. Without this a construct's ONE general
            # format rule becomes its own agent — a whole fan-out slot spent on a single FMT row, which is what
            # the first version of this function actually did to SET.
            if pending and len(pending) + len(chunks[0]) <= cap:
                chunks[0] = pending + chunks[0]
                pending = []
            if pending:
                parts.append(pending)
                pending = []
            parts.extend(chunks)
            continue
        if len(pending) + len(group) <= cap:
            pending += group
        else:
            parts.append(pending)
            pending = list(group)
    if pending:
        parts.append(pending)
    return parts


#: Anything that is not a slug character. ⛔ THE SLUG BECOMES A FILE NAME, so it may hold NOTHING else.
SLUG_UNSAFE = re.compile(r"[^a-z0-9]+")
#: Long enough to stay readable, short enough that `<out>/in-<slug>.json` clears Windows' 260-character path.
MAX_SLUG = 80
#: What a slug is allowed to be. Checked on every file, so a future change to `base_slug` cannot quietly widen it.
SLUG_OK = re.compile(r"[a-z0-9][a-z0-9-]*")


def base_slug(subject: str) -> str:
    """The subject's file-name stem — every non-slug character replaced, not just the space and the slash.

    ⛔ THIS IS A SILENT-DATA-LOSS FIX, and the failure is worth stating because nothing announced it. The old
    form replaced ` ` and `/` and passed the rest of the subject through, so the Annex A.1 subject `Alignment of
    data for increased efficiency (special or automatic alignment: interpretation, …)` produced a file name
    containing a COLON. On Windows that is not an error — it names an NTFS ALTERNATE DATA STREAM. The run
    exited 0, a zero-byte `in-alignment-…-alignment` file appeared, the 3,674 bytes of the agent's input went
    into a stream no `in-*.json` glob can see, and the batch was one agent short with nothing anywhere saying
    so. Exactly the shape the partition invariant below guards against, one level up: a missing item read as
    no item.
    """
    s = SLUG_UNSAFE.sub("-", subject.replace(" function", "").lower()).strip("-")
    return s[:MAX_SLUG].strip("-") or "subject"


def part_slug(base: str, index: int, total: int) -> str:
    """`set-statement` when whole; `set-statement-p1…p6` when split.

    ⚠ The slug is an INDEX, not a clause name, because a part may span clauses once the packer absorbs a small
    group into a larger neighbour — a clause-named slug would then be a lie. The clause coverage of every part
    is printed as a table when the batch is generated, and is inside each file as `clauses`.
    """
    if total == 1:
        return base
    return f"{base}-p{index + 1}"


# ══ THE DOSSIER ═══════════════════════════════════════════════════════════════════════════════════════════════
# The pre-computed discovery handed to every agent. See the module docstring for WHY; what follows is HOW.

#: Everything the dossier scans, as (root, glob). Read once per run and reused across every subject in the batch.
#: ⚠ `tests/nist` is deliberately absent from the `.cob` roots: 459 machine-generated CCVS cards, 30 MB — twice
#: the rest of the corpus put together — and an X-card cites a NIST test number, never an ISO clause. Including
#: it would triple the scan to add nothing. The NIST `.cs` drivers under `tests/` are still scanned.
CORPUS = {
    "grammar": [("src/Cobol.Net.Frontend/Grammar", "**/*.g4")],
    "source": [("src", "Cobol.Net.*/**/*.cs")],
    "tests": [("tests", "**/*.cs"),
              ("tests/conformance", "**/*.cob"),
              ("tests/characterization", "**/*.cob")],
}
SKIP_DIRS = ("/obj/", "/bin/", "/Generated/")

#: Caps. The dossier is a MAP: an input file that grows past agent-sized has traded one search problem for
#: another. Every category reports `truncated` so a cut is visible rather than silent.
MAX_LINES = 40          # citing lines kept per category
MAX_PER_FILE = 6        # citing lines kept per file, before the round-robin trim
MAX_FILES = 40          # keyword-named files kept per category
MAX_RULES = 8           # grammar rules quoted
MAX_RULE_LINES = 40     # lines of one rule's text
MAX_LEAD_COMMENT = 12   # lines of the comment block above a rule (it usually carries the existing ISO citation)
SNIP = 300              # characters of one citing line (docs/CONFORMANCE.md rows run to 4,000)

#: ALL-CAPS words that are in a subject name but are not a construct to search for. ⚠ This is NOT the
#: construct→file map CLAUDE.md rule 8 forbids — nothing here names a file, a rule or a subsystem, and adding a
#: construct never touches it. `COBOL` is the one that has to be here: as a keyword it matches every assembly
#: (`src/Cobol.Net.*`), every grammar file (`CobolLexer.g4`) and every test, i.e. everything and therefore nothing.
#: ⛔ IT DELIBERATELY DOES NOT HOLD `TO`, `OF`, `WHEN`, `ALL`… Those look like stopwords and are COBOL RESERVED
#: WORDS carrying a construct's identity: dropping them turns `GO TO statement` into `GO` and `BLANK WHEN ZERO
#: clause` into `BLANK`+`ZERO`, and the grammar's `goToStatement` / `blankWhenZeroClause` then stop matching
#: EXACTLY — which is the rank that decides what survives the 8-rule cap. The noise they would add elsewhere is
#: held off structurally instead, by `named`'s token rule, not by a longer stopword list.
KEYWORD_NOISE = {"COBOL", "ISO", "IEC", "THE", "AND", "OR", "A", "AN"}
#: The trailing role word in a catalog `subject` — "OPEN statement", "VALUE clause", "TRIM function". ⚠ ONE
#: regex serves both readers: `.sub` strips the role and everything after it to leave the construct name, and
#: group 1 IS the role. Written twice it would be one rule in two places, and the two spellings would drift.
SUBJECT_ROLE = re.compile(r"\s+(statement|clause|function|paragraph|directive|phrase|entry|register)s?\b.*$",
                          re.IGNORECASE)
#: A construct word in a subject name: an ALL-CAPS COBOL word (`OPEN`, `BACKGROUND-COLOR`), or a hyphenated
#: lowercase COBOL term, which the standard capitalises as prose — `Entry-name`, `Level-number`,
#: `Condition-name`, `Data-address-identifier`. The second arm is not decoration: without it `Entry-name clause`
#: derives NO keyword at all and its dossier arrives with the grammar and file-name halves empty.
#: ⛔ THE HYPHENATED-PROSE ARM COMES FIRST. ANTLR-style alternation takes the first arm that matches at a
#: position, and on `Entry-name` the ALL-CAPS arm matches the single letter `E` — the scan then resumed at `n`
#: and produced the keyword `NTRY-NAME`, which matches nothing and looks like a derivation rather than a bug.
CAPS_WORD = re.compile(r"[A-Za-z][a-z]+(?:-[a-z]+)+|[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*")
#: Prose fallback: lowercase words long enough to be a real search term. `data`, `item`, `used` are not.
PROSE_WORD = re.compile(r"[A-Za-z][a-z]{5,}")
PROSE_NOISE = {"implementor", "defined", "specified", "standard", "meaning", "between", "certain", "several",
               "whether", "another", "including", "associated"}
#: `openStatement` → open · statement; `SPECIAL_NAMES` → special · names.
CAMEL = re.compile(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+")
#: Separator-stripper for file-name comparison. Compiled once: `named` runs it over the whole corpus per subject.
FLATTEN = re.compile(r"[^a-z0-9]")
#: An ANTLR rule header: a bare identifier on its own line (the project's parser-rule style) or `NAME : …`.
RULE_HEAD = re.compile(r"^([A-Za-z][A-Za-z0-9_]*)\s*(:.*)?$")
#: `GR-14.9.10.4-6` → the clause `14.9.10.4`. Catalog kinds: GR · SR · FMT · RV · AR · DOC.
RULE_ID = re.compile(r"^[A-Z]+-(\d+(?:\.\d+)*)-\d+$")
#: An Annex A.1 implementor-determination row in `docs/CONFORMANCE.md`, whose first cell is the A.1 item number.
A1_ROW = re.compile(r"^\|\s*(\d+)\s*\|")

HOW_TO_READ = (
    "PRE-COMPUTED DISCOVERY — verify it, do not repeat it. Every entry below was found mechanically: a "
    "clause-citation regex over the tree, plus the construct keyword derived from this subject's name. "
    "⛔ ITS SILENCE IS NOT EVIDENCE. This is a selector, so it is evidence about what it RETURNED and says "
    "nothing about what it dropped: an empty list means 'this derivation found none', NEVER 'the compiler has "
    "none' (a §8 concept subject has no keyword to search with at all, and code that implements a rule without "
    "citing its clause is invisible here — that is itself a finding worth reporting). Do not return "
    "NOT-IMPLEMENTED on an empty dossier without searching yourself. `truncated` counts what a cap cut."
)


def clause_key_depth(section: str) -> int:
    return len(section.split("."))


def dossier_sections(sections: list[str]) -> list[str]:
    """The clause numbers a citation of THIS subject can carry — the rows' own, plus their construct root.

    ⛔ THE ROOT IS THE LOAD-BEARING PART. A subject's catalog rows sit in `.2` (format), `.3` (syntax) and `.4`
    (general) — §14.9.27.2/.3/.4 for OPEN — but the code, the goldens and CONFORMANCE.md overwhelmingly cite the
    CONSTRUCT clause, `§14.9.27 SR8`. Scanning only the rows' own sections would miss every one of them and hand
    the agent an empty dossier for a construct with sixteen citing files. So the longest common prefix is added.

    ⚠ …but only when every row is a DIRECT CHILD of it. Otherwise a scattered concept subject
    ('Intrinsic functions' → §15.2, §15.3, §15.4.1) collapses to `§15`, which matches every intrinsic citation in
    the repo and floods the caps with noise. Measured over the whole catalog: 596 of 599 subjects take the root,
    and the three that do not (§5 'Description techniques', §6 'Reference format', §15 'Intrinsic functions') are
    exactly the ones where it would have been wrong.
    """
    secs = sorted({s for s in sections if s}, key=clause_key)
    if not secs:
        return []
    parts = [s.split(".") for s in secs]
    root: list[str] = []
    for i in range(min(len(p) for p in parts)):
        if len({p[i] for p in parts}) != 1:
            break
        root.append(parts[0][i])
    if len(root) >= 2 and all(clause_key_depth(s) <= len(root) + 1 for s in secs):
        secs = sorted(set(secs) | {".".join(root)}, key=clause_key)
    # A descendant is already matched by its ancestor's pattern (see `clause_pattern`), so drop it: a shorter
    # alternation is a faster scan and a far more readable `citation-pattern` in the file.
    minimal: list[str] = []
    for s in secs:
        if not any(s == a or s.startswith(a + ".") for a in minimal):
            minimal.append(s)
    return minimal


def clause_pattern(sections: list[str]) -> re.Pattern:
    """The one citation regex, written once and reused for source, tests, CONFORMANCE.md and DIAGNOSTICS.md.

    ⛔ `(?![0-9])` IS THE WHOLE POINT. `§14.9.2` and `§14.9.27` are different statements (STRING and OPEN), and a
    plain prefix match on the shorter one sweeps in every citation of the longer — the dossier for STRING would
    have arrived full of OPEN's binder. The lookahead forbids a following DIGIT and nothing else, so a SUBCLAUSE
    (`§14.9.27.4`), a rule suffix (`§14.9.27 GR10`) and a bare `§14.9.27` all still match, which is exactly the
    set that is genuinely about this subject.

    The second arm matches the catalog's own rule-ids, `GR-14.9.27.4-10` — the code cites those directly
    (`IntrinsicArgumentRules.cs` carries `GR-15.2-6`), and a dossier that saw only `§` would miss them.
    """
    alts = "|".join(re.escape(s) for s in sorted(sections, key=len, reverse=True))
    return re.compile(rf"(?:§\s?|\b(?:GR|SR|FMT|RV|AR|DOC)-)(?:{alts})(?![0-9])")


def keywords(subject: str) -> tuple[list[str], str]:
    """The construct word(s) to search the grammar and file names with — derived, never looked up.

    ⛔ THERE IS NO CONSTRUCT→FILE MAP HERE AND THERE MUST NEVER BE ONE (CLAUDE.md rule 8). A hand-kept table of
    "OPEN → OpenBinder.cs, CobolIO.g4" is a sixth work register wearing a different hat: it would be authored by
    hand, consulted as truth, and stale the first time a file is renamed or a construct added — and its staleness
    would be INVISIBLE, because a dossier missing an entry looks exactly like a construct that has none. So the
    keyword comes out of the catalog's own `subject` field, which the spec extractor already maintains: strip the
    parenthetical qualifier and the trailing role word, then keep the ALL-CAPS COBOL words.

    ⚠ 201 of the catalog's 599 subjects are PROSE, not constructs — 'Abbreviated combined relation conditions',
    'Alignment of data items in storage'. There is no keyword to derive and no pretending otherwise; those fall
    back to the long lowercase words (file names only, never grammar bodies) and the returned provenance says
    `prose` so the agent knows the keyword half of its dossier is weak. The clause-citation half is unaffected —
    that is the exact half, and it is why it carries the weight.
    """
    stem = re.sub(r"\s*\(.*$", "", subject)
    stem = SUBJECT_ROLE.sub("", stem)
    # ⚠ A ONE-LETTER WORD IS A KEYWORD ONLY WHEN IT IS THE ENTIRE NAME — §15's `E function` (Euler's number) is a
    # real construct called `E`. Anything looser is worse than nothing: `A conforming implementation` yields the
    # article `A`, and the subject `Byte` yields its own initial `B`, because the ALL-CAPS arm happily matches
    # the capital of a Capitalised prose word. The test is "is this the whole stem", not a length floor.
    caps = [w.upper() for w in CAPS_WORD.findall(stem)
            if (len(w) >= 2 or w == stem.strip()) and w.upper() not in KEYWORD_NOISE]
    if caps:
        return list(dict.fromkeys(caps))[:6], "construct"
    prose = [w.lower() for w in PROSE_WORD.findall(stem) if w.lower() not in PROSE_NOISE]
    return list(dict.fromkeys(prose))[:3], "prose"


def role_of(subject: str) -> str:
    """`OPEN statement` → `statement`. The grammar names its rules keyword+role (`openStatement`), and a rule
    named EXACTLY that is the construct's own rule rather than a neighbour that merely mentions it."""
    m = SUBJECT_ROLE.search(re.sub(r"\s*\(.*$", "", subject))
    return m.group(1).lower() if m else ""


@functools.lru_cache(maxsize=None)
def corpus(kind: str) -> tuple[tuple[str, tuple[str, ...]], ...]:
    """Every file of one kind, read ONCE per run and shared by every subject in the batch.

    A batch is dozens of subjects over one unchanged tree; re-reading 2,000 files per subject would make the
    dossier cost more than the search it replaces.
    """
    files: dict[str, tuple[str, ...]] = {}
    for root, pattern in CORPUS[kind]:
        for p in sorted((REPO / root).glob(pattern)):
            rel = p.relative_to(REPO).as_posix()
            if rel in files or any(d in "/" + rel for d in SKIP_DIRS):
                continue
            files[rel] = tuple(p.read_text(encoding="utf-8", errors="replace").splitlines())
    return tuple(files.items())


def snip(line: str) -> str:
    text = " ".join(line.split())
    return text if len(text) <= SNIP else text[:SNIP] + " …"


def citing(files, pat: re.Pattern, cap: int = MAX_LINES) -> dict:
    """Citing lines, capped — but capped so that EVERY citing file survives before any file gets a second line.

    ⚠ A naive `hits[:40]` would spend the whole budget on the first two files and drop eleven others entirely,
    and the agent would never learn those files exist. The map matters more than the territory: take one line
    from each file, then a second from each, and so on.
    """
    per_file: dict[str, list[dict]] = {}
    dropped = 0
    for rel, lines in files:
        for i, line in enumerate(lines, 1):
            if not pat.search(line):
                continue
            hits = per_file.setdefault(rel, [])
            if len(hits) < MAX_PER_FILE:
                hits.append({"file": rel, "line": i, "text": snip(line)})
            else:
                dropped += 1
    chosen: list[dict] = []
    for round_ in range(MAX_PER_FILE):
        for hits in per_file.values():
            if round_ < len(hits):
                if len(chosen) < cap:
                    chosen.append(hits[round_])
                else:
                    dropped += 1
    chosen.sort(key=lambda h: (h["file"], h["line"]))
    return {"files": len(per_file), "lines": chosen, "truncated": dropped}


def tokens(name: str) -> set[str]:
    return {t.lower() for t in CAMEL.findall(name)}


def kw_parts(kw: str) -> list[str]:
    """`BACKGROUND-COLOR` → background · color.

    ⛔ A HYPHENATED KEYWORD MUST BE COMPARED PART BY PART, because nothing it is compared against keeps the
    hyphen: ANTLR spells the rule `backgroundColorClause` and the token `BACKGROUND_COLOR`, C# spells the file
    `BackgroundColor.cs`, and a golden spells it `background_color.cob`. Matching the hyphenated string whole
    silently found NOTHING for every one of the 30-odd hyphenated constructs — the shape a keyword search fails
    at without ever looking like it failed.
    """
    return [p.rstrip("s") for p in re.split(r"[-_\s]+", kw.lower()) if p]


def named(files, kws: list[str]) -> dict:
    """Files whose NAME carries the construct word — `SequentialIoBinder.cs` is found by its citation, but
    `intrinsics_trim.cob` and `pb97_value_edited_truncation.cob` are found only here.

    ⛔ A SHORT KEYWORD MATCHES ONLY AS A WHOLE TOKEN, never as a substring. `IF statement` returned FORTY
    filenames on the first run — `verify`, `modify`, `notify`, `unified` — a category of pure noise presented
    with exactly the authority of a real hit. Splitting the base name on case and punctuation and requiring the
    keyword to BE one of the pieces removes all of them and loses nothing; a keyword of four characters or more
    may still match as a substring, because `trimmed`/`opening` are real.

    Files matching EVERY keyword of a multi-word clause (`RECORD KEY` → `recordKeyClause.cs`) rank above files
    matching only one, then a whole-token hit above a substring.

    ⚠ AND A PARTIAL MATCH ON A SHORT KEYWORD ALONE IS NOT A MATCH. `GO TO statement` splits into two two-letter
    words, and `to` on its own pulled in twenty-five `move-national-to-an.cob`-shaped goldens that have nothing
    to do with GO TO. A word that short only carries the construct's identity in company: when a subject has
    several keywords, a file must hit a substantial one, or hit them all.
    """
    if not kws:
        return {"files": [], "truncated": 0}
    wanted = [(k, kw_parts(k), "".join(kw_parts(k))) for k in kws]
    scored: list[tuple[int, int, str]] = []
    for rel, _ in files:
        stem = rel.rsplit("/", 1)[-1]
        toks = {t.rstrip("s") for t in tokens(stem)}
        # Separator-free and ORDER-PRESERVING, so `BACKGROUND-COLOR` can meet `BackgroundColor.cs` and
        # `background_color.cob` alike. (Joining `tokens()` would not do: it is a set, so the order is arbitrary.)
        flat = FLATTEN.sub("", stem.lower())
        hits = [0 if all(p in toks for p in parts) else 1 if len(k) >= 4 and joined in flat else 2
                for k, parts, joined in wanted]
        missed = sum(1 for h in hits if h == 2)
        if missed == len(wanted):
            continue
        if len(wanted) > 1 and missed and not any(h < 2 and len(k) >= 4 for h, (k, _, _) in zip(hits, wanted)):
            continue
        scored.append((missed, min(hits), rel))
    scored.sort()
    return {"files": [rel for *_, rel in scored[:MAX_FILES]], "truncated": max(0, len(scored) - MAX_FILES)}


@functools.lru_cache(maxsize=None)
def grammar_rules() -> tuple[dict, ...]:
    """Every ANTLR rule in the grammar, as {file, line, name, text}, with the comment block above it.

    ⚠ THE LEADING COMMENT IS PART OF THE RULE for this purpose. The grammar's ISO citations and its
    superset-parses-here / gated-at-bind notes live in the comment above the rule, not inside it — quoting the
    rule body alone would hand the agent the shape and withhold the reasoning it most needs to verify.
    """
    out: list[dict] = []
    for rel, lines in corpus("grammar"):
        i = 0
        while i < len(lines):
            m = RULE_HEAD.match(lines[i])
            if not m:
                i += 1
                continue
            start = i
            end = i
            while end < len(lines) and lines[end].strip() != ";" and not lines[end].rstrip().endswith(";"):
                end += 1
            if end >= len(lines):        # unterminated — not a rule after all (a stray identifier line)
                i += 1
                continue
            # ⚠ THE WHOLE COMMENT BLOCK IS SEARCHED, only the tail is QUOTED. This grammar's blocks run to a
            # dozen lines and the ISO citation is as often at the top as at the bottom: a 6-line window measured
            # from the rule missed `functionArgument`'s "TRIM LEADING/TRAILING §15.96" by two lines, which is
            # how TRIM's dossier came back with zero grammar rules the first time it was run.
            lead = []
            j = start - 1
            while j >= 0 and lines[j].lstrip().startswith("//"):
                lead.insert(0, lines[j])
                j -= 1
            body = list(lines[start:end + 1])
            out.append({"rule": m.group(1), "file": rel, "line": start + 1,
                        "text": "\n".join(lead[-MAX_LEAD_COMMENT:] + body[:MAX_RULE_LINES]),
                        # ⛔ THE SEARCH TEXT INCLUDES THE LEAD COMMENT, and it must. The first cut searched the
                        # rule BODY only, and TRIM came back with zero grammar rules — because a §15 function has
                        # no rule of its own and its only grammar trace is the comment above
                        # `CobolExpressions.g4`'s argument-list rule, naming "TRIM LEADING/TRAILING §15.96". The
                        # citations live in the comments; a search that skips them cannot find a construct that
                        # is implemented but not separately parsed.
                        "_search": "\n".join(lead + body)})
            i = end + 1
    return tuple(out)


def grammar_for(kws: list[str], provenance: str, pat: re.Pattern, role: str = "") -> dict:
    """The grammar rules for the construct — by rule NAME, by the CLAUSE the rule's comment cites, by keyword.

    ⭐ THE CITATION ARM CARRIES THE MOST WEIGHT and is why the same regex is threaded in here. A grammar comment
    reading `// ISO §12.4.5.2 SR1: SELECT comes first` is the grammar author telling this dossier exactly which
    rule implements the clause — a better answer than any keyword can give, and the only answer available for a
    construct whose parse is generic.

    ⚠ A PROSE SUBJECT GETS NAME AND CITATION MATCHES ONLY. `alignment`/`literal` as a keyword inside a comment is
    an ordinary English word, and matching it would return a dozen unrelated rules with the confidence of a hit.
    """
    parts = [set(kw_parts(k)) for k in kws]
    # ANTLR spells a hyphenated COBOL word with an underscore (`BACKGROUND_COLOR`), so both spellings are tried.
    kw_pats = [re.compile(rf"\b{re.escape(k)}\b") for k in
               {k.upper() for k in kws} | {k.upper().replace("-", "_") for k in kws}]
    # `OPEN statement` → the rule named exactly {open, statement}. Under an 8-rule cap this matters: without it
    # `usingByValue` and `callByValue` (BY VALUE — a different construct) tie with `valueClause` on one keyword
    # each and win on file order.
    exact_name = set().union(*parts) | ({role} if role else set()) if parts else set()
    scored: list[tuple[tuple, dict]] = []
    for rule in grammar_rules():
        rule_toks = {t.rstrip("s") for t in tokens(rule["rule"])}
        by_name = sum(1 for ps in parts if ps <= rule_toks)
        by_cite = len(pat.findall(rule["_search"]))
        by_kw = 0 if provenance == "prose" else sum(1 for p in kw_pats if p.search(rule["_search"]))
        if not (by_name or by_cite or by_kw):
            continue
        # The construct's own rule, then anything named or citing it, then a bare keyword mention.
        exact = bool(parts) and rule_toks == exact_name
        scored.append(((0 if exact else 1, 0 if (by_name or by_cite) else 1, -(by_name + by_cite), -by_kw,
                        rule["file"], rule["line"]), rule))
    scored.sort(key=lambda t: t[0])
    kept = [{k: r[k] for k in ("rule", "file", "line", "text")} for _, r in scored[:MAX_RULES]]
    return {"rules": kept, "truncated": max(0, len(scored) - MAX_RULES)}


@functools.lru_cache(maxsize=None)
def doc_lines(path: pathlib.Path) -> tuple[str, ...]:
    """A doc read once per run. `docs/CONFORMANCE.md` is half a megabyte of very long rows; re-reading it for
    each of a batch's subjects would be the largest single cost in here."""
    return tuple(path.read_text(encoding="utf-8", errors="replace").splitlines()) if path.exists() else ()


def doc_citing(path: pathlib.Path, pat: re.Pattern) -> dict:
    rel = path.relative_to(REPO).as_posix()
    hits = []
    dropped = 0
    for i, line in enumerate(doc_lines(path), 1):
        if not pat.search(line):
            continue
        if len(hits) >= MAX_LINES:
            dropped += 1
            continue
        entry = {"file": rel, "line": i, "text": snip(line)}
        row = A1_ROW.match(line)      # an Annex A.1 register row carries its item number
        if row:
            entry["a1-item"] = int(row.group(1))
        hits.append(entry)
    return {"lines": hits, "truncated": dropped}


def diagnostics_citing(pat: re.Pattern) -> dict:
    """DIAGNOSTICS.md is a generated table — split the row so the agent gets a code and an id, not a wall.

    ⚠ A row that does not split into the expected columns is emitted RAW rather than skipped. The file is
    generated and its shape can change; a parser that silently returned nothing on a new shape would read as
    "this clause has no diagnostic", which is the one answer it must never invent.
    """
    rel = DIAGNOSTICS_DOC.relative_to(REPO).as_posix()
    entries = []
    dropped = 0
    for i, line in enumerate(doc_lines(DIAGNOSTICS_DOC), 1):
        if not pat.search(line):
            continue
        if len(entries) >= MAX_LINES:
            dropped += 1
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")] if line.lstrip().startswith("|") else []
        if len(cells) >= 6:
            entries.append({"file": rel, "line": i, "code": cells[0], "id": cells[1], "severity": cells[2],
                            "iso": cells[3], "title": snip(cells[5])})
        else:
            entries.append({"file": rel, "line": i, "text": snip(line)})
    return {"entries": entries, "truncated": dropped}


@functools.lru_cache(maxsize=1)
def register_notes() -> tuple[dict, ...]:
    """`kb/Work/` read once per run — 333 notes, and a batch asks for them once per subject."""
    return tuple(work.load())


def register_for(sections: list[str]) -> dict:
    """`kb/Work/` notes whose `spec_refs` or `inventory_rows` land inside this subject.

    ⛔ THIS IS THE "DO NOT RE-REPORT A LANDED FIX" HALF, and it is why the note's `status` is carried. Batch
    prompts have to tell agents which defects are already closed, and DESIGN §8 item 8 forbids writing that list
    by hand — it went stale twice. This derives the subject's slice of it, in the file, at generation time.

    ⚠ CONTAINMENT IS ONE-WAY on purpose: a note referencing `§14.9.27.4` belongs to OPEN, a note referencing
    `§14` does not. Matching ancestors too would attach the half-dozen whole-clause analyses to all 53 statements.
    """
    notes = []
    for it in register_notes():
        refs = [str(r).strip().strip('"') for r in (it.get("spec_refs") or [])]
        rows = [str(r).strip().strip('"') for r in (it.get("inventory_rows") or [])]
        matched = sorted({r for r in refs if any(r == s or r.startswith(s + ".") for s in sections)})
        matched_rows = sorted({r for r in rows
                               if (m := RULE_ID.match(r))
                               and any(m.group(1) == s or m.group(1).startswith(s + ".") for s in sections)})
        if not matched and not matched_rows:
            continue
        notes.append({"id": it.get("id"), "title": it.get("title"), "status": it.get("status"),
                      "kind": it.get("kind"), "spec-refs": matched, "inventory-rows": matched_rows})
    notes.sort(key=lambda n: (n["status"] != "open", str(n["id"])))
    return {"notes": notes[:MAX_FILES], "truncated": max(0, len(notes) - MAX_FILES)}


def build_dossier(sections: list[str], subject: str) -> dict:
    """THE ONE ENTRY POINT: a subject's clause numbers + its name in, its pre-computed discovery out.

    Everything an adjudicating agent used to grep for, in the order it used to grep for it. Called once per
    SUBJECT (not per part) and pasted into each of the subject's part files — a part-1 agent that could not see
    part-2's clause would otherwise get a dossier with holes in it.
    """
    secs = dossier_sections(sections)
    pat = clause_pattern(secs) if secs else re.compile(r"(?!)")
    kws, provenance = keywords(subject)
    src, tst = corpus("source"), corpus("tests")
    return {
        "how-to-read": HOW_TO_READ,
        "sections-searched": secs,
        "citation-pattern": pat.pattern,
        "keywords": kws,
        "keywords-derived-from": provenance,
        "grammar": grammar_for(kws, provenance, pat, role_of(subject)),
        "source": {"citing": citing(src, pat), "named": named(src, kws)},
        "tests": {"citing": citing(tst, pat), "named": named(tst, kws)},
        "determinations": doc_citing(CONFORMANCE_DOC, pat),
        "register": register_for(secs),
        "diagnostics": diagnostics_citing(pat),
    }


def dossier_counts(d: dict) -> dict:
    """The one-line summary printed per subject — and the thing to read when a dossier comes back empty."""
    return {
        "grammar": len(d["grammar"]["rules"]),
        "source": d["source"]["citing"]["files"],
        "src-named": len(d["source"]["named"]["files"]),
        "tests": d["tests"]["citing"]["files"],
        "test-named": len(d["tests"]["named"]["files"]),
        "determ": len(d["determinations"]["lines"]),
        "register": len(d["register"]["notes"]),
        "diags": len(d["diagnostics"]["entries"]),
    }


def main() -> int:
    # ⚠ BEFORE parse_args, not after. argparse prints this module's docstring for --help, and the docstring
    # carries ⚠/⛔; on a cp1252 Windows console that raises UnicodeEncodeError from inside argparse, so
    # `--help` crashed with a traceback instead of printing help. Reconfiguring afterwards was too late.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("clauses", nargs="+", help="clauses or ranges, e.g. 15.32-15.44 or 14.9.1")
    ap.add_argument("--max-rules", type=int, default=DEFAULT_MAX_RULES,
                    help=f"most rules in one agent's file before the subject is split (default {DEFAULT_MAX_RULES})")
    ap.add_argument("--no-dossier", action="store_true",
                    help="omit the pre-computed discovery (grammar rule, citing source, tests, CONFORMANCE.md "
                         "determinations, kb/Work notes, diagnostics) from each file. ON by default — without it "
                         "every agent re-runs the same three greps, which is where batch 8's 574M cache-read "
                         "tokens went")
    ap.add_argument("--include-adjudicated", action="store_true",
                    help="⛔ NOT FOR A BATCH. Keep rules that already carry a verdict. A Phase-B batch must "
                         "never re-issue an adjudicated rule; this exists so a Phase-C agent re-opening a "
                         "PARTIAL row — and this script's own self-check — can still get the subject's dossier, "
                         "which is otherwise unreachable for any fully-adjudicated construct")
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    rules = json.loads(CATALOG.read_text(encoding="utf-8"))["rules"]
    done = set() if args.include_adjudicated else {
        r["rule-id"] for r in json.loads(INVENTORY.read_text(encoding="utf-8")) if r.get("verdict")}

    chosen = [r for r in rules if selected(r["section"], args.clauses) and r["id"] not in done]
    skipped = sum(1 for r in rules if selected(r["section"], args.clauses) and r["id"] in done)
    if not chosen:
        print(f"nothing to do — {skipped} rule(s) in that range already carry a verdict")
        return 0

    by_subject: dict[str, list[dict]] = collections.defaultdict(list)
    for r in chosen:
        by_subject[r["subject"]].append(r)

    args.out.mkdir(parents=True, exist_ok=True)
    slugs = []
    oversized = []
    summaries: list[tuple[str, list[str], dict]] = []
    part_index: dict[str, list[dict]] = {}
    taken: collections.Counter = collections.Counter()
    for subject, rows in sorted(by_subject.items()):
        # Truncation at MAX_SLUG can make two long §8 subject names share a stem; disambiguate deterministically
        # (the iteration is sorted) rather than let the second overwrite the first.
        base = base_slug(subject)
        taken[base] += 1
        if taken[base] > 1:
            base = f"{base}-{taken[base]}"
        parts = partition(rows, args.max_rules)
        # ⚠ ONCE PER SUBJECT, not per part, and from the WHOLE subject's sections — a part-1 agent handed a
        # dossier built from part 1's clauses only would be missing the very files that implement part 2.
        dossier = None if args.no_dossier else build_dossier(sorted({r["section"] for r in rows}), subject)
        if dossier is not None:
            summaries.append((subject, dossier["keywords"], dossier_counts(dossier)))
        # ⛔ THE PARTITION INVARIANT. If `partition` ever drops a rule, that rule is never issued to any agent
        # and therefore never adjudicated — and NOTHING downstream would say so: the batch would look complete,
        # the verdicts would merge cleanly, and the inventory would simply never move for it. That is the same
        # failure this session closed across the test harnesses (§11 A12c): a missing item read as no item.
        # Assert it here, where it is cheap, rather than discover it as an unexplained GAP months later.
        flat = [r for p in parts for r in p]
        assert len(flat) == len(rows) and {id(r) for r in flat} == {id(r) for r in rows}, (
            f"partition lost or duplicated rules for {subject!r}: {len(rows)} in, {len(flat)} out")
        if len(parts) > 1:
            oversized.append((subject, len(rows), len(parts)))
        sibling_slugs = [part_slug(base, i, len(parts)) for i, _ in enumerate(parts)]
        clause_map = collections.Counter(r["section"] for r in rows)
        for pi, (part, slug) in enumerate(zip(parts, sibling_slugs)):
            doc = {
                "subject": subject,
                "clauses": sorted({r["section"] for r in part}, key=clause_key),
                "rules": [{"rule-id": r["id"], "kind": r["kind"], "section": r["section"], "text": r["text"]}
                          for r in sorted(part, key=lambda x: (x["kind"], x["id"]))],
            }
            if dossier is not None:
                doc["dossier"] = dossier
            if len(parts) > 1:
                # ⛔ AN AGENT MUST KNOW IT IS SEEING A SLICE. A statement's syntax rules and its general rules
                # interlock; adjudicating GR7 while unaware that SR12 exists is how a verdict comes back
                # confidently wrong. So a split file says so, names its siblings, and carries the WHOLE
                # subject's clause map — it withholds rule TEXT it does not own, never the fact of it.
                doc["part"] = {
                    "index": pi + 1,
                    "of": len(parts),
                    "sibling-slugs": sibling_slugs,
                    "whole-subject-clause-map": {c: n for c, n in sorted(clause_map.items(), key=lambda kv: clause_key(kv[0]))},
                    "note": (f"This file holds PART {pi + 1} of {len(parts)} of '{subject}' "
                             f"({len(rows)} rules total, split because one agent adjudicating them all reliably "
                             f"degrades). Adjudicate ONLY the rules below, but read the clause map: rules you do "
                             f"not see here exist and may bear on yours. If a verdict depends on a rule outside "
                             f"this part, say so in the notes rather than guessing."),
                }
            # ⛔ THE INVARIANT IS ON THE SLUG, NOT ON THE WRITE — and finding that out is the whole lesson. The
            # first version of this check asked whether the file existed and was non-empty afterwards, and it
            # passed on the alternate-data-stream bug: Windows really had created a stream, `is_file()` really
            # was True and `st_size` really was 3,674. A check downstream of a defect can be satisfied BY the
            # defect. So screen the name, where the defect is, and where the answer is the same on every OS.
            if not SLUG_OK.fullmatch(slug):
                raise SystemExit(f"⛔ slug {slug!r} (subject {subject!r}) is not [a-z0-9-] — it becomes a file "
                                 f"name, and a stray ':' or '*' silently redirects or refuses the write")
            (args.out / f"in-{slug}.json").write_text(
                json.dumps(doc, indent=1, ensure_ascii=False), encoding="utf-8")
            slugs.append(slug)
            if len(parts) > 1:
                part_index[slug] = part

    # ⛔ THE BATCH IS WHAT THE GLOB CAN SEE. The workflow reads `in-*.json` from this directory, so a file
    # written under a name that glob does not return is a subject nobody adjudicates — and the slug list printed
    # below would still promise it. Compare the two populations here, once, where the answer is cheap.
    visible = {p.name for p in args.out.glob("in-*.json")}
    lost = [s for s in slugs if f"in-{s}.json" not in visible]
    if lost:
        raise SystemExit(f"⛔ {len(lost)} input file(s) are not visible to the workflow's in-*.json glob in "
                         f"{args.out}: {lost[:5]} — the batch would run that many agents short, silently")

    print(f"{len(chosen)} rule(s) over {len(by_subject)} subject(s) -> {len(slugs)} agent file(s); "
          f"{skipped} already adjudicated and skipped")
    if oversized:
        print(f"\n⚠ {len(oversized)} subject(s) exceeded --max-rules={args.max_rules} and were SPLIT "
              f"(largest first). Each part names its siblings and carries the whole subject's clause map:")
        for subject, n, p in sorted(oversized, key=lambda t: -t[1]):
            print(f"    {subject:<40} {n:>4} rules -> {p} parts")
        print(f"\n  part -> clauses -> rule count:")
        for slug, part in sorted(part_index.items()):
            print(f"    {slug:<40} {','.join(sorted({r['section'] for r in part}, key=clause_key)):<28} "
                  f"{len(part):>3}")
    if summaries:
        # ⚠ READ THIS TABLE BEFORE FANNING OUT. A row of zeros is not proof the construct is unimplemented — it
        # is the dossier saying its own derivation found nothing, and it usually means the keyword is `prose`
        # (an §8 concept) or the code implements the clause without citing it. Either way that agent starts
        # cold, and knowing WHICH agent starts cold is worth the six seconds this table costs.
        cols = ("grammar", "source", "src-named", "tests", "test-named", "determ", "register", "diags")
        print("\ndossier per subject (0 = this derivation found none, NOT 'the compiler has none'):")
        print(f"    {'subject':<44} " + " ".join(f"{c:>9}" for c in cols) + "   keywords")
        for subject, kws, counts in summaries:
            print(f"    {subject[:44]:<44} " + " ".join(f"{counts[c]:>9}" for c in cols)
                  + "   " + (",".join(kws) if kws else "—"))
    print(f"\ninput files -> {args.out}")
    print("\nslug list for the workflow script:\n")
    print(json.dumps(slugs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
