// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using CobolNet.Binding;
using CobolNet.Binding.Bound;
using CobolSharp.Compiler.Generated;
using Microsoft.CodeAnalysis.CSharp;

namespace CobolNet.CodeGen;

using Core = CobolParserCore;

/// <summary>
/// The Roslyn (C#) backend: renders a <see cref="BoundProgram"/> to typed-native C# source. COBOL data is .NET data
/// (native fields, no byte substrate) and COBOL verbs are operations on those typed values, calling the clean
/// <c>CobolNum</c>/<c>CobolString</c> runtime substrates for COBOL-correct semantics.
/// </summary>
/// <remarks>
/// <para>The backend consumes the bound semantic tree built by <see cref="StatementBinder"/> — every reference is
/// already a <see cref="Place"/>, every literal decoded, every expression/condition a bound node — so this class
/// never walks the ANTLR parse tree for the PROCEDURE DIVISION; it only renders. (The DATA DIVISION is emitted from
/// the <see cref="DataBinder"/> model.) An unsupported construct surfaces as a <c>Bound*Error</c>/<c>BoundUnsupported</c>
/// node here and emits a LOUD <c>NotImplemented</c> guard (COBOLNET_DESIGN §1.4), never a silent no-op.</para>
/// <para><b>Status — G2:</b> groups→record structs, OCCURS→arrays, qualified/subscripted refs, figurative + signed
/// DISPLAY, level-88. Control flow is a sequential paragraph call-chain (the G4 PC dispatcher replaces it).</para>
/// </remarks>
public sealed class CSharpEmitter
{
    private DataBinder _data = new();

    /// <summary>Emit C# source for the first program unit in <paramref name="tree"/>.</summary>
    public string Emit(Core.CompilationUnitContext tree)
    {
        Core.ProgramUnitContext? program = tree.compilationGroup().SelectMany(g => g.programUnit()).FirstOrDefault();

        _data = new DataBinder();
        if (program is not null) _data.Bind(program);
        var refs = new ReferenceResolver(_data);
        BoundProgram bound = program is not null ? new StatementBinder(_data, refs).Bind(program) : new BoundProgram([]);

        var w = new CodeWriter();
        w.Line("// <auto-generated>");
        w.Line("//   Generated by COBOL.NET — do not edit. A COBOL program compiled to typed-native C#.");
        w.Line("// </auto-generated>");
        w.Line("#nullable enable");
        w.Line("using CobolNet.Runtime;          // CobolNum / CobolString typed-native runtime substrates");
        w.Line();

        using (w.Block("internal static class Program"))
        {
            EmitWorkingStorage(w);

            if (bound.Paragraphs.Count > 0)
            {
                w.Line();
                // Main runs the paragraphs in source order — COBOL "fall-through" is a sequential call chain;
                // STOP RUN / GOBACK throw StopRun to unwind the whole chain (ISO §14.9.43). The PC dispatcher (G4)
                // replaces this with pc-indexed control flow.
                using (w.Block("private static void Main()"))
                {
                    using (w.Block("try"))
                        foreach (var p in bound.Paragraphs) w.Line($"{p.Method}();");
                    w.Line("catch (StopRun) { }");
                }
                foreach (var p in bound.Paragraphs)
                {
                    w.Line();
                    using (w.Block($"private static void {p.Method}()"))
                        foreach (var st in p.Statements) EmitStatement(st, w);
                }
            }
            else
                using (w.Block("private static void Main()")) { }
        }

        return w.ToString();
    }

    // ════════════════════════════ DATA DIVISION → typed fields ════════════════════════════════════════════

    /// <summary>
    /// Emit the DATA DIVISION as typed-native C#: a nested <c>record struct</c> type per group, a static numeric
    /// <c>NumProfile</c> per numeric leaf, the INDEXED BY index fields, and one static field per top-level (01/77)
    /// item (a group/table initialized with a composed initializer, an elementary item with its VALUE-or-default).
    /// A COBOL record IS a .NET record (COBOLNET_DESIGN §3.2) — no byte substrate, no flattening.
    /// </summary>
    private void EmitWorkingStorage(CodeWriter w)
    {
        foreach (var root in _data.Roots) EmitStructTypeDecls(root, w);
        foreach (var root in _data.Roots) EmitProfiles(root, w);
        foreach (var (name, field) in _data.IndexFields)
            w.Line($"private static long {field} = 1;   // INDEX-NAME {name}");
        foreach (var root in _data.Roots)
            if (root.IsGroup || root.IsElementary)
            {
                string comment = root.CobolName is { } n ? $"   // {n}{(root.Occurs is { } o ? $" OCCURS {o}" : "")}" : "";
                w.Line($"private static {root.FieldType} {root.CsName} = {FieldInit(root)};{comment}");
            }
    }

    private static void EmitStructTypeDecls(DataItem item, CodeWriter w)
    {
        if (!item.IsGroup) return;
        foreach (var child in item.Children) EmitStructTypeDecls(child, w);   // nested types first (any order is fine)
        using (w.Block($"private record struct {item.StructName}"))
            foreach (var child in item.Children)
                if (child.IsGroup || child.IsElementary)
                    w.Line($"public {child.FieldType} {child.CsName};   // {child.CobolName ?? "FILLER"}");
    }

    private static void EmitProfiles(DataItem item, CodeWriter w)
    {
        if (item.IsElementary && item.Pic is { Category: PicCategory.Numeric, IsFloat: false })
            w.Line($"private static readonly NumProfile {item.ProfileName} = {item.Pic.ProfileInitializer};");
        foreach (var child in item.Children) EmitProfiles(child, w);
    }

    /// <summary>The C# initializer for a field: an array literal for an OCCURS table (every element initialized so
    /// none is left at <c>default</c>), a composed object-initializer for a group, else the elementary VALUE.</summary>
    private static string FieldInit(DataItem item)
    {
        if (item.Occurs is { } n)
        {
            string element = item.IsGroup ? ComposedInit(item) : InitializerFor(item);
            return $"new {item.ElementType}[] {{ {string.Join(", ", Enumerable.Repeat(element, n))} }}";
        }
        return item.IsGroup ? ComposedInit(item) : InitializerFor(item);
    }

    private static string ComposedInit(DataItem group)
    {
        var parts = group.Children
            .Where(c => c.IsGroup || c.IsElementary)
            .Select(c => $"{c.CsName} = {FieldInit(c)}");
        return $"new {group.StructName} {{ {string.Join(", ", parts)} }}";
    }

    /// <summary>The C# initializer expression for an elementary item, from its VALUE clause or the COBOL default.</summary>
    private static string InitializerFor(DataItem item)
    {
        var pic = item.Pic!;
        if (item.RawValue is not { } raw) return pic.DefaultInitializer;

        // Figurative constants (ZERO / SPACE / HIGH-VALUE / LOW-VALUE / QUOTE / NULL) fill the item to its width.
        if (FigurativeInitializer(raw, pic) is { } fig) return fig;

        return pic.Category switch
        {
            PicCategory.Alphanumeric or PicCategory.NumericEdited =>
                $"CobolString.Store({CsStringLiteral(DecodeCobolString(raw))}, {pic.Length})",
            PicCategory.Numeric when pic.IsFloat => RawValueAsFloat(raw, pic),
            PicCategory.Numeric => UnscaledAtScale(raw, pic.Scale),
            _ => pic.DefaultInitializer,
        };
    }

    /// <summary>If <paramref name="raw"/> is a figurative constant, its C# initializer given the receiver's category
    /// and width; otherwise null (ISO §8.3.1.2; HIGH/LOW = U+00FF/U+0000 per COBOLNET_DESIGN §14.9).</summary>
    private static string? FigurativeInitializer(string raw, PicInfo pic)
    {
        string? fillChar = raw.ToUpperInvariant() switch
        {
            "ZERO" or "ZEROS" or "ZEROES" => "'0'",
            "SPACE" or "SPACES" => "' '",
            "HIGH-VALUE" or "HIGH-VALUES" => "'\\u00ff'",
            "LOW-VALUE" or "LOW-VALUES" or "NULL" or "NULLS" => "'\\u0000'",
            "QUOTE" or "QUOTES" => "'\\\"'",
            _ => null,
        };
        if (fillChar is null) return null;
        return pic.Category is PicCategory.Numeric ? pic.DefaultInitializer : $"new string({fillChar}, {pic.Length})";
    }

    /// <summary>A numeric VALUE literal as a C# float/double literal for a COMP-1/COMP-2 item.</summary>
    private static string RawValueAsFloat(string raw, PicInfo pic) =>
        pic.Usage == Usage.Float ? $"{raw.Trim().TrimStart('+')}f" : $"{raw.Trim().TrimStart('+')}d";

    /// <summary>Render a numeric literal as a C# <c>long</c> holding its UNSCALED value at <paramref name="scale"/>
    /// fractional digits — e.g. <c>"3.5"</c> at scale 2 → <c>350L</c>, <c>"12"</c> at scale 0 → <c>12L</c>.</summary>
    private static string UnscaledAtScale(string raw, int scale)
    {
        string t = raw.Trim().TrimStart('+');
        bool neg = t.StartsWith('-');
        if (neg) t = t[1..];
        int dot = t.IndexOf('.');
        string intPart = dot < 0 ? t : t[..dot];
        string fracPart = dot < 0 ? "" : t[(dot + 1)..];
        if (fracPart.Length < scale) fracPart = fracPart.PadRight(scale, '0');
        else if (fracPart.Length > scale) fracPart = fracPart[..scale];
        string digits = (intPart + fracPart).TrimStart('0');
        return $"{(neg ? "-" : "")}{(digits.Length == 0 ? "0" : digits)}L";
    }

    // ════════════════════════════ PROCEDURE DIVISION → statements ═════════════════════════════════════════

    private void EmitStatement(BoundStatement s, CodeWriter w)
    {
        switch (s)
        {
            case BoundStop: w.Line("throw new StopRun();"); break;
            case BoundUnsupported u: w.Line(LoudStmt(u.Feature)); break;
            case BoundDisplay d: EmitDisplay(d, w); break;
            case BoundMove m: EmitMove(m, w); break;
            case BoundAddTo a: EmitInPlace(a.Targets, "+", Fold(a.Addends), w); break;
            case BoundAddGiving a: EmitGiving(a.Targets, Fold(a.Addends), w); break;
            case BoundSubtractFrom a: EmitInPlace(a.Targets, "-", Fold(a.Minuends), w); break;
            case BoundSubtractGiving a: EmitGiving(a.Targets, Combine(Render(a.From), "-", Fold(a.Minuends)), w); break;
            case BoundMultiplyBy a: EmitInPlace(a.Targets, "*", Render(a.A), w); break;
            case BoundMultiplyGiving a: EmitGiving(a.Targets, Combine(Render(a.A), "*", Render(a.B)), w); break;
            case BoundDivideInto a: EmitDivide(a.Targets, null, Render(a.Divisor), w); break;
            case BoundDivideGiving a: EmitDivide(a.Targets, Render(a.Dividend), Render(a.Divisor), w); break;
            case BoundCompute c: foreach (var t in c.Targets) { _targetScale = ScaleOf(t); StoreArith(t, Render(c.Rhs), w); } break;
            case BoundIf iff: EmitIf(iff, w); break;
            case BoundInlinePerform p: EmitInlinePerform(p, w); break;
            case BoundOutOfLinePerform p: EmitOutOfLinePerform(p, w); break;
            case BoundSetConditions set: EmitSet(set, w); break;
            default: w.Line(LoudStmt($"bound statement '{s.GetType().Name}'")); break;
        }
    }

    private void EmitDisplay(BoundDisplay d, CodeWriter w)
    {
        var parts = d.Operands.Select(AsString).ToList();
        string image = parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
        w.Line(d.NoAdvancing ? $"System.Console.Write({image});" : $"System.Console.WriteLine({image});");
    }

    private void EmitMove(BoundMove m, CodeWriter w)
    {
        foreach (var target in m.Targets)
            if (target.Item.Pic is null)
                w.Line(LoudStmt($"MOVE to group item '{target.Item.CobolName}' (whole-group MOVE is G6)"));
            else
                w.Line(target.Write(ConvertSource(m.Source, target.Item)));
    }

    /// <summary>The C# expression a MOVE source converts to when stored into <paramref name="target"/>.</summary>
    private string ConvertSource(BoundOperand source, DataItem target)
    {
        var pic = target.Pic!;
        switch (pic.Category)
        {
            case PicCategory.Alphanumeric or PicCategory.NumericEdited:
                return $"CobolString.Store({AsString(source)}, {pic.Length})";
            case PicCategory.Numeric:
                NumX n = AsNum(source);
                return $"CobolNum.Store({n.Expr}, {n.Scale}, {target.ProfileName})";
            default:
                return "default";
        }
    }

    // ── Arithmetic ──────────────────────────────────────────────────────────────────────────────────────

    private void EmitInPlace(IReadOnlyList<Place> targets, string op, NumX value, CodeWriter w)
    {
        foreach (var t in targets) StoreArith(t, Combine(FieldNum(t), op, value), w);
    }

    private void EmitGiving(IReadOnlyList<Place> targets, NumX value, CodeWriter w)
    {
        foreach (var t in targets) StoreArith(t, value, w);
    }

    private void EmitDivide(IReadOnlyList<Place> targets, NumX? dividend, NumX divisor, CodeWriter w)
    {
        foreach (var t in targets)
        {
            _targetScale = ScaleOf(t);                       // the quotient is computed at the receiver's scale
            NumX num = dividend ?? FieldNum(t);              // DIVIDE … INTO with no GIVING divides the target itself
            StoreArith(t, Combine(num, "/", divisor), w);
        }
    }

    /// <summary>Store an arithmetic result into a numeric target place via <c>CobolNum.Store</c>.</summary>
    private static void StoreArith(Place target, NumX value, CodeWriter w)
    {
        if (target.Item.Pic is not { Category: PicCategory.Numeric, IsFloat: false })
        {
            w.Line(LoudStmt($"arithmetic into a non-fixed-point target '{target.Item.CobolName ?? target.Read()}'"));
            return;
        }
        w.Line(target.Write($"CobolNum.Store({value.Expr}, {value.Scale}, {target.Item.ProfileName})"));
    }

    // ── IF / PERFORM ───────────────────────────────────────────────────────────────────────────────────

    private void EmitIf(BoundIf iff, CodeWriter w)
    {
        using (w.Block($"if ({Render(iff.Condition)})"))
            foreach (var st in iff.Then) EmitStatement(st, w);
        if (iff.Else.Count > 0)
            using (w.Block("else"))
                foreach (var st in iff.Else) EmitStatement(st, w);
    }

    private void EmitInlinePerform(BoundInlinePerform p, CodeWriter w)
    {
        void Body() { foreach (var st in p.Body) EmitStatement(st, w); }
        switch (p.Control)
        {
            case PerformTimes t:
                using (w.Block($"for (long _i = 0; _i < {CountExpr(t.Count)}; _i++)")) Body();
                break;
            case PerformUntil u when u.TestAfter:
                using (w.Block("do")) Body();
                w.Line($"while (!({Render(u.Until)}));");
                break;
            case PerformUntil u:
                using (w.Block($"while (!({Render(u.Until)}))")) Body();
                break;
            default:   // PerformOnce
                using (w.Block("do")) Body();
                w.Line("while (false);");
                break;
        }
    }

    private void EmitOutOfLinePerform(BoundOutOfLinePerform p, CodeWriter w)
    {
        void Body() { foreach (var m in p.TargetMethods) w.Line($"{m}();"); }
        switch (p.Control)
        {
            case PerformTimes t:
                using (w.Block($"for (long _i = 0; _i < {CountExpr(t.Count)}; _i++)")) Body();
                break;
            case PerformUntil u when u.TestAfter:
                using (w.Block("do")) Body();
                w.Line($"while (!({Render(u.Until)}));");
                break;
            case PerformUntil u:
                using (w.Block($"while (!({Render(u.Until)}))")) Body();
                break;
            default:   // PerformOnce
                Body();
                break;
        }
    }

    private string CountExpr(BoundOperand count) => count switch
    {
        BoundNumericLiteral n => n.Text,
        BoundFieldOperand f => f.Place.Read(),
        BoundOperandError e => LoudValue("long", e.Feature),
        _ => "1",
    };

    private void EmitSet(BoundSetConditions set, CodeWriter w)
    {
        foreach (var (parent, cond) in set.Sets)
        {
            var (low, _) = cond.Values[0];   // SET TO TRUE stores the first VALUE (ISO §14.9.39 Format 5)
            string rhs = parent.Item.Pic?.Category switch
            {
                PicCategory.Alphanumeric or PicCategory.NumericEdited =>
                    $"CobolString.Store({CsStringLiteral(DecodeCobolString(low))}, {parent.Item.Pic.Length})",
                PicCategory.Numeric =>
                    $"CobolNum.Store({UnscaledAtScale(low, parent.Item.Pic.Scale)}, {parent.Item.Pic.Scale}, {parent.Item.ProfileName})",
                _ => LoudValue("string", $"SET condition '{cond.Name}' over a group parent"),
            };
            w.Line(parent.Write(rhs));
        }
    }

    // ════════════════════════════ Conditions → C# boolean ═════════════════════════════════════════════════

    private string Render(BoundCondition c) => c switch
    {
        BoundRelational r => RenderRelational(r),
        BoundLogical l => "(" + string.Join($" {l.Op} ", l.Operands.Select(Render)) + ")",
        BoundNot n => $"!({Render(n.Operand)})",
        BoundCondition88 c88 => RenderCondition88(c88),
        BoundSignCondition s => RenderSign(s),
        BoundConditionError e => LoudValue("bool", e.Feature),
        _ => LoudValue("bool", $"bound condition '{c.GetType().Name}'"),
    };

    private string RenderRelational(BoundRelational r)
    {
        if (IsStringOperand(r.Left) || IsStringOperand(r.Right))
            return $"CobolString.Compare({AsString(r.Left)}, {AsString(r.Right)}) {r.Op} 0";
        NumX l = AsNum(r.Left), rr = AsNum(r.Right);
        int s = Math.Max(l.Scale, rr.Scale);
        return $"{Align(l, s)} {r.Op} {Align(rr, s)}";
    }

    private static bool IsStringOperand(BoundOperand op) => op switch
    {
        BoundStringLiteral => true,
        BoundFieldOperand f => f.Place.Item.Pic?.Category is PicCategory.Alphanumeric or PicCategory.NumericEdited,
        _ => false,
    };

    private string RenderSign(BoundSignCondition s)
    {
        NumX v = Render(s.Expr);
        string test = s.Kind switch { 'P' => $"{v.Expr} > 0", 'N' => $"{v.Expr} < 0", _ => $"{v.Expr} == 0" };
        return s.Negated ? $"!({test})" : $"({test})";
    }

    private static string RenderCondition88(BoundCondition88 c)
    {
        string read = c.Parent.Read();
        bool isString = c.Parent.Item.IsGroup || c.Parent.Item.Pic?.Category is PicCategory.Alphanumeric or PicCategory.NumericEdited;
        var tests = c.Condition.Values.Select(v => RenderMembershipTest(read, c.Parent.Item, isString, v.Low, v.High));
        return "(" + string.Join(" || ", tests) + ")";
    }

    /// <summary>One VALUE-set membership test: equality for a singleton, an inclusive bound test for a THRU range.</summary>
    private static string RenderMembershipTest(string read, DataItem parent, bool isString, string low, string? high)
    {
        if (isString)
        {
            string lo = CsStringLiteral(DecodeCobolString(low));
            if (high is null) return $"CobolString.Compare({read}, {lo}) == 0";
            return $"(CobolString.Compare({read}, {lo}) >= 0 && CobolString.Compare({read}, {CsStringLiteral(DecodeCobolString(high))}) <= 0)";
        }
        int scale = parent.Pic?.Scale ?? 0;
        string loN = UnscaledAtScale(low, scale);
        if (high is null) return $"{read} == {loN}";
        return $"({read} >= {loN} && {read} <= {UnscaledAtScale(high, scale)})";
    }

    // ════════════════════════════ Operands → string / number ══════════════════════════════════════════════

    /// <summary>A bound operand rendered as a C# <see cref="string"/> (its DISPLAY image).</summary>
    private string AsString(BoundOperand op) => op switch
    {
        BoundStringLiteral s => CsStringLiteral(s.Value),
        BoundNumericLiteral n => CsStringLiteral(n.Text),
        BoundFieldOperand f => FieldAsString(f.Place),
        BoundComputedOperand => LoudValue("string", "computed expression in a string context"),
        BoundOperandError e => LoudValue("string", e.Feature),
        _ => LoudValue("string", $"bound operand '{op.GetType().Name}'"),
    };

    private static string FieldAsString(Place p)
    {
        if (p.Item.IsGroup) return LoudValue("string", $"DISPLAY of group item '{p.Item.CobolName}' (whole-group image is G6)");
        return p.Item.Pic switch
        {
            { Category: PicCategory.Numeric, IsFloat: false } => $"CobolNum.FormatDisplay({p.Read()}, {p.Item.ProfileName})",
            { Category: PicCategory.Numeric } => $"{p.Read()}.ToString()",            // COMP-1/2 float — refine later
            { Category: PicCategory.Alphanumeric or PicCategory.NumericEdited } => p.Read(),
            _ => $"{p.Read()}.ToString()",
        };
    }

    /// <summary>A bound operand rendered as a scaled native-integer value.</summary>
    private NumX AsNum(BoundOperand op) => op switch
    {
        BoundNumericLiteral n => UnscaledLit(n.Text),
        BoundFieldOperand f => FieldNum(f.Place),
        BoundComputedOperand c => Render(c.Expr),
        BoundStringLiteral => new NumX(LoudValue("long", "alphanumeric literal in a numeric context"), 0),
        BoundOperandError e => new NumX(LoudValue("long", e.Feature), 0),
        _ => new NumX(LoudValue("long", $"bound operand '{op.GetType().Name}'"), 0),
    };

    // ════════════════════════════ Numeric expressions (scale-tracked) ═════════════════════════════════════

    /// <summary>A rendered numeric expression: a C# <c>long</c>-valued expression holding the UNSCALED value, plus
    /// its fractional <see cref="Scale"/> (the implied decimal position). The pair lets the backend align scales.</summary>
    private readonly record struct NumX(string Expr, int Scale);

    /// <summary>The division working scale (the receiving item's scale), set before rendering an RHS.</summary>
    private int _targetScale;

    private static int ScaleOf(Place p) => p.Item.Pic?.Scale ?? 0;

    /// <summary>Render a bound numeric expression as a scaled long.</summary>
    private NumX Render(BoundExpr e) => e switch
    {
        BoundNumLiteral l => UnscaledLit(l.Text),
        BoundNumRef r => FieldNum(r.Place),
        BoundBinary b => Combine(Render(b.Left), b.Op.ToString(), Render(b.Right)),
        BoundNegate n => Negate(Render(n.Operand)),
        BoundPower p => new NumX($"(long)System.Math.Pow((double)({Real(Render(p.Base))}), (double)({Real(Render(p.Exp))}))", 0),
        BoundExprError err => new NumX(LoudValue("long", err.Feature), 0),
        _ => new NumX(LoudValue("long", $"bound expression '{e.GetType().Name}'"), 0),
    };

    /// <summary>The scaled value of a data item place (its unscaled <c>long</c> value + its scale). A float item is
    /// truncated to <c>long</c> for now (mixed float/fixed arithmetic is a later slice).</summary>
    private static NumX FieldNum(Place p) =>
        p.Item.Pic!.IsFloat ? new NumX($"(long){p.Read()}", 0) : new NumX(p.Read(), p.Item.Pic.Scale);

    /// <summary>Left-fold a list of scaled values with <c>+</c> (the addends of an ADD / minuends of a SUBTRACT).</summary>
    private NumX Fold(IReadOnlyList<BoundExpr> xs)
    {
        if (xs.Count == 0) return new NumX("0L", 0);
        NumX acc = Render(xs[0]);
        for (int i = 1; i < xs.Count; i++) acc = Combine(acc, "+", Render(xs[i]));
        return acc;
    }

    /// <summary>Combine two scaled values with a COBOL operator, tracking the result scale (ISO §8.8.1).</summary>
    private NumX Combine(NumX a, string op, NumX b) => op switch
    {
        "+" or "-" => CombineAdditive(a, op, b),
        "*" => new NumX($"({a.Expr} * {b.Expr})", a.Scale + b.Scale),     // multiplication: scales add (exact)
        "/" => new NumX(                                                  // division: quotient at the working scale
            $"CobolNum.Divide({a.Expr}, {a.Scale}, {b.Expr}, {b.Scale}, {DivScale(a, b)}, CobolRounding.Truncation)",
            DivScale(a, b)),
        _ => a,
    };

    private static NumX CombineAdditive(NumX a, string op, NumX b)
    {
        int s = Math.Max(a.Scale, b.Scale);
        return new NumX($"({Align(a, s)} {op} {Align(b, s)})", s);
    }

    private int DivScale(NumX a, NumX b) => Math.Max(_targetScale, Math.Max(a.Scale, b.Scale));

    /// <summary>Rescale a value's unscaled long up to <paramref name="toScale"/> (widening only here → exact).</summary>
    private static string Align(NumX x, int toScale) =>
        toScale == x.Scale ? x.Expr : $"CobolNum.Rescale({x.Expr}, {x.Scale}, {toScale}, CobolRounding.Truncation)";

    private static NumX Negate(NumX x) => new($"(-{x.Expr})", x.Scale);

    private static string Real(NumX x) => x.Scale == 0 ? $"(double){x.Expr}" : $"({x.Expr} / {Pow10D(x.Scale)})";

    private static string Pow10D(int n) { double r = 1; for (int i = 0; i < n; i++) r *= 10; return $"{r}d"; }

    /// <summary>Render a numeric literal as a scaled <c>long</c>: its digits as the unscaled value, its fractional
    /// digit count as the scale (e.g. <c>"3.5"</c> → <c>(35L, 1)</c>, <c>"-12"</c> → <c>(-12L, 0)</c>).</summary>
    private static NumX UnscaledLit(string text)
    {
        string t = text.Trim().TrimStart('+');
        int dot = t.IndexOf('.');
        if (dot < 0) return new NumX($"{t}L", 0);
        int scale = t.Length - dot - 1;
        return new NumX($"{t.Remove(dot, 1)}L", scale);
    }

    // ════════════════════════════ Loud-failure + literal helpers ══════════════════════════════════════════

    /// <summary>A C# statement that fails loud at run time for an unsupported construct (COBOLNET_DESIGN §1.4).</summary>
    private static string LoudStmt(string feature) => $"NotImplemented.Run({CsStringLiteral(feature)});";

    /// <summary>A C# expression (typed <paramref name="csType"/>) that fails loud at run time when reached.</summary>
    private static string LoudValue(string csType, string feature) =>
        $"NotImplemented.Value<{csType}>({CsStringLiteral(feature)})";

    /// <summary>Decode a COBOL <c>STRINGLIT</c> (<c>"…"</c> with doubled <c>""</c>) to its character value.</summary>
    private static string DecodeCobolString(string raw) =>
        raw.Length >= 2 && raw[0] == '"' && raw[^1] == '"' ? raw[1..^1].Replace("\"\"", "\"") : raw;

    /// <summary>Render a .NET string as a safely-escaped C# string literal.</summary>
    private static string CsStringLiteral(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
