// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using Antlr4.Runtime.Tree;
using CobolNet.Binding;
using CobolSharp.Compiler.Generated;
using Microsoft.CodeAnalysis.CSharp;

namespace CobolNet.CodeGen;

using Core = CobolParserCore;

/// <summary>
/// Translates a COBOL parse tree into typed-native C# source. The heart of COBOL.NET: COBOL data is .NET data
/// (native fields, no byte substrate) and COBOL verbs are operations on those typed values, calling the clean
/// <c>CobolNum</c>/<c>CobolString</c> runtime substrates for COBOL-correct semantics.
/// </summary>
/// <remarks>
/// <para><b>Status — G2 data model + <c>Place</c>:</b> WORKING-STORAGE elementary items (alphanumeric→<c>string</c>,
/// numeric→native unscaled <c>long</c> — never <c>decimal</c>) AND group items (→ nested <c>record struct</c>) with
/// composed VALUE init (incl. figurative constants); every operand resolves through
/// <see cref="ReferenceResolver"/>→<see cref="Place"/> (unqualified + OF/IN-qualified). Verbs: <c>DISPLAY</c>,
/// <c>MOVE</c>, <c>ADD</c>/<c>SUBTRACT</c>/<c>MULTIPLY</c>/<c>DIVIDE</c>/<c>COMPUTE</c>, <c>IF</c>, inline
/// <c>PERFORM</c>, <c>STOP RUN</c>/<c>GOBACK</c>. OCCURS tables + subscripts + ref-mod (G2-1b), level-88 (G2c),
/// signed-DISPLAY overpunch (G2d), the formal bound tree + emitter decomposition (G2-2), and the PC dispatcher (G4)
/// follow. An unsupported construct emits a LOUD <c>NotImplemented.Run/Value</c> guard (throws at run time —
/// COBOLNET_DESIGN §1.4), never a silent no-op.</para>
/// </remarks>
public sealed class CSharpEmitter
{
    private DataBinder _data = new();
    private ReferenceResolver _refs = new(new DataBinder());

    /// <summary>Emit C# source for the first program unit in <paramref name="tree"/>.</summary>
    public string Emit(Core.CompilationUnitContext tree)
    {
        Core.ProgramUnitContext? program = tree.compilationGroup().SelectMany(g => g.programUnit()).FirstOrDefault();

        _data = new DataBinder();
        if (program is not null) _data.Bind(program);
        _refs = new ReferenceResolver(_data);

        var w = new CodeWriter();
        w.Line("// <auto-generated>");
        w.Line("//   Generated by COBOL.NET — do not edit. A COBOL program compiled to typed-native C#.");
        w.Line("// </auto-generated>");
        w.Line("#nullable enable");
        w.Line("using CobolNet.Runtime;          // CobolNum / CobolString typed-native runtime substrates");
        w.Line();

        using (w.Block("internal static class Program"))
        {
            EmitWorkingStorage(w);

            if (program?.procedureDivision() is { } pd)
            {
                CollectParagraphs(pd);
                w.Line();
                // Main runs the paragraphs in source order — COBOL "fall-through" is a sequential call chain;
                // STOP RUN / GOBACK throw StopRun to unwind the whole chain (ISO §14.9.43).
                using (w.Block("private static void Main()"))
                {
                    using (w.Block("try"))
                        foreach (var p in _paras) w.Line($"{p.Method}();");
                    w.Line("catch (StopRun) { }");
                }
                // One method per paragraph.
                foreach (var p in _paras)
                {
                    w.Line();
                    using (w.Block($"private static void {p.Method}()"))
                        EmitParagraphBody(p.Ctx, w);
                }
            }
            else
                using (w.Block("private static void Main()")) { }
        }

        return w.ToString();
    }

    // ── DATA DIVISION → fields ───────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emit the DATA DIVISION as typed-native C#: a nested <c>record struct</c> type per group, a static numeric
    /// <c>NumProfile</c> per numeric leaf, and one static field per top-level (01/77) item (a group initialized
    /// with a composed object-initializer, an elementary item with its VALUE-or-default). A COBOL record IS a .NET
    /// record (COBOLNET_DESIGN §3.2) — no byte substrate, no flattening.
    /// </summary>
    private void EmitWorkingStorage(CodeWriter w)
    {
        foreach (var root in _data.Roots) EmitStructTypeDecls(root, w);   // 1. record struct types (every group)
        foreach (var root in _data.Roots) EmitProfiles(root, w);          // 2. numeric profiles (every leaf, flat)
        foreach (var root in _data.Roots)                                 // 3. one static field per 01/77
        {
            if (root.IsGroup)
                w.Line($"private static {root.StructName} {root.CsName} = {ComposedInit(root)};   // {root.CobolName}");
            else if (root.IsElementary)
            {
                string comment = root.CobolName is { } n ? $"   // {n} {root.Pic!.Category}" : "";
                w.Line($"private static {root.Pic!.ClrType} {root.CsName} = {InitializerFor(root)};{comment}");
            }
        }
    }

    /// <summary>Emit a <c>record struct</c> type for a group item and (recursively) its nested group members.</summary>
    private static void EmitStructTypeDecls(DataItem item, CodeWriter w)
    {
        if (!item.IsGroup) return;
        foreach (var child in item.Children) EmitStructTypeDecls(child, w);   // nested types first (any order is fine)
        using (w.Block($"private record struct {item.StructName}"))
            foreach (var child in item.Children)
                if (child.IsGroup || child.IsElementary)
                    w.Line($"public {child.ClrType} {child.CsName};   // {child.CobolName ?? "FILLER"}");
    }

    /// <summary>Emit a static <c>NumProfile</c> field for every numeric (fixed-point) elementary item, recursively.</summary>
    private static void EmitProfiles(DataItem item, CodeWriter w)
    {
        if (item.IsElementary && item.Pic is { Category: PicCategory.Numeric, IsFloat: false })
            w.Line($"private static readonly NumProfile {item.ProfileName} = {item.Pic.ProfileInitializer};");
        foreach (var child in item.Children) EmitProfiles(child, w);
    }

    /// <summary>A composed C# object-initializer for a group: every member set to its VALUE-or-default (so no
    /// member is left at <c>default</c> — a <c>string</c> member would otherwise be null).</summary>
    private static string ComposedInit(DataItem group)
    {
        var parts = group.Children
            .Where(c => c.IsGroup || c.IsElementary)
            .Select(c => $"{c.CsName} = {(c.IsGroup ? ComposedInit(c) : InitializerFor(c))}");
        return $"new {group.StructName} {{ {string.Join(", ", parts)} }}";
    }

    /// <summary>The C# name of an item's runtime numeric profile field.</summary>
    private static string ProfileName(DataItem item) => item.ProfileName;

    /// <summary>The C# initializer expression for an elementary item, from its VALUE clause or the COBOL default.</summary>
    private static string InitializerFor(DataItem item)
    {
        var pic = item.Pic!;
        if (item.RawValue is not { } raw)
            return pic.DefaultInitializer;

        // Figurative constants (ZERO / SPACE / HIGH-VALUE / LOW-VALUE / QUOTE / NULL) fill the item to its width
        // (ISO §8.3.1.2): ZERO → 0 for a numeric item, "0…0" for an alphanumeric one; the others are alphanumeric.
        if (FigurativeInitializer(raw, pic) is { } fig)
            return fig;

        return pic.Category switch
        {
            PicCategory.Alphanumeric or PicCategory.NumericEdited =>
                $"CobolString.Store({CsStringLiteral(DecodeCobolString(raw))}, {pic.Length})",
            // A numeric VALUE is stored unscaled at the item's own scale (e.g. VALUE 3.5 in a PIC 9V99 → 350L).
            PicCategory.Numeric when pic.IsFloat => RawValueAsFloat(raw, pic),
            PicCategory.Numeric => UnscaledAtScale(raw, pic.Scale),
            _ => pic.DefaultInitializer,
        };
    }

    /// <summary>
    /// If <paramref name="raw"/> is a figurative constant, the C# initializer for it given the receiver's category
    /// and width; otherwise <see langword="null"/>. ZERO maps to the numeric zero or a zero-filled string; SPACE,
    /// HIGH-VALUE (U+00FF), LOW-VALUE (U+0000), QUOTE, and NULL are width-filled strings (COBOLNET_DESIGN §14.9).
    /// </summary>
    private static string? FigurativeInitializer(string raw, PicInfo pic)
    {
        // The fill character for the alphanumeric form; a numeric receiver ignores it and uses its zero default.
        string? fillChar = raw.ToUpperInvariant() switch
        {
            "ZERO" or "ZEROS" or "ZEROES" => "'0'",
            "SPACE" or "SPACES" => "' '",
            "HIGH-VALUE" or "HIGH-VALUES" => "'\\u00ff'",
            "LOW-VALUE" or "LOW-VALUES" or "NULL" or "NULLS" => "'\\u0000'",
            "QUOTE" or "QUOTES" => "'\\\"'",
            _ => null,
        };
        if (fillChar is null) return null;
        return pic.Category is PicCategory.Numeric ? pic.DefaultInitializer : $"new string({fillChar}, {pic.Length})";
    }

    /// <summary>A numeric VALUE literal as a C# float/double literal for a COMP-1/COMP-2 item.</summary>
    private static string RawValueAsFloat(string raw, PicInfo pic) =>
        pic.Usage == Usage.Float ? $"{raw.Trim().TrimStart('+')}f" : $"{raw.Trim().TrimStart('+')}d";

    /// <summary>
    /// Render a numeric literal as a C# <c>long</c> holding its UNSCALED value at <paramref name="scale"/> fractional
    /// digits — e.g. <c>"3.5"</c> at scale 2 → <c>350L</c>, <c>"12"</c> at scale 0 → <c>12L</c>. The literal's own
    /// fractional digits are scaled up or truncated to match.
    /// </summary>
    private static string UnscaledAtScale(string raw, int scale)
    {
        string t = raw.Trim().TrimStart('+');
        bool neg = t.StartsWith('-');
        if (neg) t = t[1..];
        int dot = t.IndexOf('.');
        string intPart = dot < 0 ? t : t[..dot];
        string fracPart = dot < 0 ? "" : t[(dot + 1)..];
        if (fracPart.Length < scale) fracPart = fracPart.PadRight(scale, '0');
        else if (fracPart.Length > scale) fracPart = fracPart[..scale];     // truncate excess fraction
        string digits = (intPart + fracPart).TrimStart('0');
        return $"{(neg ? "-" : "")}{(digits.Length == 0 ? "0" : digits)}L";
    }

    // ── PROCEDURE DIVISION → paragraph methods + control flow ────────────────────────────────────────────

    /// <summary>A bound paragraph: its COBOL name, the C# method name it emits as, and its parse subtree.</summary>
    private sealed record Para(string CobolName, string Method, Core.ParagraphDefinitionContext Ctx);

    private List<Para> _paras = [];
    private readonly Dictionary<string, int> _paraIndex = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Collect every paragraph (flattening sections) in source order, assigning each a unique C# method name.</summary>
    private void CollectParagraphs(Core.ProcedureDivisionContext pd)
    {
        _paras = [];
        _paraIndex.Clear();
        var used = new HashSet<string>(StringComparer.Ordinal);

        void Add(Core.ParagraphDefinitionContext p)
        {
            string name = p.paragraphName().GetText();
            string baseName = "P_" + name.Replace('-', '_').Replace('.', '_');
            string method = baseName;
            for (int n = 2; !used.Add(method); n++) method = $"{baseName}_{n}";
            _paraIndex.TryAdd(name, _paras.Count);   // first definition wins for PERFORM resolution
            _paras.Add(new Para(name, method, p));
        }

        foreach (var unit in pd.procedureUnit())
        {
            if (unit.paragraphDefinition() is { } para) Add(para);
            else if (unit.sectionDefinition() is { } section)
                foreach (var p in section.paragraphDefinition()) Add(p);
        }
    }

    /// <summary>The C# method name a PERFORM target (COBOL paragraph name) resolves to.</summary>
    private string MethodOf(string cobolName) =>
        _paraIndex.TryGetValue(cobolName, out int i) ? _paras[i].Method : "P_" + cobolName.Replace('-', '_');

    private void EmitParagraphBody(Core.ParagraphDefinitionContext para, CodeWriter w)
    {
        foreach (var sentence in para.sentence())
            foreach (var statement in sentence.statement())
                EmitStatement(statement, w);
    }

    /// <summary>Emit one statement. Unsupported verbs emit a TODO marker (compile, don't crash).</summary>
    private void EmitStatement(Core.StatementContext s, CodeWriter w)
    {
        switch (s)
        {
            case var _ when s.displayStatement() is { } d: EmitDisplay(d, w); break;
            case var _ when s.moveStatement() is { } m: EmitMove(m, w); break;
            case var _ when s.addStatement() is { } a: EmitAdd(a, w); break;
            case var _ when s.subtractStatement() is { } sub: EmitSubtract(sub, w); break;
            case var _ when s.multiplyStatement() is { } mul: EmitMultiply(mul, w); break;
            case var _ when s.divideStatement() is { } div: EmitDivide(div, w); break;
            case var _ when s.computeStatement() is { } c: EmitCompute(c, w); break;
            case var _ when s.ifStatement() is { } iff: EmitIf(iff, w); break;
            case var _ when s.performStatement() is { } p: EmitPerform(p, w); break;
            case var _ when s.stopStatement() is not null || s.gobackStatement() is not null:
                w.Line("throw new StopRun();"); break;   // unwind the paragraph call-chain (ISO §14.9.43)
            default: w.Line(LoudStmt($"statement '{FirstToken(s)}'")); break;   // loud failure (COBOLNET_DESIGN §1.4)
        }
    }

    /// <summary>Emit a <c>DISPLAY</c>: concatenate operand display images and write the line.</summary>
    private void EmitDisplay(Core.DisplayStatementContext display, CodeWriter w)
    {
        var parts = new List<string>();
        foreach (IParseTree child in Children(display))
        {
            switch (child)
            {
                case Core.LiteralContext lit: parts.Add(RenderLiteralAsString(lit)); break;
                case Core.DataReferenceContext dref: parts.Add(ReadAsString(dref)); break;
            }
        }

        string image = parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
        bool noAdvancing = display.displayNoAdvancing() is not null;
        w.Line(noAdvancing ? $"System.Console.Write({image});" : $"System.Console.WriteLine({image});");
    }

    /// <summary>Emit a <c>MOVE</c> (single sending operand → one or more targets). CORR is a later slice.</summary>
    private void EmitMove(Core.MoveStatementContext move, CodeWriter w)
    {
        var send = move.moveSendingOperand();
        var phrase = move.moveReceivingPhrase();
        if (send is null || phrase?.dataReferenceList() is not { } targets)
        {
            w.Line(LoudStmt("MOVE CORRESPONDING / unsupported MOVE form"));
            return;
        }

        foreach (var target in targets.dataReference())
            if (Resolve(target) is not { } p)
                w.Line(LoudStmt($"MOVE to unsupported target '{target.GetText()}'"));
            else if (p.Item.Pic is null)
                w.Line(LoudStmt($"MOVE to group item '{p.Item.CobolName}' (whole-group MOVE is G6)"));
            else
                w.Line(p.Write(ConvertToTarget(send, p.Item)));
    }

    /// <summary>Emit <c>ADD … TO …</c> and <c>ADD … GIVING …</c> (numeric). ROUNDED / SIZE ERROR / CORR: later.</summary>
    private void EmitAdd(Core.AddStatementContext add, CodeWriter w)
    {
        if (add.addOperandList() is not { } operands) { w.Line(LoudStmt("ADD CORRESPONDING")); return; }
        var addends = operands.addOperand().Select(Num).ToList();
        NumX sum = Fold(addends, "+");

        if (add.addGivingPhrase() is { } giving)
            foreach (var dref in DataRefs(giving))
                EmitArithInto(dref, sum, w);                                         // GIVING t = a + b + …
        else if (add.addToPhrase() is { } to)
            foreach (var dref in DataRefs(to))
                if (Resolve(dref) is { } p)
                    EmitArithAssign(p, Combine(FieldNum(p), "+", sum), w);           // TO t = t + (a + b + …)
                else w.Line(LoudStmt($"ADD into unsupported target '{dref.GetText()}'"));
    }

    /// <summary>Resolve an arithmetic target reference and store <paramref name="value"/>, failing loud if unresolved.</summary>
    private void EmitArithInto(Core.DataReferenceContext target, NumX value, CodeWriter w)
    {
        if (Resolve(target) is { } p) EmitArithAssign(p, value, w);
        else w.Line(LoudStmt($"arithmetic into unsupported target '{target.GetText()}'"));
    }

    /// <summary>Emit <c>SUBTRACT … FROM …</c> and <c>SUBTRACT … FROM … GIVING …</c> (numeric).</summary>
    private void EmitSubtract(Core.SubtractStatementContext sub, CodeWriter w)
    {
        if (sub.subtractOperandList() is not { } operands) { w.Line(LoudStmt("SUBTRACT CORRESPONDING")); return; }
        NumX minuends = Fold(operands.subtractOperand().Select(Num).ToList(), "+");

        if (sub.subtractGivingPhrase() is { } giving && sub.subtractFromPhrase()?.subtractFromOperand() is { } from)
        {
            NumX fromVal = Num(from);
            foreach (var dref in DataRefs(giving))
                EmitArithInto(dref, Combine(fromVal, "-", minuends), w);             // GIVING t = from − (a+b+…)
        }
        else if (sub.subtractFromPhrase()?.subtractFromOperand() is { } fromTargets)
            foreach (var dref in DataRefs(fromTargets))
                if (Resolve(dref) is { } p)
                    EmitArithAssign(p, Combine(FieldNum(p), "-", minuends), w);      // FROM t = t − (a+b+…)
                else w.Line(LoudStmt($"SUBTRACT into unsupported target '{dref.GetText()}'"));
    }

    /// <summary>
    /// Emit an <c>IF condition THEN … [ELSE …] END-IF</c> as a C# <c>if/else</c>. THEN- and ELSE-branch statement
    /// blocks are split at the <c>ELSE</c> token. Conditions translate via <see cref="RenderCondition"/>.
    /// </summary>
    private void EmitIf(Core.IfStatementContext iff, CodeWriter w)
    {
        // Split the combined statementBlock list into THEN / ELSE at the ELSE keyword.
        var thenBlocks = new List<Core.StatementBlockContext>();
        var elseBlocks = new List<Core.StatementBlockContext>();
        bool seenElse = false;
        foreach (var child in Children(iff))
        {
            if (child is ITerminalNode t && t.Symbol.Type == CobolLexer.ELSE) seenElse = true;
            else if (child is Core.StatementBlockContext sb) (seenElse ? elseBlocks : thenBlocks).Add(sb);
        }

        using (w.Block($"if ({RenderCondition(iff.condition())})"))
            EmitBlocks(thenBlocks, w);
        if (elseBlocks.Count > 0)
            using (w.Block("else"))
                EmitBlocks(elseBlocks, w);
    }

    /// <summary>Emit the statements of a set of statement blocks.</summary>
    private void EmitBlocks(IEnumerable<Core.StatementBlockContext> blocks, CodeWriter w)
    {
        foreach (var block in blocks)
            foreach (var statement in block.statement())
                EmitStatement(statement, w);
    }

    // ── PERFORM ──────────────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emit a <c>PERFORM</c>: out-of-line (a paragraph or <c>THRU</c> range, optionally looped <c>n TIMES</c> /
    /// <c>UNTIL</c>) or inline (a statement block looped). The body is "execute these paragraphs in order then
    /// return" — a sequential call chain, matching COBOL's perform-range semantics for well-structured ranges.
    /// (PERFORM VARYING and ranges that contain GO TO are later slices — the latter needs the PC dispatcher.)
    /// </summary>
    private void EmitPerform(Core.PerformStatementContext p, CodeWriter w)
    {
        var names = p.procedureName();
        if (names.Length == 0)
        {
            EmitInlinePerform(p, w);   // PERFORM [options] <statements> END-PERFORM
            return;
        }

        // The body: call the target paragraph, or every paragraph in the THRU range, in order.
        var body = new List<string>();
        if ((p.THRU() is not null || p.THROUGH() is not null) && names.Length >= 2
            && _paraIndex.TryGetValue(names[0].GetText(), out int i)
            && _paraIndex.TryGetValue(names[1].GetText(), out int j) && i <= j)
            for (int k = i; k <= j; k++) body.Add($"{_paras[k].Method}();");
        else
            body.Add($"{MethodOf(names[0].GetText())}();");

        if (p.performTimes() is { } times) EmitLoop($"for (long _i = 0; _i < {TimesCount(times)}; _i++)", body, w);
        else if (p.performUntil() is { } until) EmitUntil(until, body, w);
        else if (p.performVarying() is not null) w.Line(LoudStmt("PERFORM VARYING (out-of-line)"));
        else foreach (var line in body) w.Line(line);   // simple PERFORM / PERFORM THRU
    }

    /// <summary>Emit an inline <c>PERFORM … END-PERFORM</c> (optionally with TIMES/UNTIL options).</summary>
    private void EmitInlinePerform(Core.PerformStatementContext p, CodeWriter w)
    {
        void EmitBody(CodeWriter cw) => EmitBlocks(p.statementBlock(), cw);
        var opts = p.performOptions();
        if (opts.Length == 0) { using (w.Block("do")) EmitBody(w); w.Line("while (false);"); return; }   // once

        var opt = opts[0];
        if (opt.performTimes() is { } t)
            using (w.Block($"for (long _i = 0; _i < {TimesCount(t)}; _i++)")) EmitBody(w);
        else if (opt.performUntil() is { } u)
        {
            string cond = RenderCondition(u.condition());
            if (u.AFTER() is not null) { using (w.Block("do")) EmitBody(w); w.Line($"while (!({cond}));"); }
            else using (w.Block($"while (!({cond}))")) EmitBody(w);
        }
        else w.Line(LoudStmt("inline PERFORM VARYING"));
    }

    /// <summary>Emit a loop header wrapping a body of pre-rendered statement lines.</summary>
    private static void EmitLoop(string header, IReadOnlyList<string> body, CodeWriter w)
    {
        using (w.Block(header))
            foreach (var line in body) w.Line(line);
    }

    /// <summary>Emit a <c>PERFORM … UNTIL</c> loop (TEST BEFORE → while; TEST AFTER → do/while).</summary>
    private void EmitUntil(Core.PerformUntilContext until, IReadOnlyList<string> body, CodeWriter w)
    {
        string cond = RenderCondition(until.condition());
        if (until.AFTER() is not null)
        {
            using (w.Block("do")) foreach (var line in body) w.Line(line);
            w.Line($"while (!({cond}));");
        }
        else EmitLoop($"while (!({cond}))", body, w);
    }

    /// <summary>The C# count expression for a <c>PERFORM … n TIMES</c> phrase (literal or data item).</summary>
    private string TimesCount(Core.PerformTimesContext t) =>
        t.integerLiteral() is { } lit ? lit.GetText()
        : t.dataReference() is { } d && Resolve(d) is { } p ? p.Read() : "1";

    // ── Condition translation (IF / relational / logical) ────────────────────────────────────────────────

    /// <summary>
    /// Translate a COBOL condition to a C# boolean expression. Handles relational comparisons (numeric and
    /// alphanumeric) combined with <c>AND</c>/<c>OR</c>/<c>NOT</c>/<c>XOR</c> and parentheses. Class/sign/condition-
    /// name and the abbreviated relational forms emit a conservative <c>false</c> fallback (refined in later slices).
    /// </summary>
    private string RenderCondition(IParseTree node)
    {
        switch (node)
        {
            case Core.ConditionContext c:
                return RenderCondition(c.GetChild(0));

            case Core.LogicalOrExpressionContext orExpr when orExpr.abbreviatedAndChain().Length == 0:
                return string.Join(" || ", orExpr.logicalXorExpression().Select(RenderCondition));

            case Core.LogicalXorExpressionContext xorExpr:
                return string.Join(" ^ ", xorExpr.logicalAndExpression().Select(RenderCondition));

            case Core.LogicalAndExpressionContext andExpr when andExpr.abbreviatedRelation().Length == 0:
                return string.Join(" && ", andExpr.unaryLogicalExpression().Select(RenderCondition));

            case Core.UnaryLogicalExpressionContext u:
                return u.NOT() is not null
                    ? $"!({RenderCondition(u.primaryCondition())})"
                    : RenderCondition(u.primaryCondition());

            case Core.PrimaryConditionContext p:
                if (p.comparisonExpression() is { } cmp) return RenderComparison(cmp);
                if (p.condition() is { } inner) return $"({RenderCondition(inner)})";
                return "false /* TODO(COBOL.NET): boolean-literal condition */";

            default:
                return "false /* TODO(COBOL.NET): unsupported condition form */";
        }
    }

    /// <summary>Translate a relational comparison expression to a C# boolean expression.</summary>
    private string RenderComparison(Core.ComparisonExpressionContext cmp)
    {
        var operands = cmp.comparisonOperand();
        if (cmp.comparisonOperator() is not { } opCtx || operands.Length < 2)
            return "false /* TODO(COBOL.NET): class/sign/condition-name comparison */";

        string csOp = MapOperator(opCtx.GetText());
        bool isString = IsStringOperand(operands[0]) || IsStringOperand(operands[1]);
        if (isString)
            return $"CobolString.Compare({OperandAsString(operands[0])}, {OperandAsString(operands[1])}) {csOp} 0";
        // Numeric comparison: render both as scaled longs, align to the common scale, then compare (ISO §8.8.4.1.1).
        NumX l = OperandNum(operands[0]), r = OperandNum(operands[1]);
        int s = Math.Max(l.Scale, r.Scale);
        return $"{Align(l, s)} {csOp} {Align(r, s)}";
    }

    /// <summary>A comparison operand rendered as a scaled native-integer value.</summary>
    private NumX OperandNum(Core.ComparisonOperandContext operand) =>
        operand.valueOperand()?.arithmeticExpression() is { } expr ? Num(expr) : new NumX("0L", 0);

    /// <summary>
    /// Map a COBOL comparison operator (any symbolic or word form, possibly negated) to a C# operator. The symbolic
    /// <c>&lt;&gt;</c> is "not equal" directly; otherwise a base relation is determined ignoring <c>NOT</c>, then a
    /// leading <c>NOT</c> inverts it (so word form <c>NOT EQUAL</c> → <c>!=</c>, <c>NOT GREATER</c> → <c>&lt;=</c>).
    /// </summary>
    private static string MapOperator(string raw)
    {
        string t = raw.ToUpperInvariant().Replace("IS", "").Replace("THAN", "").Replace("TO", "");
        if (t.Contains("<>")) return "!=";
        bool not = t.Contains("NOT");
        bool orEqual = t.Contains(">=") || t.Contains("<=") || t.Contains("OREQUAL");
        string baseOp =
            t.Contains('>') || t.Contains("GREATER") ? (orEqual ? ">=" : ">")
            : t.Contains('<') || t.Contains("LESS") ? (orEqual ? "<=" : "<")
            : "==";  // EQUAL / =
        if (!not) return baseOp;
        return baseOp switch { ">" => "<=", ">=" => "<", "<" => ">=", "<=" => ">", "==" => "!=", _ => "==" };
    }

    /// <summary>True if a comparison operand should be compared as text (a string literal or an alphanumeric item).</summary>
    private bool IsStringOperand(Core.ComparisonOperandContext operand)
    {
        var vo = operand.valueOperand();
        if (vo?.nonNumericLiteral() is not null) return true;
        if (vo?.arithmeticExpression() is { } expr && SoleDataRef(expr) is { } dref)
            return Resolve(dref)?.Item.Pic?.Category is PicCategory.Alphanumeric or PicCategory.NumericEdited;
        return false;
    }

    /// <summary>Render a comparison operand as a C# string (display image).</summary>
    private string OperandAsString(Core.ComparisonOperandContext operand)
    {
        var vo = operand.valueOperand();
        if (vo?.nonNumericLiteral()?.STRINGLIT() is { } s) return CsStringLiteral(DecodeCobolString(s.GetText()));
        if (vo?.arithmeticExpression() is { } expr && SoleDataRef(expr) is { } dref) return ReadAsString(dref);
        return "\"\"";
    }

    /// <summary>If an arithmetic expression is exactly one data reference (no operators), return it; else null.</summary>
    private static Core.DataReferenceContext? SoleDataRef(Core.ArithmeticExpressionContext expr)
    {
        IParseTree n = expr;
        while (n is not Core.PrimaryExpressionContext)
        {
            if (n.ChildCount != 1) return null;
            n = n.GetChild(0);
        }
        return ((Core.PrimaryExpressionContext)n).dataReference();
    }

    /// <summary>
    /// Emit <c>COMPUTE t [t2 …] = arithmetic-expression</c>. The RHS is rendered as a scale-tracked native-integer
    /// expression and stored into each target via <c>CobolNum.Store</c> (which applies the receiver's scale,
    /// truncation, and — later — ROUNDED / SIZE ERROR). The receiver's scale is set as the division working scale.
    /// </summary>
    private void EmitCompute(Core.ComputeStatementContext compute, CodeWriter w)
    {
        if (compute.arithmeticExpression() is not { } expr) { w.Line(LoudStmt("COMPUTE without an expression")); return; }
        foreach (var store in compute.computeStore())
            if (store.dataReference() is not { } target) { }
            else if (Resolve(target) is { Item.Pic.Scale: var s } p)
            {
                _targetScale = s;                       // division inside the RHS computes at the receiver's scale
                EmitArithAssign(p, Num(expr), w);
            }
            else w.Line(LoudStmt($"COMPUTE into unsupported target '{target.GetText()}'"));
    }

    /// <summary>Emit <c>MULTIPLY a BY b</c> (→ <c>b = b × a</c>) and <c>MULTIPLY a BY b GIVING c…</c> (→ <c>c = a × b</c>).</summary>
    private void EmitMultiply(Core.MultiplyStatementContext mul, CodeWriter w)
    {
        if (mul.multiplyOperand() is not { } aCtx) { w.Line(LoudStmt("MULTIPLY form")); return; }
        NumX a = Num(aCtx);
        var byOps = mul.multiplyByOperand();

        if (mul.multiplyGivingPhrase() is { } giving && byOps.Length > 0)
        {
            NumX b = Num(byOps[0]);
            foreach (var target in DataRefs(giving)) AssignScaled(target, Combine(a, "*", b), w);
        }
        else
            foreach (var byOp in byOps)
                if (DataRefs(byOp).FirstOrDefault() is { } target && Resolve(target) is { } p)
                    AssignScaled(target, Combine(FieldNum(p), "*", a), w);
    }

    /// <summary>Emit <c>DIVIDE a INTO b [GIVING c]</c> (b ÷ a) and <c>DIVIDE a BY b GIVING c</c> (a ÷ b). REMAINDER: later.</summary>
    private void EmitDivide(Core.DivideStatementContext div, CodeWriter w)
    {
        if (div.divideRemainderPhrase() is not null) { w.Line(LoudStmt("DIVIDE … REMAINDER")); return; }
        if (div.divideOperand() is not { } aCtx) { w.Line(LoudStmt("DIVIDE form")); return; }
        NumX a = Num(aCtx);

        if (div.divideIntoPhrase() is { } into)
        {
            NumX b = Num(into.divideIntoOperand());                  // dividend; divisor = a
            if (div.divideGivingPhrase() is { } giving)
                foreach (var target in DataRefs(giving)) AssignDivide(target, b, a, w);
            else
                foreach (var target in DataRefs(into))
                    if (Resolve(target) is { } p) AssignDivide(target, FieldNum(p), a, w);
        }
        else if (div.divideByPhrase() is { } byPhrase && div.divideGivingPhrase() is { } giving)
        {
            NumX b = Num(byPhrase.divideOperand());                  // DIVIDE a BY b GIVING c → c = a ÷ b
            foreach (var target in DataRefs(giving)) AssignDivide(target, a, b, w);
        }
    }

    /// <summary>Assign <c>dividend ÷ divisor</c> into a target, computing the quotient at the target's scale.</summary>
    private void AssignDivide(Core.DataReferenceContext target, NumX dividend, NumX divisor, CodeWriter w)
    {
        _targetScale = Resolve(target)?.Item.Pic?.Scale ?? 0;
        AssignScaled(target, Combine(dividend, "/", divisor), w);
    }

    /// <summary>Store a scaled native-integer value into a numeric target via the runtime engine.</summary>
    private void AssignScaled(Core.DataReferenceContext target, NumX value, CodeWriter w) =>
        EmitArithInto(target, value, w);

    // ── Scale-tracked native-integer numeric expressions ─────────────────────────────────────────────────

    /// <summary>A rendered numeric expression: a C# <c>long</c>-valued expression holding the UNSCALED value, plus
    /// its fractional <see cref="Scale"/> (the implied decimal position). The pair lets the emitter align scales.</summary>
    private readonly record struct NumX(string Expr, int Scale);

    /// <summary>The division working scale (the receiving item's scale), set before rendering an RHS.</summary>
    private int _targetScale;

    /// <summary>Store a numeric <see cref="NumX"/> result into a numeric target place via <c>CobolNum.Store</c>.</summary>
    private void EmitArithAssign(Place target, NumX value, CodeWriter w)
    {
        if (target.Item.Pic is not { Category: PicCategory.Numeric, IsFloat: false })
        {
            w.Line(LoudStmt($"arithmetic into a non-fixed-point target '{target.Item.CobolName ?? target.Read()}'"));
            return;
        }
        w.Line(target.Write($"CobolNum.Store({value.Expr}, {value.Scale}, {target.Item.ProfileName})"));
    }

    /// <summary>Render any numeric node (expression, operand wrapper, literal, or data reference) as a scaled long.</summary>
    private NumX Num(IParseTree node) => node switch
    {
        Core.ArithmeticExpressionContext a => Num(a.GetChild(0)),
        Core.AdditiveExpressionContext or Core.MultiplicativeExpressionContext => NumChain(node),
        Core.PowerExpressionContext p => NumPower(p),
        Core.UnaryExpressionContext u => u.primaryExpression() is { } pr ? Num(pr)
            : u.addOp().GetText() == "-" ? Negate(Num(u.unaryExpression())) : Num(u.unaryExpression()),
        Core.PrimaryExpressionContext pe => NumPrimary(pe),
        Core.LiteralContext l => UnscaledLit(l.GetText()),
        Core.DataReferenceContext d => Resolve(d) is { } p ? FieldNum(p) : new NumX(LoudValue("long", $"numeric reference '{d.GetText()}'"), 0),
        _ => FindOperandNum(node),   // operand wrappers (addOperand, multiplyByOperand, …): descend to the leaf
    };

    /// <summary>Fold an additive/multiplicative chain left-to-right, combining operands by their interleaved operators.</summary>
    private NumX NumChain(IParseTree node)
    {
        NumX? acc = null;
        string op = "+";
        foreach (var child in Children(node))
        {
            if (child is Core.AddOpContext or Core.MulOpContext) op = child.GetText();
            else { NumX x = Num(child); acc = acc is { } a ? Combine(a, op, x) : x; }
        }
        return acc ?? new NumX("0L", 0);
    }

    /// <summary>Render <c>a ** b ** …</c> left-folded via <c>Math.Pow</c> (scale 0 — exponentiation result is integral here).</summary>
    private NumX NumPower(Core.PowerExpressionContext p)
    {
        var bases = p.unaryExpression();
        NumX acc = Num(bases[0]);
        for (int i = 1; i < bases.Length; i++)
        {
            NumX e = Num(bases[i]);
            acc = new NumX($"(long)System.Math.Pow((double)({Real(acc)}), (double)({Real(e)}))", 0);
        }
        return acc;
    }

    /// <summary>Render a primary numeric expression.</summary>
    private NumX NumPrimary(Core.PrimaryExpressionContext pe)
    {
        if (pe.numericLiteral() is { } num) return UnscaledLit(num.GetText());
        if (pe.ZERO_ARITH() is not null) return new NumX("0L", 0);
        if (pe.dataReference() is { } dref) return Resolve(dref) is { } p ? FieldNum(p) : new NumX(LoudValue("long", $"numeric reference '{dref.GetText()}'"), 0);
        if (pe.arithmeticExpression() is { } paren) return Num(paren);
        return new NumX(LoudValue("long", "function-call operand"), 0);
    }

    /// <summary>The scaled value of a data item place (its unscaled <c>long</c> value + its scale). A float item is
    /// truncated to <c>long</c> for now (mixed float/fixed arithmetic is a later slice).</summary>
    private static NumX FieldNum(Place p) =>
        p.Item.Pic!.IsFloat ? new NumX($"(long){p.Read()}", 0) : new NumX(p.Read(), p.Item.Pic.Scale);

    /// <summary>Left-fold a list of scaled values with a single operator (e.g. the addends of an ADD).</summary>
    private NumX Fold(IReadOnlyList<NumX> xs, string op)
    {
        if (xs.Count == 0) return new NumX("0L", 0);
        NumX acc = xs[0];
        for (int i = 1; i < xs.Count; i++) acc = Combine(acc, op, xs[i]);
        return acc;
    }

    /// <summary>Combine two scaled values with a COBOL operator, tracking the result scale (ISO §8.8.1).</summary>
    private NumX Combine(NumX a, string op, NumX b) => op switch
    {
        "+" or "-" => CombineAdditive(a, op, b),
        "*" => new NumX($"({a.Expr} * {b.Expr})", a.Scale + b.Scale),     // multiplication: scales add (exact)
        "/" => new NumX(                                                  // division: quotient at the working scale
            $"CobolNum.Divide({a.Expr}, {a.Scale}, {b.Expr}, {b.Scale}, {DivScale(a, b)}, CobolRounding.Truncation)",
            DivScale(a, b)),
        _ => a,
    };

    /// <summary>Add/subtract two scaled values, first aligning both to the larger scale (a widening, hence exact).</summary>
    private static NumX CombineAdditive(NumX a, string op, NumX b)
    {
        int s = Math.Max(a.Scale, b.Scale);
        return new NumX($"({Align(a, s)} {op} {Align(b, s)})", s);
    }

    /// <summary>The fractional scale a division produces: the receiver's scale, but at least the operands' scales.</summary>
    private int DivScale(NumX a, NumX b) => Math.Max(_targetScale, Math.Max(a.Scale, b.Scale));

    /// <summary>Rescale a value's unscaled long up to <paramref name="toScale"/> (widening only here → exact).</summary>
    private static string Align(NumX x, int toScale) =>
        toScale == x.Scale ? x.Expr : $"CobolNum.Rescale({x.Expr}, {x.Scale}, {toScale}, CobolRounding.Truncation)";

    /// <summary>Negate a scaled value.</summary>
    private static NumX Negate(NumX x) => new($"(-{x.Expr})", x.Scale);

    /// <summary>The real (double) value of a scaled long — for the floating-point <c>**</c> path.</summary>
    private static string Real(NumX x) => x.Scale == 0 ? $"(double){x.Expr}" : $"({x.Expr} / {Pow10D(x.Scale)})";

    private static string Pow10D(int n) { double r = 1; for (int i = 0; i < n; i++) r *= 10; return $"{r}d"; }

    /// <summary>Descend an operand-wrapper node to its numeric literal or data reference.</summary>
    private NumX FindOperandNum(IParseTree node)
    {
        for (int i = 0; i < node.ChildCount; i++)
        {
            var c = node.GetChild(i);
            if (c is Core.LiteralContext l) return UnscaledLit(l.GetText());
            if (c is Core.DataReferenceContext d) return Resolve(d) is { } p ? FieldNum(p) : new NumX(LoudValue("long", $"numeric reference '{d.GetText()}'"), 0);
            NumX inner = FindOperandNum(c);
            if (inner.Expr != "0L") return inner;
        }
        return new NumX("0L", 0);
    }

    /// <summary>Render a numeric literal as a scaled <c>long</c>: its digits as the unscaled value, its fractional
    /// digit count as the scale (e.g. <c>"3.5"</c> → <c>(35L, 1)</c>, <c>"-12"</c> → <c>(-12L, 0)</c>).</summary>
    private static NumX UnscaledLit(string text)
    {
        string t = text.Trim().TrimStart('+');
        int dot = t.IndexOf('.');
        if (dot < 0) return new NumX($"{t}L", 0);
        int scale = t.Length - dot - 1;
        return new NumX($"{t.Remove(dot, 1)}L", scale);
    }

    /// <summary>Convert a MOVE sending operand to the C# expression assigned into <paramref name="target"/>.</summary>
    private string ConvertToTarget(Core.MoveSendingOperandContext send, DataItem target)
    {
        var pic = target.Pic!;
        switch (pic.Category)
        {
            case PicCategory.Alphanumeric or PicCategory.NumericEdited:
                // Alphanumeric MOVE: a numeric source moves its DISPLAY image (digits); a string source its value.
                return $"CobolString.Store({SendAsString(send)}, {pic.Length})";
            case PicCategory.Numeric:
                // Numeric MOVE: rescale the source (at its own scale) into the receiver's PICTURE+USAGE.
                NumX src = SendAsNumber(send);
                return $"CobolNum.Store({src.Expr}, {src.Scale}, {ProfileName(target)})";
            default:
                return "default";
        }
    }

    /// <summary>A MOVE sending operand rendered as a C# <see cref="string"/> (its display image).</summary>
    private string SendAsString(Core.MoveSendingOperandContext send)
    {
        if (send.literal() is { } lit) return RenderLiteralAsString(lit);
        if (send.dataReference() is { } dref) return ReadAsString(dref);
        return "\"\"";
    }

    /// <summary>A MOVE sending operand rendered as a scaled native-integer value.</summary>
    private NumX SendAsNumber(Core.MoveSendingOperandContext send)
    {
        if (send.literal() is { } lit) return UnscaledLit(lit.GetText());
        if (send.dataReference() is { } dref) return Resolve(dref) is { } p ? FieldNum(p) : new NumX(LoudValue("long", $"numeric reference '{dref.GetText()}'"), 0);
        return new NumX("0L", 0);
    }

    /// <summary>Read a data reference as a C# <see cref="string"/> (its DISPLAY image).</summary>
    private string ReadAsString(Core.DataReferenceContext dref)
    {
        if (Resolve(dref) is not { } p) return LoudValue("string", $"reference '{dref.GetText()}'");
        if (p.Item.IsGroup) return LoudValue("string", $"DISPLAY of group item '{p.Item.CobolName}' (whole-group image is G6)");
        return p.Item.Pic switch
        {
            // Fixed-point numeric → its DISPLAY image (unscaled digits, zero-padded, no point) via the profile.
            { Category: PicCategory.Numeric, IsFloat: false } => $"CobolNum.FormatDisplay({p.Read()}, {p.Item.ProfileName})",
            { Category: PicCategory.Numeric } => $"{p.Read()}.ToString()",           // COMP-1/2 float — refine later
            { Category: PicCategory.Alphanumeric or PicCategory.NumericEdited } => p.Read(),
            _ => $"{p.Read()}.ToString()",
        };
    }

    /// <summary>Render a COBOL literal as a C# <see cref="string"/> expression (its display image).</summary>
    private static string RenderLiteralAsString(Core.LiteralContext lit) =>
        lit.nonNumericLiteral()?.STRINGLIT() is { } s
            ? CsStringLiteral(DecodeCobolString(s.GetText()))
            : CsStringLiteral(lit.GetText());

    // ── Reference resolution + helpers ───────────────────────────────────────────────────────────────────

    /// <summary>Resolve a data reference (unqualified or OF/IN-qualified) to its typed <see cref="Place"/>, or
    /// <see langword="null"/> when it cannot be resolved in this slice (unknown name, subscript, or ref-mod).</summary>
    private Place? Resolve(Core.DataReferenceContext dref) => _refs.Resolve(dref);

    /// <summary>A C# statement that fails loud at run time for an unsupported construct (COBOLNET_DESIGN §1.4).</summary>
    private static string LoudStmt(string feature) => $"NotImplemented.Run({CsStringLiteral(feature)});";

    /// <summary>A C# expression (typed <paramref name="csType"/>) that fails loud at run time when reached.</summary>
    private static string LoudValue(string csType, string feature) =>
        $"NotImplemented.Value<{csType}>({CsStringLiteral(feature)})";

    /// <summary>All <see cref="Core.DataReferenceContext"/> descendants of a node, in source order.</summary>
    private static IEnumerable<Core.DataReferenceContext> DataRefs(IParseTree node)
    {
        for (int i = 0; i < node.ChildCount; i++)
        {
            var child = node.GetChild(i);
            if (child is Core.DataReferenceContext dref) yield return dref;
            else foreach (var inner in DataRefs(child)) yield return inner;
        }
    }

    /// <summary>Decode a COBOL <c>STRINGLIT</c> (<c>"…"</c> with doubled <c>""</c>) to its character value.</summary>
    private static string DecodeCobolString(string raw) =>
        raw.Length >= 2 && raw[0] == '"' && raw[^1] == '"' ? raw[1..^1].Replace("\"\"", "\"") : raw;

    /// <summary>Render a .NET string as a safely-escaped C# string literal.</summary>
    private static string CsStringLiteral(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static IEnumerable<IParseTree> Children(IParseTree node)
    {
        for (int i = 0; i < node.ChildCount; i++) yield return node.GetChild(i);
    }

    private static string FirstToken(IParseTree node) =>
        node.ChildCount > 0 ? node.GetChild(0).GetText() : node.GetText();
}
