// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using CobolNet.Binding;
using CobolNet.Binding.Bound;
using CobolNet.CodeGen.Emit;
using CobolSharp.Compiler.Generated;

namespace CobolNet.CodeGen;

using Core = CobolParserCore;
using static CobolNet.CodeGen.Emit.EmitText;

/// <summary>
/// The Roslyn (C#) backend orchestrator: binds a program unit to a <see cref="BoundProgram"/> and renders it to
/// typed-native C# source, delegating to the decomposed emitters/renderers over a shared <see cref="EmissionContext"/>
/// (COBOLNET_DESIGN §17 §2.2): <see cref="FieldEmitter"/> (DATA DIVISION), <see cref="NumericRenderer"/> (arithmetic),
/// <see cref="ConditionRenderer"/> (conditions), and <see cref="OperandText"/> (DISPLAY images). It consumes only the
/// bound tree for the PROCEDURE DIVISION — it never walks the parse tree (that is the binder's job) — and an
/// unsupported construct surfaces as a bound error node and emits a LOUD <c>NotImplemented</c> guard (§1.4).
/// </summary>
/// <remarks><b>Status — G2:</b> groups→record structs, OCCURS→arrays, qualified/subscripted refs, figurative +
/// signed DISPLAY, level-88. Control flow is a sequential paragraph call-chain (the G4 PC dispatcher replaces it).</remarks>
public sealed class CSharpEmitter
{
    private EmissionContext _ctx = null!;
    private NumericRenderer _num = null!;
    private ConditionRenderer _cond = null!;

    /// <summary>Emit C# source for the first program unit in <paramref name="tree"/>.</summary>
    public string Emit(Core.CompilationUnitContext tree)
    {
        Core.ProgramUnitContext? program = tree.compilationGroup().SelectMany(g => g.programUnit()).FirstOrDefault();

        var data = new DataBinder();
        if (program is not null) data.Bind(program);
        var refs = new ReferenceResolver(data);
        BoundProgram bound = program is not null ? new StatementBinder(data, refs).Bind(program) : new BoundProgram([]);

        var w = new CodeWriter();
        _ctx = new EmissionContext(w, data);
        _num = new NumericRenderer(_ctx);
        _cond = new ConditionRenderer(_num);

        w.Line("// <auto-generated>");
        w.Line("//   Generated by COBOL.NET — do not edit. A COBOL program compiled to typed-native C#.");
        w.Line("// </auto-generated>");
        w.Line("#nullable enable");
        w.Line("using CobolNet.Runtime;          // CobolNum / CobolString typed-native runtime substrates");
        w.Line();

        using (w.Block("internal static class Program"))
        {
            new FieldEmitter(_ctx).Emit();

            if (bound.Paragraphs.Count > 0)
            {
                w.Line();
                // Main runs the paragraphs in source order — COBOL "fall-through" is a sequential call chain;
                // STOP RUN / GOBACK throw StopRun to unwind the whole chain (ISO §14.9.43). The PC dispatcher (G4)
                // replaces this with pc-indexed control flow.
                using (w.Block("private static void Main()"))
                {
                    using (w.Block("try"))
                        foreach (var p in bound.Paragraphs) w.Line($"{p.Method}();");
                    w.Line("catch (StopRun) { }");
                }
                foreach (var p in bound.Paragraphs)
                {
                    w.Line();
                    using (w.Block($"private static void {p.Method}()"))
                        foreach (var st in p.Statements) EmitStatement(st);
                }
            }
            else
                using (w.Block("private static void Main()")) { }
        }

        return w.ToString();
    }

    // ── Statement dispatch ─────────────────────────────────────────────────────────────────────────────────

    private void EmitStatement(BoundStatement s)
    {
        var w = _ctx.Writer;
        switch (s)
        {
            case BoundStop: w.Line("throw new StopRun();"); break;
            case BoundUnsupported u: w.Line(LoudStmt(u.Feature)); break;
            case BoundDisplay d: EmitDisplay(d); break;
            case BoundMove m: EmitMove(m); break;
            case BoundAddTo a: EmitInPlace(a.Targets, "+", _num.Fold(a.Addends)); break;
            case BoundAddGiving a: EmitGiving(a.Targets, _num.Fold(a.Addends)); break;
            case BoundSubtractFrom a: EmitInPlace(a.Targets, "-", _num.Fold(a.Minuends)); break;
            case BoundSubtractGiving a: EmitGiving(a.Targets, _num.Combine(_num.Render(a.From), "-", _num.Fold(a.Minuends))); break;
            case BoundMultiplyBy a: EmitInPlace(a.Targets, "*", _num.Render(a.A)); break;
            case BoundMultiplyGiving a: EmitGiving(a.Targets, _num.Combine(_num.Render(a.A), "*", _num.Render(a.B))); break;
            case BoundDivideInto a: EmitDivide(a.Targets, null, _num.Render(a.Divisor)); break;
            case BoundDivideGiving a: EmitDivide(a.Targets, _num.Render(a.Dividend), _num.Render(a.Divisor)); break;
            case BoundCompute c: foreach (var t in c.Targets) { _ctx.TargetScale = ScaleOf(t); StoreArith(t, _num.Render(c.Rhs)); } break;
            case BoundIf iff: EmitIf(iff); break;
            case BoundInlinePerform p: EmitInlinePerform(p); break;
            case BoundOutOfLinePerform p: EmitOutOfLinePerform(p); break;
            case BoundSetConditions set: EmitSet(set); break;
            default: w.Line(LoudStmt($"bound statement '{s.GetType().Name}'")); break;
        }
    }

    private void EmitDisplay(BoundDisplay d)
    {
        var parts = d.Operands.Select(OperandText.AsString).ToList();
        string image = parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
        _ctx.Writer.Line(d.NoAdvancing ? $"System.Console.Write({image});" : $"System.Console.WriteLine({image});");
    }

    private void EmitMove(BoundMove m)
    {
        foreach (var target in m.Targets)
            if (target.Item.Pic is null)
                _ctx.Writer.Line(LoudStmt($"MOVE to group item '{target.Item.CobolName}' (whole-group MOVE is G6)"));
            else
                _ctx.Writer.Line(target.Write(ConvertSource(m.Source, target.Item)));
    }

    /// <summary>The C# expression a MOVE source converts to when stored into <paramref name="target"/>.</summary>
    private string ConvertSource(BoundOperand source, DataItem target)
    {
        var pic = target.Pic!;
        switch (pic.Category)
        {
            case PicCategory.Alphanumeric or PicCategory.NumericEdited:
                return $"CobolString.Store({OperandText.AsString(source)}, {pic.Length})";
            case PicCategory.Numeric:
                NumX n = _num.AsNum(source);
                return $"CobolNum.Store({n.Expr}, {n.Scale}, {target.ProfileName})";
            default:
                return "default";
        }
    }

    // ── Arithmetic ──────────────────────────────────────────────────────────────────────────────────────

    private void EmitInPlace(IReadOnlyList<Place> targets, string op, NumX value)
    {
        foreach (var t in targets) StoreArith(t, _num.Combine(NumericRenderer.FieldNum(t), op, value));
    }

    private void EmitGiving(IReadOnlyList<Place> targets, NumX value)
    {
        foreach (var t in targets) StoreArith(t, value);
    }

    private void EmitDivide(IReadOnlyList<Place> targets, NumX? dividend, NumX divisor)
    {
        foreach (var t in targets)
        {
            _ctx.TargetScale = ScaleOf(t);                   // the quotient is computed at the receiver's scale
            NumX num = dividend ?? NumericRenderer.FieldNum(t);   // DIVIDE … INTO with no GIVING divides the target itself
            StoreArith(t, _num.Combine(num, "/", divisor));
        }
    }

    /// <summary>Store an arithmetic result into a numeric target place via <c>CobolNum.Store</c>.</summary>
    private void StoreArith(Place target, NumX value)
    {
        if (target.Item.Pic is not { Category: PicCategory.Numeric, IsFloat: false })
        {
            _ctx.Writer.Line(LoudStmt($"arithmetic into a non-fixed-point target '{target.Item.CobolName ?? target.Read()}'"));
            return;
        }
        _ctx.Writer.Line(target.Write($"CobolNum.Store({value.Expr}, {value.Scale}, {target.Item.ProfileName})"));
    }

    private static int ScaleOf(Place p) => p.Item.Pic?.Scale ?? 0;

    // ── IF / PERFORM / SET ─────────────────────────────────────────────────────────────────────────────

    private void EmitIf(BoundIf iff)
    {
        var w = _ctx.Writer;
        using (w.Block($"if ({_cond.Render(iff.Condition)})"))
            foreach (var st in iff.Then) EmitStatement(st);
        if (iff.Else.Count > 0)
            using (w.Block("else"))
                foreach (var st in iff.Else) EmitStatement(st);
    }

    private void EmitInlinePerform(BoundInlinePerform p) => EmitPerform(p.Control, () => { foreach (var st in p.Body) EmitStatement(st); }, inline: true);

    private void EmitOutOfLinePerform(BoundOutOfLinePerform p) =>
        EmitPerform(p.Control, () => { foreach (var m in p.TargetMethods) _ctx.Writer.Line($"{m}();"); }, inline: false);

    private void EmitPerform(BoundPerformControl control, Action body, bool inline)
    {
        var w = _ctx.Writer;
        switch (control)
        {
            case PerformTimes t:
                using (w.Block($"for (long _i = 0; _i < {CountExpr(t.Count)}; _i++)")) body();
                break;
            case PerformUntil u when u.TestAfter:
                using (w.Block("do")) body();
                w.Line($"while (!({_cond.Render(u.Until)}));");
                break;
            case PerformUntil u:
                using (w.Block($"while (!({_cond.Render(u.Until)}))")) body();
                break;
            default:   // PerformOnce — an inline body runs once via do/while(false); an out-of-line call is unconditional
                if (inline) { using (w.Block("do")) body(); w.Line("while (false);"); }
                else body();
                break;
        }
    }

    private static string CountExpr(BoundOperand count) => count switch
    {
        BoundNumericLiteral n => n.Text,
        BoundFieldOperand f => f.Place.Read(),
        BoundOperandError e => LoudValue("long", e.Feature),
        _ => "1",
    };

    private void EmitSet(BoundSetConditions set)
    {
        foreach (var (parent, cond) in set.Sets)
        {
            var (low, _) = cond.Values[0];   // SET TO TRUE stores the first VALUE (ISO §14.9.39 Format 5)
            string rhs = parent.Item.Pic?.Category switch
            {
                PicCategory.Alphanumeric or PicCategory.NumericEdited =>
                    $"CobolString.Store({CsLiteral(DecodeCobolString(low))}, {parent.Item.Pic.Length})",
                PicCategory.Numeric =>
                    $"CobolNum.Store({UnscaledAtScale(low, parent.Item.Pic.Scale)}, {parent.Item.Pic.Scale}, {parent.Item.ProfileName})",
                _ => LoudValue("string", $"SET condition '{cond.Name}' over a group parent"),
            };
            _ctx.Writer.Line(parent.Write(rhs));
        }
    }
}
