// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cobol.Net.Compiler.SourceGen;

/// <summary>
/// Emits the ONE exhaustive dispatch over the compiler's bound tree (rearchitecture EXEC STEP A / PHASE-07 Step 6).
/// For every abstract root marked <c>[BoundNode]</c> (e.g. <c>BoundStatement</c>), it emits a typed
/// <c>I{Root}Visitor&lt;out T&gt;</c> with one <c>Visit</c> per sealed leaf, plus a <c>BoundVisitor.Accept&lt;T&gt;</c>
/// extension that dispatches each leaf to its <c>Visit</c>. The exhaustiveness guarantee: a consumer that implements
/// the interface must supply a <c>Visit</c> for every leaf, so adding a bound-node leaf regenerates the interface and
/// makes every implementing consumer fail to compile until it handles the new node — the "forgotten arm ships as a
/// runtime throw" class of bug becomes impossible.
///
/// The leaf set is discovered through the Roslyn SEMANTIC MODEL (<see cref="INamedTypeSymbol.BaseType"/>), never a
/// text/regex scan — a base-less helper record cannot be mistaken for a leaf, and the generated file cannot drift
/// from the source (it is regenerated from the live type graph on every build). This is the canonical C#→C# tooling;
/// it replaces the ~205 hand-maintained <c>case Bound…</c> arms once the consumers are converted (Step 6b→6f).
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BoundVisitorGenerator : IIncrementalGenerator
{
    private const string AttrNamespace = "CobolNet.Binding.Bound";
    private const string AttrSimpleName = "BoundNodeAttribute";
    private const string AttrFullName = AttrNamespace + "." + AttrSimpleName;

    private const string AttributeSource =
        "// <auto-generated/>\n" +
        "#nullable enable\n" +
        "namespace " + AttrNamespace + "\n" +
        "{\n" +
        "    /// <summary>Marks an abstract bound-tree root so BoundVisitorGenerator emits an exhaustive\n" +
        "    /// I{Root}Visitor&lt;T&gt; + Accept&lt;T&gt; over every sealed leaf deriving from it.</summary>\n" +
        "    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]\n" +
        "    internal sealed class " + AttrSimpleName + " : global::System.Attribute { }\n" +
        "}\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The marker attribute lives in the compilation via post-init so the compiler can annotate its roots.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("BoundNodeAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // Regenerate from the whole compilation: the bound hierarchy is ~120 types, so a full-model pass every build
        // is negligible and keeps the discovery semantic (correctness over micro-incrementality).
        var source = context.CompilationProvider.Select(static (compilation, _) => BuildSource(compilation));
        context.RegisterSourceOutput(source, static (spc, text) =>
            spc.AddSource("BoundVisitors.g.cs", SourceText.From(text, Encoding.UTF8)));
    }

    /// <summary>Walk the compiler assembly's own types, group the non-abstract leaves under each [BoundNode] root
    /// (by base-chain), and render the interfaces + Accept dispatch.</summary>
    private static string BuildSource(Compilation compilation)
    {
        var attr = compilation.GetTypeByMetadataName(AttrFullName);

        var allTypes = new List<INamedTypeSymbol>();
        CollectTypes(compilation.Assembly.GlobalNamespace, allTypes);

        // Roots: abstract classes carrying [BoundNode], in declaration-stable name order.
        var roots = allTypes
            .Where(t => t.IsAbstract && HasBoundNodeAttribute(t, attr))
            .OrderBy(t => t.Name, System.StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/> Emitted by Cobol.Net.Compiler.SourceGen.BoundVisitorGenerator — do not edit.\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System;\n");
        sb.Append("using System.Collections.Generic;\n");
        sb.Append("using System.Linq;\n\n");
        sb.Append("namespace ").Append(AttrNamespace).Append(";\n");

        if (roots.Count == 0)
        {
            sb.Append("\n// No [BoundNode] roots found — nothing to generate.\n");
            return sb.ToString();
        }

        // Per root: the sealed (non-abstract) descendants, name-ordered, are the visitable leaves.
        var leavesByRoot = new Dictionary<INamedTypeSymbol, List<INamedTypeSymbol>>(SymbolEqualityComparer.Default);
        foreach (var root in roots)
        {
            leavesByRoot[root] = allTypes
                .Where(t => !t.IsAbstract && !SymbolEqualityComparer.Default.Equals(t, root) && DerivesFrom(t, root))
                .OrderBy(t => t.Name, System.StringComparer.Ordinal)
                .ToList();
        }

        foreach (var root in roots)
        {
            var leaves = leavesByRoot[root];
            sb.Append("\n// ── ").Append(root.Name).Append(" (").Append(leaves.Count).Append(" leaves) ──\n");
            sb.Append("public interface I").Append(root.Name).Append("Visitor<out T>\n{\n");
            foreach (var leaf in leaves)
                sb.Append("    T Visit(").Append(leaf.Name).Append(" n);\n");
            sb.Append("}\n");
        }

        sb.Append("\n/// <summary>The exhaustive Accept dispatch. The default arm exists only to satisfy CS8509 (C# does\n");
        sb.Append("/// not prove closed-hierarchy exhaustiveness for class types) and is unreachable — the switch is\n");
        sb.Append("/// regenerated from the live leaf set every build.</summary>\n");
        sb.Append("public static class BoundVisitor\n{\n");
        foreach (var root in roots)
        {
            var leaves = leavesByRoot[root];
            sb.Append("    public static T Accept<T>(this ").Append(root.Name)
              .Append(" n, I").Append(root.Name).Append("Visitor<T> v) => n switch\n    {\n");
            foreach (var leaf in leaves)
                sb.Append("        ").Append(leaf.Name).Append(" x => v.Visit(x),\n");
            sb.Append("        _ => throw new InvalidOperationException($\"unhandled ").Append(root.Name)
              .Append(" node {n.GetType().Name}\"),\n    };\n\n");
        }
        sb.Append("}\n");

        // The statement-tree child enumeration (PHASE-07 Step 6g) — the ONE drift-proof source of "what statements
        // nest inside statement X", so the walker consumers recurse over it instead of hand-listing children.
        EmitStatementChildren(sb, roots, allTypes);
        return sb.ToString();
    }

    /// <summary>Emit <c>BoundStatementTree.StatementChildren(this BoundStatement) : IEnumerable&lt;BoundStatement&gt;</c>
    /// — the direct child statements of each leaf, discovered by reading EVERY property through the semantic model
    /// (completeness by construction). Handles direct statement/statement-list props and single-depth "statement-bearing"
    /// helper records (e.g. SizeErrorPhrase, KeyedInvalidKey, BoundSearchWhen, BoundEvaluateWhen).</summary>
    private static void EmitStatementChildren(StringBuilder sb, List<INamedTypeSymbol> roots, List<INamedTypeSymbol> allTypes)
    {
        var boundStatement = roots.FirstOrDefault(r => r.Name == "BoundStatement");
        if (boundStatement is null) return;
        var leaves = allTypes
            .Where(t => !t.IsAbstract && DerivesFrom(t, boundStatement))
            .OrderBy(t => t.Name, System.StringComparer.Ordinal)
            .ToList();

        sb.Append("\n/// <summary>The direct child statements of a bound statement — the ONE drift-proof source of the\n");
        sb.Append("/// statement-tree shape (PHASE-07 Step 6g), read from every property via the semantic model so it\n");
        sb.Append("/// cannot forget a nested phrase. Walker consumers recurse over this instead of hand-listing children.</summary>\n");
        sb.Append("public static class BoundStatementTree\n{\n");
        sb.Append("    private static IEnumerable<BoundStatement> One(BoundStatement? s) => s is null ? Array.Empty<BoundStatement>() : new[] { s };\n");
        sb.Append("    private static IEnumerable<BoundStatement> Nz(IEnumerable<BoundStatement>? xs) => xs ?? Array.Empty<BoundStatement>();\n\n");
        sb.Append("    /// <summary>The statements directly nested one level inside <paramref name=\"n\"/> (phrase bodies,\n");
        sb.Append("    /// IF/EVALUATE arms, loop/SEARCH bodies) — NOT transitively; a walker recurses.</summary>\n");
        sb.Append("    public static IEnumerable<BoundStatement> StatementChildren(this BoundStatement n) => n switch\n    {\n");
        foreach (var leaf in leaves)
        {
            var sources = new List<string>();
            foreach (var p in InstanceProps(leaf))
                CollectSources("x." + p.Name, p.Type, boundStatement, roots, sources, 0);
            if (sources.Count == 0) continue;   // no nested statements → falls through to the `_ => []` arm
            sb.Append("        ").Append(leaf.Name).Append(" x => ").Append(Combine(sources)).Append(",\n");
        }
        sb.Append("        _ => Array.Empty<BoundStatement>(),\n    };\n}\n");
    }

    /// <summary>Accumulate the C# source expressions (each <c>IEnumerable&lt;BoundStatement&gt;</c>) that a property
    /// <paramref name="access"/> of type <paramref name="type"/> contributes: a bound statement, a statement list, or
    /// the statement props of a single-depth helper record / list of helper records.</summary>
    private static void CollectSources(string access, ITypeSymbol type, INamedTypeSymbol boundStatement,
        List<INamedTypeSymbol> roots, List<string> sources, int depth)
    {
        if (depth > 4) return;   // the real tree is depth ≤ 1; this is only a runaway guard
        if (IsStatementLike(type, boundStatement)) { sources.Add($"One({access})"); return; }
        if (TryListElement(type, out var elem))
        {
            if (IsStatementLike(elem, boundStatement)) { sources.Add($"Nz({access})"); return; }
            if (IsStatementBearing(elem, boundStatement, roots))
            {
                var inner = new List<string>();
                string v = "__e" + depth;
                foreach (var q in InstanceProps((INamedTypeSymbol)elem))
                    CollectSources(v + "." + q.Name, q.Type, boundStatement, roots, inner, depth + 1);
                if (inner.Count > 0)
                    sources.Add($"({access} ?? Array.Empty<{elem.ToDisplayString()}>()).SelectMany({v} => {Combine(inner)})");
            }
            return;
        }
        if (IsStatementBearing(type, boundStatement, roots))
            foreach (var q in InstanceProps((INamedTypeSymbol)type))
                CollectSources($"{access}?.{q.Name}", q.Type, boundStatement, roots, sources, depth + 1);
    }

    private static string Combine(List<string> sources) =>
        sources.Count == 1 ? sources[0] : string.Join(".Concat(", sources) + new string(')', sources.Count - 1);

    /// <summary>A non-Bound helper record (in our assembly) that transitively holds statements — e.g. SizeErrorPhrase.
    /// Bound roots (Expr/Condition/Operand/…) are pruned (those hierarchies never contain statements); a visited set
    /// bounds the walk through cyclic data-model types (DataItem.Children → DataItem).</summary>
    private static bool IsStatementBearing(ITypeSymbol type, INamedTypeSymbol boundStatement, List<INamedTypeSymbol> roots) =>
        IsStatementBearing(type, boundStatement, roots, new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default));

    private static bool IsStatementBearing(ITypeSymbol type, INamedTypeSymbol boundStatement,
        List<INamedTypeSymbol> roots, HashSet<INamedTypeSymbol> visited)
    {
        if (type is not INamedTypeSymbol nt || !visited.Add(nt)) return false;
        if (roots.Any(r => IsDerivedFrom(nt, r) || SymbolEqualityComparer.Default.Equals(nt, r))) return false;
        if (!SymbolEqualityComparer.Default.Equals(nt.ContainingAssembly, boundStatement.ContainingAssembly)) return false;
        foreach (var p in InstanceProps(nt))
        {
            if (IsStatementLike(p.Type, boundStatement)) return true;
            if (TryListElement(p.Type, out var e))
            {
                if (IsStatementLike(e, boundStatement) || IsStatementBearing(e, boundStatement, roots, visited)) return true;
            }
            else if (IsStatementBearing(p.Type, boundStatement, roots, visited)) return true;
        }
        return false;
    }

    /// <summary><paramref name="t"/> IS a bound statement (the root itself — the shape of every statement-list
    /// element/child prop) or a leaf deriving from it.</summary>
    private static bool IsStatementLike(ITypeSymbol t, INamedTypeSymbol boundStatement) =>
        SymbolEqualityComparer.Default.Equals(t, boundStatement) || IsDerivedFrom(t, boundStatement);

    private static IEnumerable<IPropertySymbol> InstanceProps(INamedTypeSymbol t) =>
        t.GetMembers().OfType<IPropertySymbol>()
         .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public && p.Parameters.Length == 0);

    private static bool TryListElement(ITypeSymbol type, out ITypeSymbol element)
    {
        if (type is INamedTypeSymbol { IsGenericType: true } g
            && g.OriginalDefinition.ToDisplayString() is "System.Collections.Generic.IReadOnlyList<T>"
                or "System.Collections.Generic.IEnumerable<T>" or "System.Collections.Generic.IReadOnlyCollection<T>")
        {
            element = g.TypeArguments[0];
            return true;
        }
        element = null!;
        return false;
    }

    private static bool IsDerivedFrom(ITypeSymbol type, INamedTypeSymbol root)
    {
        for (var b = type.BaseType; b is not null; b = b.BaseType)
            if (SymbolEqualityComparer.Default.Equals(b, root))
                return true;
        return false;
    }

    private static void CollectTypes(INamespaceSymbol ns, List<INamedTypeSymbol> into)
    {
        foreach (var t in ns.GetTypeMembers())
            CollectNested(t, into);
        foreach (var child in ns.GetNamespaceMembers())
            CollectTypes(child, into);
    }

    private static void CollectNested(INamedTypeSymbol type, List<INamedTypeSymbol> into)
    {
        into.Add(type);
        foreach (var nested in type.GetTypeMembers())
            CollectNested(nested, into);
    }

    private static bool HasBoundNodeAttribute(INamedTypeSymbol type, INamedTypeSymbol? attr)
    {
        foreach (var a in type.GetAttributes())
        {
            if (attr is not null && SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr))
                return true;
            // Fallback (attr symbol not yet resolvable): match by full name.
            if (attr is null && a.AttributeClass?.ToDisplayString() == AttrFullName)
                return true;
        }
        return false;
    }

    private static bool DerivesFrom(INamedTypeSymbol type, INamedTypeSymbol root)
    {
        for (var b = type.BaseType; b is not null; b = b.BaseType)
            if (SymbolEqualityComparer.Default.Equals(b, root))
                return true;
        return false;
    }
}
