// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cobol.Net.Compiler.SourceGen;

/// <summary>
/// Emits the ONE exhaustive dispatch over the compiler's bound tree (rearchitecture EXEC STEP A / PHASE-07 Step 6).
/// For every abstract root marked <c>[BoundNode]</c> (e.g. <c>BoundStatement</c>), it emits a typed
/// <c>I{Root}Visitor&lt;out T&gt;</c> with one <c>Visit</c> per sealed leaf, plus a <c>BoundVisitor.Accept&lt;T&gt;</c>
/// extension that dispatches each leaf to its <c>Visit</c>. The exhaustiveness guarantee: a consumer that implements
/// the interface must supply a <c>Visit</c> for every leaf, so adding a bound-node leaf regenerates the interface and
/// makes every implementing consumer fail to compile until it handles the new node — the "forgotten arm ships as a
/// runtime throw" class of bug becomes impossible.
///
/// The leaf set is discovered through the Roslyn SEMANTIC MODEL (<see cref="INamedTypeSymbol.BaseType"/>), never a
/// text/regex scan — a base-less helper record cannot be mistaken for a leaf, and the generated file cannot drift
/// from the source (it is regenerated from the live type graph on every build). This is the canonical C#→C# tooling;
/// it replaces the ~205 hand-maintained <c>case Bound…</c> arms once the consumers are converted (Step 6b→6f).
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BoundVisitorGenerator : IIncrementalGenerator
{
    private const string AttrNamespace = "CobolNet.Binding.Bound";
    private const string AttrSimpleName = "BoundNodeAttribute";
    private const string AttrFullName = AttrNamespace + "." + AttrSimpleName;

    private const string AttributeSource =
        "// <auto-generated/>\n" +
        "#nullable enable\n" +
        "namespace " + AttrNamespace + "\n" +
        "{\n" +
        "    /// <summary>Marks an abstract bound-tree root so BoundVisitorGenerator emits an exhaustive\n" +
        "    /// I{Root}Visitor&lt;T&gt; + Accept&lt;T&gt; over every sealed leaf deriving from it.</summary>\n" +
        "    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]\n" +
        "    internal sealed class " + AttrSimpleName + " : global::System.Attribute { }\n" +
        "}\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The marker attribute lives in the compilation via post-init so the compiler can annotate its roots.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("BoundNodeAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // Regenerate from the whole compilation: the bound hierarchy is ~120 types, so a full-model pass every build
        // is negligible and keeps the discovery semantic (correctness over micro-incrementality).
        var source = context.CompilationProvider.Select(static (compilation, _) => BuildSource(compilation));
        context.RegisterSourceOutput(source, static (spc, text) =>
            spc.AddSource("BoundVisitors.g.cs", SourceText.From(text, Encoding.UTF8)));
    }

    /// <summary>Walk the compiler assembly's own types, group the non-abstract leaves under each [BoundNode] root
    /// (by base-chain), and render the interfaces + Accept dispatch.</summary>
    private static string BuildSource(Compilation compilation)
    {
        var attr = compilation.GetTypeByMetadataName(AttrFullName);

        var allTypes = new List<INamedTypeSymbol>();
        CollectTypes(compilation.Assembly.GlobalNamespace, allTypes);

        // Roots: abstract classes carrying [BoundNode], in declaration-stable name order.
        var roots = allTypes
            .Where(t => t.IsAbstract && HasBoundNodeAttribute(t, attr))
            .OrderBy(t => t.Name, System.StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/> Emitted by Cobol.Net.Compiler.SourceGen.BoundVisitorGenerator — do not edit.\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System;\n\n");
        sb.Append("namespace ").Append(AttrNamespace).Append(";\n");

        if (roots.Count == 0)
        {
            sb.Append("\n// No [BoundNode] roots found — nothing to generate.\n");
            return sb.ToString();
        }

        // Per root: the sealed (non-abstract) descendants, name-ordered, are the visitable leaves.
        var leavesByRoot = new Dictionary<INamedTypeSymbol, List<INamedTypeSymbol>>(SymbolEqualityComparer.Default);
        foreach (var root in roots)
        {
            leavesByRoot[root] = allTypes
                .Where(t => !t.IsAbstract && !SymbolEqualityComparer.Default.Equals(t, root) && DerivesFrom(t, root))
                .OrderBy(t => t.Name, System.StringComparer.Ordinal)
                .ToList();
        }

        foreach (var root in roots)
        {
            var leaves = leavesByRoot[root];
            sb.Append("\n// ── ").Append(root.Name).Append(" (").Append(leaves.Count).Append(" leaves) ──\n");
            sb.Append("public interface I").Append(root.Name).Append("Visitor<out T>\n{\n");
            foreach (var leaf in leaves)
                sb.Append("    T Visit(").Append(leaf.Name).Append(" n);\n");
            sb.Append("}\n");
        }

        sb.Append("\n/// <summary>The exhaustive Accept dispatch. The default arm exists only to satisfy CS8509 (C# does\n");
        sb.Append("/// not prove closed-hierarchy exhaustiveness for class types) and is unreachable — the switch is\n");
        sb.Append("/// regenerated from the live leaf set every build.</summary>\n");
        sb.Append("public static class BoundVisitor\n{\n");
        foreach (var root in roots)
        {
            var leaves = leavesByRoot[root];
            sb.Append("    public static T Accept<T>(this ").Append(root.Name)
              .Append(" n, I").Append(root.Name).Append("Visitor<T> v) => n switch\n    {\n");
            foreach (var leaf in leaves)
                sb.Append("        ").Append(leaf.Name).Append(" x => v.Visit(x),\n");
            sb.Append("        _ => throw new InvalidOperationException($\"unhandled ").Append(root.Name)
              .Append(" node {n.GetType().Name}\"),\n    };\n\n");
        }
        sb.Append("}\n");
        return sb.ToString();
    }

    private static void CollectTypes(INamespaceSymbol ns, List<INamedTypeSymbol> into)
    {
        foreach (var t in ns.GetTypeMembers())
            CollectNested(t, into);
        foreach (var child in ns.GetNamespaceMembers())
            CollectTypes(child, into);
    }

    private static void CollectNested(INamedTypeSymbol type, List<INamedTypeSymbol> into)
    {
        into.Add(type);
        foreach (var nested in type.GetTypeMembers())
            CollectNested(nested, into);
    }

    private static bool HasBoundNodeAttribute(INamedTypeSymbol type, INamedTypeSymbol? attr)
    {
        foreach (var a in type.GetAttributes())
        {
            if (attr is not null && SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr))
                return true;
            // Fallback (attr symbol not yet resolvable): match by full name.
            if (attr is null && a.AttributeClass?.ToDisplayString() == AttrFullName)
                return true;
        }
        return false;
    }

    private static bool DerivesFrom(INamedTypeSymbol type, INamedTypeSymbol root)
    {
        for (var b = type.BaseType; b is not null; b = b.BaseType)
            if (SymbolEqualityComparer.Default.Equals(b, root))
                return true;
        return false;
    }
}
