// <auto-generated>
// Generated by scripts/gen-constructs.ps1 from tests/version-matrix/constructs.json — DO NOT EDIT; re-run the script.
// tests/version-matrix/constructs.json is THE canonical version-matrix catalogue; ConstructRegistryDriftTests
// asserts this output equals it (a stale file is a CI failure, not a silent wrong build).
// </auto-generated>
namespace CobolNet.Editions;

/// <summary>Compile-checked constructs.json row ids (P2.6): use <c>Constructs.X</c> at every
/// <see cref="ConstructRegistry.Check"/> call site so an unregistered id is a COMPILE error.</summary>
public static class Constructs
{
    public const string NucleusMoveDisplay = "nucleus-move-display";
    public const string ReadPrevious2002 = "read-previous-2002";
    public const string StartFirstLast2002 = "start-first-last-2002";
    public const string DeleteFile2023 = "delete-file-2023";
    public const string Allocate2002 = "allocate-2002";
    public const string Free2002 = "free-2002";
    public const string Invoke2002 = "invoke-2002";
    public const string GobackReturning2002 = "goback-returning-2002";
    public const string StopRunStatus2002 = "stop-run-status-2002";
    public const string BasedClause2002 = "based-clause-2002";
    public const string ProcedureReturning2002 = "procedure-returning-2002";
    public const string CurrencyPictureSymbol2002 = "currency-picture-symbol-2002";
    public const string PicWide19Digits2002 = "pic-wide-19-digits-2002";
    public const string OptionsArithmeticNative2014 = "options-arithmetic-native-2014";
    public const string RoundedModeIs2014 = "rounded-mode-is-2014";
    public const string ArithmeticStandardDecimal2014 = "arithmetic-standard-decimal-2014";
    public const string OccursDynamic2014 = "occurs-dynamic-2014";
    public const string TypeClause2002 = "type-clause-2002";
    public const string TypedefDef2002 = "typedef-def-2002";
    public const string UsageFloatShort2002 = "usage-float-short-2002";
    public const string UsageFloatBinary322014 = "usage-float-binary32-2014";
    public const string ConstantEntry2002 = "constant-entry-2002";
    public const string ConcatOperator2002 = "concat-operator-2002";
    public const string LabelRecordsRemoved2002 = "label-records-removed-2002";
    public const string UserWordCommit2023 = "user-word-commit-2023";
    public const string UserWordRaising2002 = "user-word-raising-2002";
    public const string ReceiveAsUserWord = "receive-as-user-word";
    public const string EndReceiveAsUserWord = "end-receive-as-user-word";
    public const string ValueOfRemoved2002 = "value-of-removed-2002";
    public const string DataRecordsRemoved2002 = "data-records-removed-2002";
    public const string MultipleFileTapeRemoved2002 = "multiple-file-tape-removed-2002";
    public const string MemorySizeRemoved2002 = "memory-size-removed-2002";
    public const string SegmentLimitRemoved2002 = "segment-limit-removed-2002";
    public const string DebuggingModeRemoved2002 = "debugging-mode-removed-2002";
    public const string IdentificationCommentsRemoved2002 = "identification-comments-removed-2002";
    public const string RemarksRemoved2002 = "remarks-removed-2002";
    public const string StopLiteralRemoved2002 = "stop-literal-removed-2002";
    public const string OpenReversedRemoved2002 = "open-reversed-removed-2002";
    public const string CloseWithLockRemoved2023 = "close-with-lock-removed-2023";
    public const string ExitMethodWindow = "exit-method-window";
    public const string MethodWorkingStorageWindow = "method-working-storage-window";
    public const string ExitFunctionWindow = "exit-function-window";
    public const string ExitProgramArchaic2023 = "exit-program-archaic-2023";
    public const string NextSentenceArchaic2023 = "next-sentence-archaic-2023";
    public const string MoveAlphanumericFigurativeRemoved2023 = "move-alphanumeric-figurative-removed-2023";
    public const string MoveAllDigitIntegerObsolete2023 = "move-all-digit-integer-obsolete-2023";
    public const string NationalData2002 = "national-data-2002";
    public const string NationalEdited2002 = "national-edited-2002";
    public const string BooleanData2002 = "boolean-data-2002";
    public const string PicExternalFloat2002 = "pic-external-float-2002";
    public const string UsagePointer2002 = "usage-pointer-2002";
    public const string UsageObjectReference2002 = "usage-object-reference-2002";
    public const string UsageBinaryCharFamily2002 = "usage-binary-char-family-2002";
    public const string UsageFloatLong2002 = "usage-float-long-2002";
    public const string UsageFloatExtended2002 = "usage-float-extended-2002";
    public const string RepositoryClass2002 = "repository-class-2002";
    public const string StartWithLength2002 = "start-with-length-2002";
    public const string SpecialNamesForNational2002 = "special-names-for-national-2002";
    public const string CallByValue2002 = "call-by-value-2002";
    public const string ClassDefinition2002 = "class-definition-2002";
    public const string InterfaceDefinition2002 = "interface-definition-2002";
    public const string RepositoryInterface2002 = "repository-interface-2002";
    public const string RepositoryProperty2002 = "repository-property-2002";
    public const string PropertyClause2002 = "property-clause-2002";
    public const string ImplementsClause2002 = "implements-clause-2002";
    public const string MethodPropertySelector2002 = "method-property-selector-2002";
    public const string SetObjectReference2002 = "set-object-reference-2002";
    public const string MoveQuoteNumericObsolete2014 = "move-quote-numeric-obsolete-2014";
    public const string BooleanOperators2002 = "boolean-operators-2002";
    public const string UserWordBAnd2002 = "user-word-b-and-2002";
    public const string UserWordPrototype2002 = "user-word-prototype-2002";
    public const string LogicalXorOperator2023 = "logical-xor-operator-2023";
    public const string UserWordXor2023 = "user-word-xor-2023";
    public const string UserWordExclusiveOr2023 = "user-word-exclusive-or-2023";
    public const string FixedFormWordContinuationRemoved2023 = "fixed-form-word-continuation-removed-2023";
    public const string CopyReplacingNonPseudoTextRemoved2023 = "copy-replacing-non-pseudo-text-removed-2023";
    public const string Col7ContinuationObsolete2023 = "col7-continuation-obsolete-2023";
    public const string RerunRemoved2002 = "rerun-removed-2002";
    public const string EnterRemoved2002 = "enter-removed-2002";
    public const string UseForDebuggingRemoved2002 = "use-for-debugging-removed-2002";
    public const string SegmentNumbersRemoved2002 = "segment-numbers-removed-2002";
    public const string UserFunctionInvocation2002 = "user-function-invocation-2002";
    public const string FunctionPrototype2002 = "function-prototype-2002";
    public const string SetAddress2002 = "set-address-2002";
    public const string PointerArithmetic2002 = "pointer-arithmetic-2002";
    public const string FileSharingClause2002 = "file-sharing-clause-2002";
    public const string LockModeClause2002 = "lock-mode-clause-2002";
    public const string RetryPhrase2002 = "retry-phrase-2002";
    public const string UnlockStatement2002 = "unlock-statement-2002";
    public const string RecordLockPhrase2002 = "record-lock-phrase-2002";
    public const string UserWordSharing2002 = "user-word-sharing-2002";
}
