// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using System.Text.Json;
using System.Text.RegularExpressions;
using CobolNet.Editions;
using CobolNet.Tests.Shared;
using Xunit;

namespace CobolNet.Tests.Unit;

/// <summary>
/// The ISO §8.10 context-sensitive word table is single-sourced from the SPEC and generated by
/// <c>scripts/gen-reserved-words.ps1</c> into two artifacts — <c>src/Cobol.Net.Editions/ContextSensitiveWords
/// .Table.cs</c> and <c>tests/version-matrix/context-sensitive-words.json</c>. These tests prove neither can drift
/// from the other OR from §8.10 itself (the parallel of <c>ReservedWordsDriftTests</c> for §8.9).
/// <para>The table exists because <c>&gt;&gt;COBOL-WORDS</c> SR3 admits a context-sensitive word as its EXISTING
/// word and SR4 bars one as its NEW word (§7.3.10.3), and the category test could previously only ask the lexer
/// vocabulary — which knows the context words this compiler happens to tokenize and none of the rest, so legal
/// directives naming HEX, CURRENT, LC_ALL, ANUM, BYTE, ACTIVATING, STACK, TOP-LEVEL, UCS-4, UTF-8 or UTF-16 were
/// rejected outright (kb/Work PB250).</para>
/// Content-filter rule: report counts and at most a few offending words, never a list.
/// </summary>
public sealed class ContextSensitiveWordsDriftTests
{
    /// <summary>The C# table equals the canonical JSON, both directions, word AND context column.</summary>
    [Fact]
    public void CsharpTable_Matches_Json()
    {
        var json = LoadJson();
        var table = ContextSensitiveWords.Entries.ToDictionary(e => e.Word, e => e.Context, StringComparer.Ordinal);

        var onlyJson = json.Keys.Where(w => !table.ContainsKey(w)).Take(5).ToList();
        var onlyTable = table.Keys.Where(w => !json.ContainsKey(w)).Take(5).ToList();
        Assert.True(onlyJson.Count == 0 && onlyTable.Count == 0,
            $"§8.10 drift: json={json.Count} table={table.Count} json-only=[{string.Join(",", onlyJson)}] "
            + $"table-only=[{string.Join(",", onlyTable)}] — re-run scripts/gen-reserved-words.ps1");

        var ctxMismatch = json.Where(kv => table.TryGetValue(kv.Key, out var c) && c != kv.Value)
                              .Select(kv => kv.Key).Take(5).ToList();
        Assert.True(ctxMismatch.Count == 0,
            $"§8.10 context-column drift on [{string.Join(",", ctxMismatch)}]");
    }

    /// <summary>The generated table equals the SPEC section it claims to transcribe — the check that makes the
    /// table evidence rather than a hand list. Re-derives §8.10 from <c>specs/ISO_COBOL.md</c> the way the
    /// generator does, so a spec transcription repair that adds or corrects a row fails here until regenerated.</summary>
    [Fact]
    public void Table_Matches_TheSpecSection()
    {
        var spec = SpecContextWords();
        var table = ContextSensitiveWords.Entries.Select(e => e.Word).ToHashSet(StringComparer.Ordinal);

        var onlySpec = spec.Where(w => !table.Contains(w)).Take(5).ToList();
        var onlyTable = table.Where(w => !spec.Contains(w)).Take(5).ToList();
        Assert.True(onlySpec.Count == 0 && onlyTable.Count == 0,
            $"§8.10 vs spec: spec={spec.Count} table={table.Count} spec-only=[{string.Join(",", onlySpec)}] "
            + $"table-only=[{string.Join(",", onlyTable)}] — re-run scripts/gen-reserved-words.ps1");
    }

    /// <summary>Structural sanity plus the §8.9/§8.10 relationship the two categories have by definition: a word
    /// is context-sensitive OR reserved, never both at the 2023 edition (§8.9 lists the words reserved
    /// everywhere; §8.10 lists the words reserved only in one construct). A word in both tables would make the
    /// SR3/SR4 category answers depend on lookup order.</summary>
    [Fact]
    public void Structural_Sanity_And_NoOverlapWithReservedAt2023()
    {
        var entries = ContextSensitiveWords.Entries;
        Assert.True(entries.Length >= 50, $"only {entries.Length} §8.10 rows");
        Assert.Equal(entries.Length, entries.Select(e => e.Word).Distinct(StringComparer.Ordinal).Count());
        Assert.All(entries, e => Assert.Matches("^[A-Z][A-Z0-9_-]*$", e.Word));
        Assert.All(entries, e => Assert.False(string.IsNullOrWhiteSpace(e.Context), $"{e.Word} has no context"));

        var both = entries.Select(e => e.Word)
                          .Where(w => ReservedWords.Find(w) is { } r && r.R2023)
                          .Take(5).ToList();
        Assert.True(both.Count == 0,
            $"{both.Count} word(s) are in BOTH §8.9 (2023) and §8.10: [{string.Join(",", both)}]");

        Assert.True(ContextSensitiveWords.Contains("hex"));   // case-insensitive lookup
        Assert.Null(ContextSensitiveWords.Find("MOVE"));
    }

    private static Dictionary<string, string> LoadJson()
    {
        string path = TestRepo.VersionMatrix("context-sensitive-words.json");
        Assert.True(File.Exists(path), $"canonical json missing: {path} — run scripts/gen-reserved-words.ps1");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.GetProperty("words").EnumerateArray()
            .ToDictionary(e => e.GetProperty("word").GetString()!, e => e.GetProperty("context").GetString()!,
                          StringComparer.Ordinal);
    }

    private static HashSet<string> SpecContextWords()
    {
        string path = TestRepo.Specs("ISO_COBOL.md");
        Assert.True(File.Exists(path), $"spec missing: {path} — git submodule update --init --recursive");
        var lines = File.ReadAllLines(path);
        int start = -1, end = -1;
        for (int i = 0; i < lines.Length; i++)
        {
            if (start < 0 && Regex.IsMatch(lines[i], @"^#{2,}\s+8\.10\s+Context-sensitive words")) { start = i; continue; }
            if (start >= 0 && Regex.IsMatch(lines[i], @"^#{2,}\s+8\.11\s")) { end = i; break; }
        }
        Assert.True(start >= 0 && end > start, $"spec §8.10 section not located (start={start} end={end})");

        var set = new HashSet<string>(StringComparer.Ordinal);
        for (int i = start + 1; i < end; i++)
        {
            var m = Regex.Match(lines[i], @"^\|\s*\*{0,2}([A-Za-z][A-Za-z0-9_-]*)\*{0,2}\s*\|\s*(.+?)\s*\|\s*$");
            if (m.Success && m.Groups[1].Value != "Context-sensitive") set.Add(m.Groups[1].Value.ToUpperInvariant());
        }
        return set;
    }
}
