// <auto-generated>
//   Generated by COBOL.NET — do not edit. A COBOL program compiled to typed-native C#.
// </auto-generated>
#nullable enable
#pragma warning disable CS0164   // unreferenced label — SEARCH/NEXT-SENTENCE emit per-boundary labels; not every one is jumped to
using System;                    // Int128 — the wide arithmetic carrier (numeric design D1)
using CobolNet.Runtime;          // CobolNum / CobolString substrates + the inter-program ABI (ManagedPointer / ICobolProgram / ProgramRegistry)
using CobolNet.Runtime.IO;       // CobolFile — the sequential file-I/O facade (§8)

internal sealed class _PRG_IC101A : ICobolProgram
{
    private bool __asCalled;   // true during a CALL activation — EXIT PROGRAM is CONTINUE otherwise (ISO §14.9.14 GR2)
    private bool __filesRegistered;   // connectors register once per INSTANCE — a canceled/INITIAL program gets fresh connectors (ISO §14.6.2.3.2)
    private record struct _T_10
    {
        public string _filler3;   // FILLER
        public string PARDOT_X;   // PARDOT-X
        public string DOTVALUE;   // DOTVALUE
        public readonly string AsImage() => _filler3 + PARDOT_X + DOTVALUE;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 22);
            _filler3 = __s.Substring(0, 19);
            PARDOT_X = __s.Substring(19, 1);
            DOTVALUE = __s.Substring(20, 2);
        }
    }
    private record struct _T_4
    {
        public string _filler0;   // FILLER
        public string FEATURE;   // FEATURE
        public string _filler1;   // FILLER
        public string P_OR_F;   // P-OR-F
        public string _filler2;   // FILLER
        public _T_10 PAR_NAME;   // PAR-NAME
        public string _filler4;   // FILLER
        public string RE_MARK;   // RE-MARK
        public readonly string AsImage() => _filler0 + FEATURE + _filler1 + P_OR_F + _filler2 + PAR_NAME.AsImage() + _filler4 + RE_MARK;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 119);
            _filler0 = __s.Substring(0, 1);
            FEATURE = __s.Substring(1, 20);
            _filler1 = __s.Substring(21, 1);
            P_OR_F = __s.Substring(22, 5);
            _filler2 = __s.Substring(27, 1);
            PAR_NAME.FromImage(__s.Substring(28, 22));
            _filler4 = __s.Substring(50, 8);
            RE_MARK = __s.Substring(58, 61);
        }
    }
    private record struct _T_25
    {
        public readonly string AsImage() => "";
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 0);
        }
    }
    private record struct _T_19
    {
        public string _redef_COMPUTED_A;   // REDEFINES backing for COMPUTED-A
        public string _filler8;   // FILLER
        public readonly string AsImage() => _redef_COMPUTED_A + _filler8;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 70);
            _redef_COMPUTED_A = __s.Substring(0, 20);
            _filler8 = __s.Substring(20, 50);
        }
    }
    private record struct _T_16
    {
        public string _filler5;   // FILLER
        public string _filler6;   // FILLER
        public _T_19 COMPUTED_X;   // COMPUTED-X
        public readonly string AsImage() => _filler5 + _filler6 + COMPUTED_X.AsImage();
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 117);
            _filler5 = __s.Substring(0, 30);
            _filler6 = __s.Substring(30, 17);
            COMPUTED_X.FromImage(__s.Substring(47, 70));
        }
    }
    private record struct _T_38
    {
        public readonly string AsImage() => "";
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 0);
        }
    }
    private record struct _T_32
    {
        public string _redef_CORRECT_A;   // REDEFINES backing for CORRECT-A
        public string _filler12;   // FILLER
        public string COR_ANSI_REFERENCE;   // COR-ANSI-REFERENCE
        public readonly string AsImage() => _redef_CORRECT_A + _filler12 + COR_ANSI_REFERENCE;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 70);
            _redef_CORRECT_A = __s.Substring(0, 20);
            _filler12 = __s.Substring(20, 2);
            COR_ANSI_REFERENCE = __s.Substring(22, 48);
        }
    }
    private record struct _T_29
    {
        public string _filler9;   // FILLER
        public string _filler10;   // FILLER
        public _T_32 CORRECT_X;   // CORRECT-X
        public readonly string AsImage() => _filler9 + _filler10 + CORRECT_X.AsImage();
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 117);
            _filler9 = __s.Substring(0, 30);
            _filler10 = __s.Substring(30, 17);
            CORRECT_X.FromImage(__s.Substring(47, 70));
        }
    }
    private record struct _T_43
    {
        public string _filler13;   // FILLER
        public string _filler14;   // FILLER
        public readonly string AsImage() => _filler13 + _filler14;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 119);
            _filler13 = __s.Substring(0, 99);
            _filler14 = __s.Substring(99, 20);
        }
    }
    private record struct _T_46
    {
        public string _filler15;   // FILLER
        public string _filler16;   // FILLER
        public string _filler17;   // FILLER
        public string _filler18;   // FILLER
        public string _filler19;   // FILLER
        public readonly string AsImage() => _filler15 + _filler16 + _filler17 + _filler18 + _filler19;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler15 = __s.Substring(0, 1);
            _filler16 = __s.Substring(1, 6);
            _filler17 = __s.Substring(7, 15);
            _filler18 = __s.Substring(22, 4);
            _filler19 = __s.Substring(26, 94);
        }
    }
    private record struct _T_63
    {
        public string _filler20;   // FILLER
        public string _filler21;   // FILLER
        public string _filler22;   // FILLER
        public readonly string AsImage() => _filler20 + _filler21 + _filler22;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler20 = __s.Substring(0, 39);
            _filler21 = __s.Substring(39, 42);
            _filler22 = __s.Substring(81, 39);
        }
    }
    private record struct _T_67
    {
        public string _filler23;   // FILLER
        public string _filler24;   // FILLER
        public string _filler25;   // FILLER
        public string _filler26;   // FILLER
        public string _filler27;   // FILLER
        public readonly string AsImage() => _filler23 + _filler24 + _filler25 + _filler26 + _filler27;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler23 = __s.Substring(0, 40);
            _filler24 = __s.Substring(40, 7);
            _filler25 = __s.Substring(47, 4);
            _filler26 = __s.Substring(51, 28);
            _filler27 = __s.Substring(79, 41);
        }
    }
    private record struct _T_73
    {
        public string _filler28;   // FILLER
        public string TEST_ID;   // TEST-ID
        public string _filler29;   // FILLER
        public string _filler30;   // FILLER
        public string _filler31;   // FILLER
        public string _filler32;   // FILLER
        public readonly string AsImage() => _filler28 + TEST_ID + _filler29 + _filler30 + _filler31 + _filler32;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler28 = __s.Substring(0, 15);
            TEST_ID = __s.Substring(15, 9);
            _filler29 = __s.Substring(24, 4);
            _filler30 = __s.Substring(28, 12);
            _filler31 = __s.Substring(40, 22);
            _filler32 = __s.Substring(62, 58);
        }
    }
    private record struct _T_80
    {
        public string _filler33;   // FILLER
        public string _filler34;   // FILLER
        public string _filler35;   // FILLER
        public readonly string AsImage() => _filler33 + _filler34 + _filler35;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler33 = __s.Substring(0, 34);
            _filler34 = __s.Substring(34, 58);
            _filler35 = __s.Substring(92, 28);
        }
    }
    private record struct _T_84
    {
        public string _filler36;   // FILLER
        public string _filler37;   // FILLER
        public string ID_AGAIN;   // ID-AGAIN
        public string _filler38;   // FILLER
        public readonly string AsImage() => _filler36 + _filler37 + ID_AGAIN + _filler38;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler36 = __s.Substring(0, 52);
            _filler37 = __s.Substring(52, 14);
            ID_AGAIN = __s.Substring(66, 9);
            _filler38 = __s.Substring(75, 45);
        }
    }
    private record struct _T_92
    {
        public string ERROR_TOTAL;   // ERROR-TOTAL
        public string _filler41;   // FILLER
        public string ENDER_DESC;   // ENDER-DESC
        public readonly string AsImage() => ERROR_TOTAL + _filler41 + ENDER_DESC;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 48);
            ERROR_TOTAL = __s.Substring(0, 3);
            _filler41 = __s.Substring(3, 1);
            ENDER_DESC = __s.Substring(4, 44);
        }
    }
    private record struct _T_89
    {
        public string _filler39;   // FILLER
        public string _filler40;   // FILLER
        public _T_92 CCVS_E_2_2;   // CCVS-E-2-2
        public readonly string AsImage() => _filler39 + _filler40 + CCVS_E_2_2.AsImage();
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 100);
            _filler39 = __s.Substring(0, 31);
            _filler40 = __s.Substring(31, 21);
            CCVS_E_2_2.FromImage(__s.Substring(52, 48));
        }
    }
    private record struct _T_96
    {
        public string _filler42;   // FILLER
        public string _filler43;   // FILLER
        public string _filler44;   // FILLER
        public string _filler45;   // FILLER
        public string _filler46;   // FILLER
        public readonly string AsImage() => _filler42 + _filler43 + _filler44 + _filler45 + _filler46;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler42 = __s.Substring(0, 22);
            _filler43 = __s.Substring(22, 12);
            _filler44 = __s.Substring(34, 58);
            _filler45 = __s.Substring(92, 13);
            _filler46 = __s.Substring(105, 15);
        }
    }
    private record struct _T_102
    {
        public string CCVS_E_4_1;   // CCVS-E-4-1
        public string _filler47;   // FILLER
        public string CCVS_E_4_2;   // CCVS-E-4-2
        public string _filler48;   // FILLER
        public readonly string AsImage() => CCVS_E_4_1 + _filler47 + CCVS_E_4_2 + _filler48;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 50);
            CCVS_E_4_1 = __s.Substring(0, 3);
            _filler47 = __s.Substring(3, 4);
            CCVS_E_4_2 = __s.Substring(7, 3);
            _filler48 = __s.Substring(10, 40);
        }
    }
    private record struct _T_109
    {
        public string _filler50;   // FILLER
        public string XXCOMPUTED;   // XXCOMPUTED
        public string _filler51;   // FILLER
        public string XXCORRECT;   // XXCORRECT
        public readonly string AsImage() => _filler50 + XXCOMPUTED + _filler51 + XXCORRECT;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 53);
            _filler50 = __s.Substring(0, 8);
            XXCOMPUTED = __s.Substring(8, 20);
            _filler51 = __s.Substring(28, 5);
            XXCORRECT = __s.Substring(33, 20);
        }
    }
    private record struct _T_107
    {
        public string _filler49;   // FILLER
        public _T_109 INFO_TEXT;   // INFO-TEXT
        public string INF_ANSI_REFERENCE;   // INF-ANSI-REFERENCE
        public readonly string AsImage() => _filler49 + INFO_TEXT.AsImage() + INF_ANSI_REFERENCE;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler49 = __s.Substring(0, 19);
            INFO_TEXT.FromImage(__s.Substring(19, 53));
            INF_ANSI_REFERENCE = __s.Substring(72, 48);
        }
    }
    private record struct _T_115
    {
        public string _filler52;   // FILLER
        public string _filler53;   // FILLER
        public string _filler54;   // FILLER
        public readonly string AsImage() => _filler52 + _filler53 + _filler54;
        public void FromImage(string __s)
        {
            __s = CobolString.Store(__s, 120);
            _filler52 = __s.Substring(0, 1);
            _filler53 = __s.Substring(1, 65);
            _filler54 = __s.Substring(66, 54);
        }
    }
    internal static readonly NumProfile _P_2 = new NumProfile { Digits = 1, FractionDigits = 0, Signed = true, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_3 = new NumProfile { Digits = 1, FractionDigits = 0, Signed = true, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_13 = new NumProfile { Digits = 2, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_52 = new NumProfile { Digits = 2, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_53 = new NumProfile { Digits = 2, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_54 = new NumProfile { Digits = 3, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_55 = new NumProfile { Digits = 3, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_56 = new NumProfile { Digits = 3, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_57 = new NumProfile { Digits = 3, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_58 = new NumProfile { Digits = 3, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_59 = new NumProfile { Digits = 3, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_61 = new NumProfile { Digits = 5, FractionDigits = 0, Signed = false, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    private string PRINT_REC = new string(' ', 120);   // PRINT-REC
    private long DN1 = 0L;   // DN1
    private long DN2 = 0L;   // DN2
    private _T_4 TEST_RESULTS = new _T_4 { _filler0 = new string(' ', 1), FEATURE = new string(' ', 20), _filler1 = new string(' ', 1), P_OR_F = new string(' ', 5), _filler2 = new string(' ', 1), PAR_NAME = new _T_10 { _filler3 = new string(' ', 19), PARDOT_X = new string(' ', 1), DOTVALUE = CobolNum.FormatDisplay(0L, _P_13) }, _filler4 = new string(' ', 8), RE_MARK = new string(' ', 61) };   // TEST-RESULTS
    private _T_16 TEST_COMPUTED = new _T_16 { _filler5 = new string(' ', 30), _filler6 = CobolString.Store("       COMPUTED=", 17), COMPUTED_X = new _T_19 { _redef_COMPUTED_A = CobolString.Store(new string(' ', 20), 20), _filler8 = new string(' ', 50) } };   // TEST-COMPUTED
    private _T_29 TEST_CORRECT = new _T_29 { _filler9 = new string(' ', 30), _filler10 = CobolString.Store("       CORRECT =", 17), CORRECT_X = new _T_32 { _redef_CORRECT_A = CobolString.Store(new string(' ', 20), 20), _filler12 = new string(' ', 2), COR_ANSI_REFERENCE = new string(' ', 48) } };   // TEST-CORRECT
    private _T_43 CCVS_C_1 = new _T_43 { _filler13 = CobolString.Store(" FEATURE              PASS  PARAGRAPH-NAME                                                 REMARKS", 99), _filler14 = new string(' ', 20) };   // CCVS-C-1
    private _T_46 CCVS_C_2 = new _T_46 { _filler15 = new string(' ', 1), _filler16 = CobolString.Store("TESTED", 6), _filler17 = new string(' ', 15), _filler18 = CobolString.Store("FAIL", 4), _filler19 = new string(' ', 94) };   // CCVS-C-2
    private long REC_SKL_SUB = 0L;   // REC-SKL-SUB
    private long REC_CT = 0L;   // REC-CT
    private long DELETE_COUNTER = 0L;   // DELETE-COUNTER
    private long ERROR_COUNTER = 0L;   // ERROR-COUNTER
    private long INSPECT_COUNTER = 0L;   // INSPECT-COUNTER
    private long PASS_COUNTER = 0L;   // PASS-COUNTER
    private long TOTAL_ERROR = 0L;   // TOTAL-ERROR
    private long ERROR_HOLD = 0L;   // ERROR-HOLD
    private string DUMMY_HOLD = new string(' ', 120);   // DUMMY-HOLD
    private long RECORD_COUNT = 0L;   // RECORD-COUNT
    private string ANSI_REFERENCE = new string(' ', 48);   // ANSI-REFERENCE
    private _T_63 CCVS_H_1 = new _T_63 { _filler20 = new string(' ', 39), _filler21 = CobolString.Store("OFFICIAL COBOL COMPILER VALIDATION SYSTEM", 42), _filler22 = new string(' ', 39) };   // CCVS-H-1
    private _T_67 CCVS_H_2A = new _T_67 { _filler23 = new string(' ', 40), _filler24 = CobolString.Store("CCVS85 ", 7), _filler25 = CobolString.Store("4.2 ", 4), _filler26 = CobolString.Store(" COPY - NOT FOR DISTRIBUTION", 28), _filler27 = new string(' ', 41) };   // CCVS-H-2A
    private _T_73 CCVS_H_2B = new _T_73 { _filler28 = CobolString.Store("TEST RESULT OF ", 15), TEST_ID = new string(' ', 9), _filler29 = CobolString.Store(" IN ", 4), _filler30 = CobolString.Store(" HIGH       ", 12), _filler31 = CobolString.Store(" LEVEL VALIDATION FOR ", 22), _filler32 = CobolString.Store("ON-SITE VALIDATION, NATIONAL INSTITUTE OF STD & TECH.     ", 58) };   // CCVS-H-2B
    private _T_80 CCVS_H_3 = new _T_80 { _filler33 = CobolString.Store(" FOR OFFICIAL USE ONLY    ", 34), _filler34 = CobolString.Store("COBOL 85 VERSION 4.2, Apr  1993 SSVG                      ", 58), _filler35 = CobolString.Store("  COPYRIGHT   1985 ", 28) };   // CCVS-H-3
    private _T_84 CCVS_E_1 = new _T_84 { _filler36 = new string(' ', 52), _filler37 = CobolString.Store("END OF TEST-  ", 14), ID_AGAIN = new string(' ', 9), _filler38 = new string(' ', 45) };   // CCVS-E-1
    private _T_89 CCVS_E_2 = new _T_89 { _filler39 = new string(' ', 31), _filler40 = new string(' ', 21), CCVS_E_2_2 = new _T_92 { ERROR_TOTAL = new string(' ', 3), _filler41 = new string(' ', 1), ENDER_DESC = CobolString.Store("ERRORS ENCOUNTERED", 44) } };   // CCVS-E-2
    private _T_96 CCVS_E_3 = new _T_96 { _filler42 = CobolString.Store(" FOR OFFICIAL USE ONLY", 22), _filler43 = new string(' ', 12), _filler44 = CobolString.Store("ON-SITE VALIDATION, NATIONAL INSTITUTE OF STD & TECH.     ", 58), _filler45 = new string(' ', 13), _filler46 = CobolString.Store(" COPYRIGHT 1985", 15) };   // CCVS-E-3
    private _T_102 CCVS_E_4 = new _T_102 { CCVS_E_4_1 = new string(' ', 3), _filler47 = CobolString.Store(" OF ", 4), CCVS_E_4_2 = new string(' ', 3), _filler48 = CobolString.Store("  TESTS WERE EXECUTED SUCCESSFULLY", 40) };   // CCVS-E-4
    private _T_107 XXINFO = new _T_107 { _filler49 = CobolString.Store("*** INFORMATION ***", 19), INFO_TEXT = new _T_109 { _filler50 = new string(' ', 8), XXCOMPUTED = new string(' ', 20), _filler51 = new string(' ', 5), XXCORRECT = new string(' ', 20) }, INF_ANSI_REFERENCE = new string(' ', 48) };   // XXINFO
    private _T_115 HYPHEN_LINE = new _T_115 { _filler52 = new string(' ', 1), _filler53 = CobolString.Store("*****************************************************************", 65), _filler54 = CobolString.Store("******************************************************", 54) };   // HYPHEN-LINE
    private string CCVS_PGM_ID = CobolString.Store("IC101A", 9);   // CCVS-PGM-ID

    public void Call(CobolArg[] __args, ManagedPointer? __ret)
    {
        __asCalled = true;
        try { __Activate(); } finally { __asCalled = false; }
    }
    void ICobolProgram.Activate() => __Activate();
    public void CloseFiles()
    {
        CobolFile.Close("IC101A::PRINT-FILE");
    }


    private const int __N = 46;   // paragraph count

    public void __Activate()
    {
        if (!__filesRegistered)
        {
            __filesRegistered = true;
            CobolFile.Register("IC101A::PRINT-FILE", "IC101A", 120, false, false);
        }
        try { __Dispatch(0, -1); } catch (ProgramReturn) { }   // GOBACK / called-program EXIT PROGRAM returns to the activator here (ISO §14.9.18 GR2/GR3; §14.9.14 GR3)
    }

    private int __Dispatch(int __startPc, int __exitPc)
    {
        int __pc = __startPc;
        while ((uint)__pc < (uint)__N)
        {
            bool __atExit = __pc == __exitPc;   // captured before the body overwrites __pc
            switch (__pc)
            {
                case 0:   // OPEN-FILES
                {
                    CobolFile.OpenOutput("IC101A::PRINT-FILE");
                    CCVS_H_2B.TEST_ID = CobolString.Store(CCVS_PGM_ID, 9);
                    CCVS_E_1.ID_AGAIN = CobolString.Store(CCVS_PGM_ID, 9);
                    TEST_RESULTS.FromImage(new string(' ', 119));
                    __Dispatch(8, 9);
                    __pc = 24;
                    break;
                }
                case 1:   // CLOSE-FILES
                {
                    __Dispatch(10, 14);
                    CobolFile.Close("IC101A::PRINT-FILE");
                    __pc = 2;
                    break;
                }
                case 2:   // TERMINATE-CCVS
                {
                    throw new StopRun();
                }
                case 3:   // INSPT
                {
                    TEST_RESULTS.P_OR_F = CobolString.Store("INSPT", 5);
                    INSPECT_COUNTER = (long)(CobolNum.Store(((Int128)(INSPECT_COUNTER) + (1L)), 0, _P_56, CobolRounding.Truncation));
                    __pc = 4;
                    break;
                }
                case 4:   // PASS
                {
                    TEST_RESULTS.P_OR_F = CobolString.Store("PASS ", 5);
                    PASS_COUNTER = (long)(CobolNum.Store(((Int128)(PASS_COUNTER) + (1L)), 0, _P_57, CobolRounding.Truncation));
                    __pc = 5;
                    break;
                }
                case 5:   // FAIL
                {
                    TEST_RESULTS.P_OR_F = CobolString.Store("FAIL*", 5);
                    ERROR_COUNTER = (long)(CobolNum.Store(((Int128)(ERROR_COUNTER) + (1L)), 0, _P_55, CobolRounding.Truncation));
                    __pc = 6;
                    break;
                }
                case 6:   // DE-LETE
                {
                    TEST_RESULTS.P_OR_F = CobolString.Store("*****", 5);
                    DELETE_COUNTER = (long)(CobolNum.Store(((Int128)(DELETE_COUNTER) + (1L)), 0, _P_54, CobolRounding.Truncation));
                    TEST_RESULTS.RE_MARK = CobolString.Store("****TEST DELETED****", 61);
                    __pc = 7;
                    break;
                }
                case 7:   // PRINT-DETAIL
                {
                    if (REC_CT != 0L)
                    {
                        TEST_RESULTS.PAR_NAME.PARDOT_X = CobolString.Store(".", 1);
                        TEST_RESULTS.PAR_NAME.DOTVALUE = CobolNum.FormatDisplay((long)(CobolNum.Store(REC_CT, 0, _P_13)), _P_13);
                    }
                    PRINT_REC = CobolString.Store(TEST_RESULTS.AsImage(), 120);
                    __Dispatch(15, 15);
                    if (CobolString.Compare(TEST_RESULTS.P_OR_F, "FAIL*") == 0)
                    {
                        __Dispatch(15, 15);
                        __Dispatch(18, 20);
                    }
                    else
                    {
                        __Dispatch(21, 23);
                    }
                    TEST_RESULTS.P_OR_F = new string(' ', 5);
                    TEST_COMPUTED.COMPUTED_X.FromImage(new string(' ', 70));
                    TEST_CORRECT.CORRECT_X.FromImage(new string(' ', 70));
                    if (REC_CT == 0L)
                    {
                        TEST_RESULTS.PAR_NAME.FromImage(new string(' ', 22));
                    }
                    TEST_RESULTS.RE_MARK = new string(' ', 61);
                    __pc = 8;
                    break;
                }
                case 8:   // HEAD-ROUTINE
                {
                    PRINT_REC = CobolString.Store(CCVS_H_1.AsImage(), 120);
                    long __n0 = 2;
                    for (long __i0 = 0; __i0 < __n0; __i0++)
                    {
                        __Dispatch(15, 15);
                    }
                    PRINT_REC = CobolString.Store(CCVS_H_2A.AsImage(), 120);
                    long __n1 = 2;
                    for (long __i1 = 0; __i1 < __n1; __i1++)
                    {
                        __Dispatch(15, 15);
                    }
                    PRINT_REC = CobolString.Store(CCVS_H_2B.AsImage(), 120);
                    long __n2 = 3;
                    for (long __i2 = 0; __i2 < __n2; __i2++)
                    {
                        __Dispatch(15, 15);
                    }
                    PRINT_REC = CobolString.Store(CCVS_H_3.AsImage(), 120);
                    long __n3 = 3;
                    for (long __i3 = 0; __i3 < __n3; __i3++)
                    {
                        __Dispatch(15, 15);
                    }
                    __pc = 9;
                    break;
                }
                case 9:   // COLUMN-NAMES-ROUTINE
                {
                    PRINT_REC = CobolString.Store(CCVS_C_1.AsImage(), 120);
                    __Dispatch(15, 15);
                    PRINT_REC = CobolString.Store(CCVS_C_2.AsImage(), 120);
                    long __n4 = 2;
                    for (long __i4 = 0; __i4 < __n4; __i4++)
                    {
                        __Dispatch(15, 15);
                    }
                    PRINT_REC = CobolString.Store(HYPHEN_LINE.AsImage(), 120);
                    __Dispatch(15, 15);
                    __pc = 10;
                    break;
                }
                case 10:   // END-ROUTINE
                {
                    PRINT_REC = CobolString.Store(HYPHEN_LINE.AsImage(), 120);
                    long __n5 = 5;
                    for (long __i5 = 0; __i5 < __n5; __i5++)
                    {
                        __Dispatch(15, 15);
                    }
                    __pc = 11;
                    break;
                }
                case 11:   // END-RTN-EXIT
                {
                    PRINT_REC = CobolString.Store(CCVS_E_1.AsImage(), 120);
                    long __n6 = 2;
                    for (long __i6 = 0; __i6 < __n6; __i6++)
                    {
                        __Dispatch(15, 15);
                    }
                    __pc = 12;
                    break;
                }
                case 12:   // END-ROUTINE-1
                {
                    ERROR_HOLD = (long)(CobolNum.Store(((Int128)(ERROR_HOLD) + (ERROR_COUNTER)), 0, _P_59, CobolRounding.Truncation));
                    ERROR_HOLD = (long)(CobolNum.Store(((Int128)(ERROR_HOLD) + (INSPECT_COUNTER)), 0, _P_59, CobolRounding.Truncation));
                    ERROR_HOLD = (long)(CobolNum.Store(((Int128)(ERROR_HOLD) + (DELETE_COUNTER)), 0, _P_59, CobolRounding.Truncation));
                    ERROR_HOLD = (long)(CobolNum.Store(((Int128)(ERROR_HOLD) + (PASS_COUNTER)), 0, _P_59, CobolRounding.Truncation));
                    CCVS_E_4.CCVS_E_4_1 = CobolString.Store(CobolNum.FormatUnsignedDisplay(PASS_COUNTER, 3), 3);
                    CCVS_E_4.CCVS_E_4_2 = CobolString.Store(CobolNum.FormatUnsignedDisplay(ERROR_HOLD, 3), 3);
                    CCVS_E_2.CCVS_E_2_2.FromImage(CobolString.Store(CCVS_E_4.AsImage(), 48));
                    PRINT_REC = CobolString.Store(CCVS_E_2.AsImage(), 120);
                    __Dispatch(15, 15);
                    __pc = 13;
                    break;
                }
                case 13:   // END-ROUTINE-12
                {
                    CCVS_E_2.CCVS_E_2_2.ENDER_DESC = CobolString.Store("TEST(S) FAILED", 44);
                    if (ERROR_COUNTER == 0L)
                    {
                        CCVS_E_2.CCVS_E_2_2.ERROR_TOTAL = CobolString.Store("NO ", 3);
                    }
                    else
                    {
                        CCVS_E_2.CCVS_E_2_2.ERROR_TOTAL = CobolString.Store(CobolNum.FormatUnsignedDisplay(ERROR_COUNTER, 3), 3);
                    }
                    PRINT_REC = CobolString.Store(CCVS_E_2.AsImage(), 120);
                    __Dispatch(15, 15);
                    __pc = 14;
                    break;
                }
                case 14:   // END-ROUTINE-13
                {
                    if (DELETE_COUNTER == 0L)
                    {
                        CCVS_E_2.CCVS_E_2_2.ERROR_TOTAL = CobolString.Store("NO ", 3);
                    }
                    else
                    {
                        CCVS_E_2.CCVS_E_2_2.ERROR_TOTAL = CobolString.Store(CobolNum.FormatUnsignedDisplay(DELETE_COUNTER, 3), 3);
                    }
                    CCVS_E_2.CCVS_E_2_2.ENDER_DESC = CobolString.Store("TEST(S) DELETED     ", 44);
                    PRINT_REC = CobolString.Store(CCVS_E_2.AsImage(), 120);
                    __Dispatch(15, 15);
                    if (INSPECT_COUNTER == 0L)
                    {
                        CCVS_E_2.CCVS_E_2_2.ERROR_TOTAL = CobolString.Store("NO ", 3);
                    }
                    else
                    {
                        CCVS_E_2.CCVS_E_2_2.ERROR_TOTAL = CobolString.Store(CobolNum.FormatUnsignedDisplay(INSPECT_COUNTER, 3), 3);
                    }
                    CCVS_E_2.CCVS_E_2_2.ENDER_DESC = CobolString.Store("TEST(S) REQUIRE INSPECTION", 44);
                    PRINT_REC = CobolString.Store(CCVS_E_2.AsImage(), 120);
                    __Dispatch(15, 15);
                    PRINT_REC = CobolString.Store(CCVS_E_3.AsImage(), 120);
                    __Dispatch(15, 15);
                    __pc = 15;
                    break;
                }
                case 15:   // WRITE-LINE
                {
                    RECORD_COUNT = (long)(CobolNum.Store(((Int128)(RECORD_COUNT) + (1L)), 0, _P_61, CobolRounding.Truncation));
                    __Dispatch(16, 16);
                    __pc = 16;
                    break;
                }
                case 16:   // WRT-LN
                {
                    CobolFile.WriteAdvancing("IC101A::PRINT-FILE", PRINT_REC, (int)(1), false);
                    PRINT_REC = new string(' ', 120);
                    __pc = 17;
                    break;
                }
                case 17:   // BLANK-LINE-PRINT
                {
                    __Dispatch(16, 16);
                    __pc = 18;
                    break;
                }
                case 18:   // FAIL-ROUTINE
                {
                    if (CobolString.Compare(TEST_COMPUTED.COMPUTED_X.AsImage(), new string(' ', 70)) != 0)
                    {
                        __pc = 19;
                        break;
                    }
                    if (CobolString.Compare(TEST_CORRECT.CORRECT_X.AsImage(), new string(' ', 70)) != 0)
                    {
                        __pc = 19;
                        break;
                    }
                    XXINFO.INF_ANSI_REFERENCE = CobolString.Store(ANSI_REFERENCE, 48);
                    XXINFO.INFO_TEXT.FromImage(CobolString.Store("NO FURTHER INFORMATION, SEE PROGRAM.", 53));
                    PRINT_REC = CobolString.Store(XXINFO.AsImage(), 120);
                    long __n7 = 2;
                    for (long __i7 = 0; __i7 < __n7; __i7++)
                    {
                        __Dispatch(15, 15);
                    }
                    XXINFO.INF_ANSI_REFERENCE = new string(' ', 48);
                    __pc = 20;
                    break;
                }
                case 19:   // FAIL-ROUTINE-WRITE
                {
                    PRINT_REC = CobolString.Store(TEST_COMPUTED.AsImage(), 120);
                    __Dispatch(15, 15);
                    TEST_CORRECT.CORRECT_X.COR_ANSI_REFERENCE = CobolString.Store(ANSI_REFERENCE, 48);
                    PRINT_REC = CobolString.Store(TEST_CORRECT.AsImage(), 120);
                    long __n8 = 2;
                    for (long __i8 = 0; __i8 < __n8; __i8++)
                    {
                        __Dispatch(15, 15);
                    }
                    TEST_CORRECT.CORRECT_X.COR_ANSI_REFERENCE = new string(' ', 48);
                    __pc = 20;
                    break;
                }
                case 20:   // FAIL-ROUTINE-EX
                {
                    __pc = 21;
                    break;
                }
                case 21:   // BAIL-OUT
                {
                    if (CobolString.Compare(CobolString.RefMod(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 20), new string(' ', 20)) != 0)
                    {
                        __pc = 22;
                        break;
                    }
                    if (CobolString.Compare(CobolString.RefMod(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 20), new string(' ', 20)) == 0)
                    {
                        __pc = 23;
                        break;
                    }
                    __pc = 22;
                    break;
                }
                case 22:   // BAIL-OUT-WRITE
                {
                    XXINFO.INFO_TEXT.XXCORRECT = CobolString.Store(CobolString.RefMod(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 20), 20);
                    XXINFO.INFO_TEXT.XXCOMPUTED = CobolString.Store(CobolString.RefMod(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 20), 20);
                    XXINFO.INF_ANSI_REFERENCE = CobolString.Store(ANSI_REFERENCE, 48);
                    PRINT_REC = CobolString.Store(XXINFO.AsImage(), 120);
                    long __n9 = 2;
                    for (long __i9 = 0; __i9 < __n9; __i9++)
                    {
                        __Dispatch(15, 15);
                    }
                    XXINFO.INF_ANSI_REFERENCE = new string(' ', 48);
                    __pc = 23;
                    break;
                }
                case 23:   // BAIL-OUT-EX
                {
                    __pc = 24;
                    break;
                }
                case 24:   // CCVS1-EXIT
                {
                    __pc = 25;
                    break;
                }
                case 25:   // CALL-INIT-1
                {
                    TEST_RESULTS.FEATURE = CobolString.Store("CALL...USING DATA-NM", 20);
                    TEST_RESULTS.PAR_NAME.FromImage(CobolString.Store("CALL-TEST-01", 22));
                    __pc = 26;
                    break;
                }
                case 26:   // CALL-TEST-1
                {
                    ProgramRegistry.CallProgram("IC102A", "IC101A", new CobolArg[] { new CobolArg(CobolPassMode.Reference, ManagedPointer<long>.OverField(() => DN1, __v => { DN1 = __v; }), 1, 0) }, null);
                    if (DN1 == 1L)
                    {
                        __Dispatch(4, 4);
                        __pc = 28;
                        break;
                    }
                    __pc = 27;
                    break;
                }
                case 27:   // CALL-FAIL-1
                {
                    TEST_CORRECT.CORRECT_X._redef_CORRECT_A = CobolString.SpliceInto(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 19, CobolEdit.Format(1L, 0, "-999999999999999999"));
                    TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A = CobolString.SpliceInto(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 19, CobolEdit.Format(DN1, 0, "-999999999999999999"));
                    __Dispatch(5, 5);
                    __pc = 28;
                    break;
                }
                case 28:   // CALL-WRITE-1
                {
                    __Dispatch(7, 7);
                    __pc = 29;
                    break;
                }
                case 29:   // CALL-INIT-2
                {
                    DN1 = (long)(CobolNum.Store(0L, 0, _P_2));
                    __pc = 30;
                    break;
                }
                case 30:   // CALL-TEST-2
                {
                    ProgramRegistry.CallProgram("IC102A", "IC101A", new CobolArg[] { new CobolArg(CobolPassMode.Reference, ManagedPointer<long>.OverField(() => DN1, __v => { DN1 = __v; }), 1, 0) }, null);
                    if (DN1 == 2L)
                    {
                        __Dispatch(4, 4);
                        __pc = 32;
                        break;
                    }
                    __pc = 31;
                    break;
                }
                case 31:   // CALL-FAIL-2
                {
                    TEST_CORRECT.CORRECT_X._redef_CORRECT_A = CobolString.SpliceInto(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 19, CobolEdit.Format(2L, 0, "-999999999999999999"));
                    TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A = CobolString.SpliceInto(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 19, CobolEdit.Format(DN1, 0, "-999999999999999999"));
                    __Dispatch(5, 5);
                    __pc = 32;
                    break;
                }
                case 32:   // CALL-WRITE-2
                {
                    TEST_RESULTS.PAR_NAME.FromImage(CobolString.Store("CALL-TEST-02", 22));
                    __Dispatch(7, 7);
                    __pc = 33;
                    break;
                }
                case 33:   // CALL-INIT-3
                {
                    DN1 = (long)(CobolNum.Store(((Int128)(DN1) + (4L)), 0, _P_2, CobolRounding.Truncation));
                    __pc = 34;
                    break;
                }
                case 34:   // CALL-TEST-3
                {
                    ProgramRegistry.CallProgram("IC102A", "IC101A", new CobolArg[] { new CobolArg(CobolPassMode.Reference, ManagedPointer<long>.OverField(() => DN1, __v => { DN1 = __v; }), 1, 0) }, null);
                    if (DN1 == 3L)
                    {
                        __Dispatch(4, 4);
                        __pc = 36;
                        break;
                    }
                    __pc = 35;
                    break;
                }
                case 35:   // CALL-FAIL-3
                {
                    TEST_CORRECT.CORRECT_X._redef_CORRECT_A = CobolString.SpliceInto(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 19, CobolEdit.Format(3L, 0, "-999999999999999999"));
                    TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A = CobolString.SpliceInto(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 19, CobolEdit.Format(DN1, 0, "-999999999999999999"));
                    __Dispatch(5, 5);
                    __pc = 36;
                    break;
                }
                case 36:   // CALL-WRITE-3
                {
                    TEST_RESULTS.PAR_NAME.FromImage(CobolString.Store("CALL-TEST-03", 22));
                    __Dispatch(7, 7);
                    __pc = 37;
                    break;
                }
                case 37:   // CALL-TEST-4
                {
                    ProgramRegistry.CallProgram("IC102A", "IC101A", new CobolArg[] { new CobolArg(CobolPassMode.Reference, ManagedPointer<long>.OverField(() => DN2, __v => { DN2 = __v; }), 1, 0) }, null);
                    if (DN2 != 4L)
                    {
                        __pc = 38;
                        break;
                    }
                    __Dispatch(4, 4);
                    __pc = 39;
                    break;
                }
                case 38:   // CALL-FAIL-4
                {
                    TEST_CORRECT.CORRECT_X._redef_CORRECT_A = CobolString.SpliceInto(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 19, CobolEdit.Format(4L, 0, "-999999999999999999"));
                    TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A = CobolString.SpliceInto(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 19, CobolEdit.Format(DN2, 0, "-999999999999999999"));
                    __Dispatch(5, 5);
                    __pc = 39;
                    break;
                }
                case 39:   // CALL-WRITE-4
                {
                    TEST_RESULTS.PAR_NAME.FromImage(CobolString.Store("CALL-TEST-04", 22));
                    __Dispatch(7, 7);
                    __pc = 40;
                    break;
                }
                case 40:   // CALL-INIT-5
                {
                    DN2 = (long)(CobolNum.Store(0L, 0, _P_3));
                    __pc = 41;
                    break;
                }
                case 41:   // CALL-TEST-5
                {
                    ProgramRegistry.CallProgram("IC102A", "IC101A", new CobolArg[] { new CobolArg(CobolPassMode.Reference, ManagedPointer<long>.OverField(() => DN2, __v => { DN2 = __v; }), 1, 0) }, null);
                    if (DN2 == 5L)
                    {
                        __Dispatch(4, 4);
                        __pc = 43;
                        break;
                    }
                    __pc = 42;
                    break;
                }
                case 42:   // CALL-FAIL-5
                {
                    TEST_CORRECT.CORRECT_X._redef_CORRECT_A = CobolString.SpliceInto(TEST_CORRECT.CORRECT_X._redef_CORRECT_A, (int)(0 + 1), 19, CobolEdit.Format(5L, 0, "-999999999999999999"));
                    TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A = CobolString.SpliceInto(TEST_COMPUTED.COMPUTED_X._redef_COMPUTED_A, (int)(0 + 1), 19, CobolEdit.Format(DN2, 0, "-999999999999999999"));
                    __Dispatch(5, 5);
                    __pc = 43;
                    break;
                }
                case 43:   // CALL-WRITE-5
                {
                    TEST_RESULTS.PAR_NAME.FromImage(CobolString.Store("CALL-TEST-05", 22));
                    __Dispatch(7, 7);
                    __pc = 44;
                    break;
                }
                case 44:   // CALL-END-ROUTINE
                {
                    __pc = 45;
                    break;
                }
                case 45:   // CCVS-999999
                {
                    __pc = 1;
                    break;
                }
                default:
                {
                    __pc = __N;
                    break;
                }
            }
            if (__atExit && __pc == __exitPc + 1) return __pc;   // a named THRU exit paragraph fell off its end
        }
        return __pc;
    }
}
internal sealed class _PRG_IC102A : ICobolProgram
{
    private bool __asCalled;   // true during a CALL activation — EXIT PROGRAM is CONTINUE otherwise (ISO §14.9.14 GR2)
    private bool __filesRegistered;   // connectors register once per INSTANCE — a canceled/INITIAL program gets fresh connectors (ISO §14.6.2.3.2)
    internal static readonly NumProfile _P_100002 = new NumProfile { Digits = 1, FractionDigits = 0, Signed = true, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    internal static readonly NumProfile _P_100003 = new NumProfile { Digits = 1, FractionDigits = 0, Signed = true, SignKind = NumericSign.TrailingOverpunch, Truncation = NumericTruncation.DigitCount, StorageLength = 0 };
    private string PRINT_REC = new string(' ', 120);   // PRINT-REC
    private long DN2 = 0L;   // DN2
    private ManagedPointer<long> __lnkp0 = ManagedPointer<long>.Cell(0L);   // LINKAGE formal #1 — the caller-storage carrier (ISO §13.7.1; design D1)

    public void Call(CobolArg[] __args, ManagedPointer? __ret)
    {
        __lnkp0 = CobolArgAdapt.Num(__args, 0, _P_100003, 0);
        __asCalled = true;
        try { __Activate(); } finally { __asCalled = false; }
    }
    void ICobolProgram.Activate() => __Activate();
    public void CloseFiles()
    {
        CobolFile.Close("IC102A::PRINT-FILE");
    }


    private const int __N = 2;   // paragraph count

    public void __Activate()
    {
        if (!__filesRegistered)
        {
            __filesRegistered = true;
            CobolFile.Register("IC102A::PRINT-FILE", "IC101A", 120, false, false);
        }
        try { __Dispatch(0, -1); } catch (ProgramReturn) { }   // GOBACK / called-program EXIT PROGRAM returns to the activator here (ISO §14.9.18 GR2/GR3; §14.9.14 GR3)
    }

    private int __Dispatch(int __startPc, int __exitPc)
    {
        int __pc = __startPc;
        while ((uint)__pc < (uint)__N)
        {
            bool __atExit = __pc == __exitPc;   // captured before the body overwrites __pc
            switch (__pc)
            {
                case 0:   // CALL-TEST-001
                {
                    DN2 = (long)(CobolNum.Store(((Int128)(DN2) + (1L)), 0, _P_100002, CobolRounding.Truncation));
                    __lnkp0.Value = (long)(CobolNum.Store(DN2, 0, _P_100003));
                    __pc = 1;
                    break;
                }
                case 1:   // CALL-EXIT-001
                {
                    if (__asCalled) throw new ProgramReturn();   // ISO §14.9.14 GR2: CONTINUE in a non-called program; GR3: return in a called one
                    __pc = 2;
                    break;
                }
                default:
                {
                    __pc = __N;
                    break;
                }
            }
            if (__atExit && __pc == __exitPc + 1) return __pc;   // a named THRU exit paragraph fell off its end
        }
        return __pc;
    }
}
public static class __CobolModule
{
    public static void Register()
    {
        ProgramRegistry.Register("IC101A", "IC101A", null, false, false, false, static __o => new _PRG_IC101A());
        ProgramRegistry.Register("IC102A", "IC102A", null, false, false, false, static __o => new _PRG_IC102A());
    }
}

internal static class Program
{
    private static void Main()
    {
        ProgramRegistry.Reset();
        CobolFile.Init();
        __CobolModule.Register();
        try { ProgramRegistry.RunMain("IC101A"); }
        catch (StopRun) { }
        finally { CobolFile.CloseAll(); }   // run-unit termination implicit CLOSE (ISO §14.6.11)
    }
}
