// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using System;
using System.Collections.Generic;

namespace CobolSharp.Runtime;

/// <summary>
/// Runtime support for the COBOL Report Writer Control System (RWCS), ISO 1989 §14.9. INITIATE/GENERATE/
/// TERMINATE maintain a per-report LINE-COUNTER and PAGE-COUNTER, compose each DETAIL line in a line buffer
/// (SOURCE fields placed by COLUMN from emitted code), and present it through the report's file via
/// <see cref="FileRuntime.WriteAdvancing"/>. The RWCS auto-presents the PAGE HEADING at each page start
/// (the first GENERATE and after every page advance) and the PAGE FOOTING at page overflow, positioning the
/// first body group of a page at FIRST DETAIL (ISO §13.18.35.4.5b.3 / §13.18.39).
///
/// Page-group (heading/footing) fields whose value is a VALUE literal or SOURCE LINE-COUNTER/PAGE-COUNTER
/// are composed by the runtime from a registered field plan; page groups sourcing program data are a later
/// increment.
/// </summary>
public static class ReportWriterRuntime
{
    /// <summary>A field of a page heading/footing group the runtime composes itself: a VALUE literal
    /// (Kind 0) or SOURCE LINE-COUNTER (Kind 1) / PAGE-COUNTER (Kind 2).</summary>
    private sealed class FieldPlan
    {
        public int Column;
        public int Width;
        public int Kind;       // 0 = literal, 1 = LINE-COUNTER, 2 = PAGE-COUNTER, 3 = data SOURCE, 4 = SUM counter
        public string Literal = "";
        // Kind 3 (data SOURCE): the live storage location, read at presentation time.
        public byte[]? SrcArea;
        public int SrcOffset;
        public int SrcSize;
        // Kind 4 (SUM counter): the id of the accumulator (ReportContext.Sums) whose value is printed here.
        public string CounterId = "";
    }

    // Auto-presented group slots — the RWCS presents these itself (page boundaries / report start-end / control
    // breaks), composing each from a registered FieldPlan, as opposed to body (DETAIL) groups GENERATEd by user
    // code. PAGE/REPORT HEADING/FOOTING are fixed slots 0-3; CONTROL HEADING/FOOTING at control level L (0 = most
    // major) occupy slots 4+2L and 5+2L.
    private const int SlotPageHeading = 0;
    private const int SlotPageFooting = 1;
    private const int SlotReportHeading = 2;
    private const int SlotReportFooting = 3;
    private static int ControlHeadingSlot(int level) => 4 + level * 2;
    private static int ControlFootingSlot(int level) => 5 + level * 2;

    /// <summary>An auto-presented group: the LINE it occupies and its runtime-composed field plan.</summary>
    private sealed class AutoGroupPlan
    {
        public int Line;
        public List<FieldPlan> Fields = [];
    }

    /// <summary>One CONTROL data item (or FINAL) of the control hierarchy (ISO §13.18.16), with the saved prior
    /// value used to detect a control break between GENERATEs.</summary>
    private sealed class ControlInfo
    {
        public bool IsFinal;
        public byte[]? Area;     // the control item's storage (null for FINAL)
        public int Offset;
        public int Size;
        public byte[]? Prior;    // value at the previous GENERATE (null until the first GENERATE)
    }

    /// <summary>A SUM accumulator (ISO §13.18.54): the running total plus the DISPLAY-numeric addend it sums
    /// (read from its storage at each detail GENERATE).</summary>
    private sealed class SumInfo
    {
        public decimal Value;
        public byte[]? Area;
        public int Offset;
        public int Size;
        public int Scale;
    }

    private sealed class ReportContext
    {
        public string FileName = "";
        public byte[] Line = Array.Empty<byte>();
        public int LineCounter;
        public int PageCounter;
        public int LastDetail;
        public int FirstDetail;
        public bool Started;                 // a body group has been GENERATEd (chronologically first done)
        public bool ReportHeadingPresented;  // REPORT HEADING is presented exactly once, at the first GENERATE
        // Auto-presented groups keyed by slot (see Slot* / ControlHeadingSlot / ControlFootingSlot).
        public Dictionary<int, AutoGroupPlan> Groups = new();
        // CONTROL hierarchy, major → minor (index 0 most major); FINAL, if present, is index 0.
        public List<ControlInfo> Controls = new();
        // SUM accumulators keyed by counter id (ISO §13.18.54).
        public Dictionary<string, SumInfo> Sums = new();
    }

    private static readonly Dictionary<string, ReportContext> _reports =
        new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Reset all report state (called from FileRuntime.Init at run-unit start).</summary>
    public static void Reset() => _reports.Clear();

    /// <summary>
    /// INITIATE report-name (§14.9.21): begin report processing. Resets PAGE-COUNTER to 1 and LINE-COUNTER
    /// to 0 and allocates a space-filled line buffer. The report's file must already be OPEN OUTPUT.
    /// </summary>
    public static void InitiateReport(string reportName, string fileName, int lineWidth,
        int pageLimit, int lastDetail, int firstDetail)
    {
        if (lineWidth < 1) lineWidth = 132;
        var line = new byte[lineWidth];
        for (int i = 0; i < line.Length; i++) line[i] = (byte)' ';
        _reports[reportName] = new ReportContext
        {
            FileName = fileName,
            Line = line,
            LineCounter = 0,
            PageCounter = 1,
            LastDetail = lastDetail > 0 ? lastDetail : (pageLimit > 0 ? pageLimit : int.MaxValue),
            FirstDetail = firstDetail > 0 ? firstDetail : 1,
            Started = false,
        };
    }

    /// <summary>Register the LINE of an auto-presented group (PAGE/REPORT/CONTROL HEADING/FOOTING — see Slot*).</summary>
    public static void RegisterAutoGroup(string reportName, int slot, int lineValue)
    {
        if (!_reports.TryGetValue(reportName, out var ctx)) return;
        ctx.Groups[slot] = new AutoGroupPlan { Line = lineValue };
    }

    /// <summary>Register one runtime-composed field of an auto-presented group (see <see cref="FieldPlan"/>).</summary>
    public static void RegisterAutoField(string reportName, int slot, int column, int width, int kind, string literal)
    {
        if (!_reports.TryGetValue(reportName, out var ctx) || !ctx.Groups.TryGetValue(slot, out var plan)) return;
        plan.Fields.Add(new FieldPlan { Column = column, Width = width, Kind = kind, Literal = literal ?? "" });
    }

    /// <summary>Register a data-SOURCE field of an auto-presented group: the runtime keeps the live storage
    /// location and reads its bytes when it presents the group (ISO §13.18.53).</summary>
    public static void RegisterAutoDataField(string reportName, int slot, int column, int width,
        byte[] area, int offset, int size)
    {
        if (!_reports.TryGetValue(reportName, out var ctx) || !ctx.Groups.TryGetValue(slot, out var plan)) return;
        plan.Fields.Add(new FieldPlan
        {
            Column = column, Width = width, Kind = 3,
            SrcArea = area, SrcOffset = offset, SrcSize = size,
        });
    }

    /// <summary>Register a CONTROL item (or FINAL) of the control hierarchy, in major→minor order. Its live
    /// storage location is read each GENERATE to detect a control break (ISO §13.18.16).</summary>
    public static void RegisterControl(string reportName, bool isFinal, byte[] area, int offset, int size)
    {
        if (!_reports.TryGetValue(reportName, out var ctx)) return;
        ctx.Controls.Add(new ControlInfo { IsFinal = isFinal, Area = isFinal ? null : area, Offset = offset, Size = size });
    }

    /// <summary>Register a SUM accumulator and its DISPLAY-numeric addend storage (ISO §13.18.54): the counter is
    /// incremented by the addend at each detail GENERATE and printed by a kind-4 SUM field.</summary>
    public static void RegisterSum(string reportName, string counterId, byte[] area, int offset, int size, int scale)
    {
        if (!_reports.TryGetValue(reportName, out var ctx)) return;
        ctx.Sums[counterId] = new SumInfo { Area = area, Offset = offset, Size = size, Scale = scale, Value = 0m };
    }

    /// <summary>Register a SUM-counter print field (kind 4) on an auto-presented group: it prints the running
    /// total of the accumulator named <paramref name="counterId"/> when the group is presented.</summary>
    public static void RegisterAutoSumField(string reportName, int slot, int column, int width, string counterId)
    {
        if (!_reports.TryGetValue(reportName, out var ctx) || !ctx.Groups.TryGetValue(slot, out var plan)) return;
        plan.Fields.Add(new FieldPlan { Column = column, Width = width, Kind = 4, CounterId = counterId });
    }

    /// <summary>Clear the report line buffer to spaces before a group's SOURCE fields are placed.</summary>
    public static void BeginLine(string reportName)
    {
        if (_reports.TryGetValue(reportName, out var ctx))
            for (int i = 0; i < ctx.Line.Length; i++) ctx.Line[i] = (byte)' ';
    }

    /// <summary>
    /// Place a SOURCE field's bytes into the line buffer at COLUMN (1-based), left-justified and truncated
    /// to the report field's PIC width and the buffer extent (an alphanumeric move; the buffer is
    /// pre-filled with spaces by <see cref="BeginLine"/>, providing right padding).
    /// </summary>
    public static void PlaceField(string reportName, int column, int fieldWidth, byte[] src, int srcOffset, int srcLen)
    {
        if (!_reports.TryGetValue(reportName, out var ctx)) return;
        Place(ctx.Line, column, fieldWidth, src, srcOffset, srcLen);
    }

    private static void Place(byte[] dstBuf, int column, int fieldWidth, byte[] src, int srcOffset, int srcLen)
    {
        int dst = column >= 1 ? column - 1 : 0;
        int n = srcLen;
        if (fieldWidth > 0 && n > fieldWidth) n = fieldWidth;
        if (n > dstBuf.Length - dst) n = dstBuf.Length - dst;
        if (n > 0) Array.Copy(src, srcOffset, dstBuf, dst, n);
    }

    /// <summary>Place a constant VALUE literal into the active line buffer at COLUMN (a body-group field whose
    /// value is a VALUE clause rather than a SOURCE — ISO §13.18.63), left-justified, truncated to the field
    /// width. The buffer is pre-filled with spaces by <see cref="BeginLine"/>.</summary>
    public static void PlaceLiteralField(string reportName, int column, int fieldWidth, string text)
    {
        if (!_reports.TryGetValue(reportName, out var ctx)) return;
        var bytes = System.Text.Encoding.ASCII.GetBytes(text ?? "");
        Place(ctx.Line, column, fieldWidth, bytes, 0, bytes.Length);
    }

    /// <summary>
    /// GENERATE a DETAIL group's line (§14.9.19). The detail's SOURCE fields are already in the line buffer.
    /// Performs the RWCS page mechanics first: on the chronologically first GENERATE, or after a page
    /// overflow, present the PAGE FOOTING (overflow only) + form-feed + PAGE-COUNTER increment, present the
    /// PAGE HEADING, and position the first body group of the page at FIRST DETAIL; otherwise advance by the
    /// LINE NUMBER value. Then write the detail line and update LINE-COUNTER.
    /// </summary>
    public static void EmitGroup(string reportName, int advance, bool nextPage)
    {
        if (!_reports.TryGetValue(reportName, out var ctx)) return;
        if (advance < 1) advance = 1;

        bool pageStart = false;
        if (!ctx.Started)
        {
            // Chronologically first body group since INITIATE: no page-fit test, no footing (§14.9.16.4 GR4).
            ctx.Started = true;
            // The REPORT HEADING is presented exactly once, before the first PAGE HEADING (§14.9.16.4 GR4a).
            if (!ctx.ReportHeadingPresented)
            {
                PresentAutoGroup(ctx, SlotReportHeading);
                ctx.ReportHeadingPresented = true;
            }
            pageStart = true;
        }
        else if (nextPage || ctx.LineCounter + advance > ctx.LastDetail)
        {
            // Page overflow (§13.18.35.4.4): present the PAGE FOOTING on the current page, advance to a
            // fresh page (form-feed), increment PAGE-COUNTER and reset LINE-COUNTER.
            PresentAutoGroup(ctx, SlotPageFooting);
            FileRuntime.WriteAdvancing(ctx.FileName, Array.Empty<byte>(), 0, 0, -1, isBefore: false);
            ctx.PageCounter++;
            ctx.LineCounter = 0;
            pageStart = true;
        }

        if (pageStart)
        {
            // Present the PAGE HEADING, then position the first body group of the page at FIRST DETAIL
            // (§13.18.35.4.5b.3): LINE-COUNTER is set so this group's relative advance lands on FIRST DETAIL.
            PresentAutoGroup(ctx, SlotPageHeading);
            ctx.LineCounter = ctx.FirstDetail - advance;
            if (ctx.LineCounter < 0) ctx.LineCounter = 0;
        }

        // After RH/PH, drive the control-break logic: CONTROL FOOTINGs for any groups that just ended and
        // CONTROL HEADINGs for the new ones, before this detail line (§14.9.16.4 GR4/GR5).
        ProcessDetailControls(ctx);
        // Then add this detail's SUM addends — after the ended group's CONTROL FOOTING printed the prior total
        // (§13.18.54.4 GR7), so a control footing sums the details that preceded the break.
        AccumulateSums(ctx);

        int newLine = ctx.LineCounter + advance;
        FileRuntime.WriteAdvancing(ctx.FileName, ctx.Line, 0, ctx.Line.Length, advance, isBefore: false);
        ctx.LineCounter = newLine;
    }

    private static void PresentAutoGroup(ReportContext ctx, int slot)
    {
        if (ctx.Groups.TryGetValue(slot, out var plan)) PresentGroupPlan(ctx, plan);
    }

    /// <summary>Present an auto-composed group at its absolute LINE, evaluating each field (literal /
    /// LINE-COUNTER / PAGE-COUNTER / data SOURCE) against the live state at presentation time.</summary>
    private static void PresentGroupPlan(ReportContext ctx, AutoGroupPlan plan)
    {
        var fields = plan.Fields;
        int lineValue = plan.Line;
        if (fields.Count == 0 || lineValue <= 0) return;
        int adv = lineValue - ctx.LineCounter;
        if (adv < 1) adv = 1;
        ctx.LineCounter = lineValue;   // set so SOURCE LINE-COUNTER on this group reflects its own line

        var buf = new byte[ctx.Line.Length];
        for (int i = 0; i < buf.Length; i++) buf[i] = (byte)' ';
        foreach (var f in fields)
        {
            if (f.Kind == 4)
            {
                // SUM counter: print the accumulated total, then reset it (end of group, ISO §13.18.54.4 GR2).
                decimal val = ctx.Sums.TryGetValue(f.CounterId, out var s) ? s.Value : 0m;
                var sumBytes = System.Text.Encoding.ASCII.GetBytes(
                    FormatNumeric((int)Math.Round(val, MidpointRounding.AwayFromZero), f.Width));
                Place(buf, f.Column, f.Width, sumBytes, 0, sumBytes.Length);
                if (s != null) s.Value = 0m;
                continue;
            }
            if (f.Kind == 3 && f.SrcArea != null)
            {
                // Data SOURCE: place the live bytes from the registered storage location.
                Place(buf, f.Column, f.Width, f.SrcArea, f.SrcOffset, f.SrcSize);
                continue;
            }
            string text = f.Kind switch
            {
                1 => FormatNumeric(ctx.LineCounter, f.Width),
                2 => FormatNumeric(ctx.PageCounter, f.Width),
                _ => f.Literal,
            };
            var bytes = System.Text.Encoding.ASCII.GetBytes(text);
            Place(buf, f.Column, f.Width, bytes, 0, bytes.Length);
        }
        FileRuntime.WriteAdvancing(ctx.FileName, buf, 0, buf.Length, adv, isBefore: false);
    }

    /// <summary>At each detail GENERATE (after RH/PH, before the detail), drive the control-break logic. First
    /// detail: snapshot all controls + present CONTROL HEADINGs major→minor. Subsequent: at the most-major
    /// non-FINAL control that changed (break level L), present CONTROL FOOTINGs minor→L (with the ENDING group's
    /// values restored), then CONTROL HEADINGs L→minor (new values), then update the snapshots. ISO §13.18.16.4
    /// / §14.9.16.4 GR5 / §13.18.57.</summary>
    private static void ProcessDetailControls(ReportContext ctx)
    {
        int n = ctx.Controls.Count;
        if (n == 0) return;

        if (ctx.Controls[0].Prior == null)
        {
            for (int i = 0; i < n; i++) ctx.Controls[i].Prior = SnapshotControl(ctx.Controls[i]);
            for (int i = 0; i < n; i++) PresentAutoGroup(ctx, ControlHeadingSlot(i));
            return;
        }

        int breakLevel = -1;
        for (int i = 0; i < n; i++)
        {
            if (ctx.Controls[i].IsFinal) continue; // FINAL never breaks mid-report
            if (!BytesEqual(SnapshotControl(ctx.Controls[i]), ctx.Controls[i].Prior)) { breakLevel = i; break; }
        }
        if (breakLevel < 0) return;

        // Present CONTROL FOOTINGs for the ending groups (minor→break level) with the PRIOR control values
        // restored, then restore current; then CONTROL HEADINGs for the new groups (break level→minor).
        var current = new byte[n][];
        for (int i = 0; i < n; i++) { current[i] = SnapshotControl(ctx.Controls[i]); RestoreControl(ctx.Controls[i], ctx.Controls[i].Prior); }
        for (int i = n - 1; i >= breakLevel; i--) PresentAutoGroup(ctx, ControlFootingSlot(i));
        for (int i = 0; i < n; i++) RestoreControl(ctx.Controls[i], current[i]);
        for (int i = breakLevel; i < n; i++) PresentAutoGroup(ctx, ControlHeadingSlot(i));
        for (int i = 0; i < n; i++) ctx.Controls[i].Prior = SnapshotControl(ctx.Controls[i]);
    }

    /// <summary>At TERMINATE (before the REPORT FOOTING), a final control break: present every CONTROL FOOTING
    /// minor→major with the last group's control values (ISO §13.18.16.4 GR5).</summary>
    private static void ProcessTerminateControls(ReportContext ctx)
    {
        if (ctx.Controls.Count == 0 || ctx.Controls[0].Prior == null) return;
        for (int i = ctx.Controls.Count - 1; i >= 0; i--) PresentAutoGroup(ctx, ControlFootingSlot(i));
    }

    private static byte[] SnapshotControl(ControlInfo c)
    {
        if (c.IsFinal || c.Area == null) return Array.Empty<byte>();
        var b = new byte[c.Size];
        Array.Copy(c.Area, c.Offset, b, 0, c.Size);
        return b;
    }

    private static void RestoreControl(ControlInfo c, byte[]? value)
    {
        if (c.IsFinal || c.Area == null || value == null) return;
        Array.Copy(value, 0, c.Area, c.Offset, Math.Min(value.Length, c.Size));
    }

    private static bool BytesEqual(byte[] a, byte[]? b)
    {
        if (b == null || a.Length != b.Length) return false;
        for (int i = 0; i < a.Length; i++) if (a[i] != b[i]) return false;
        return true;
    }

    /// <summary>Add each SUM counter's addend (its DISPLAY-numeric storage, decoded) into its accumulator —
    /// once per detail GENERATE, after the control-break processing (ISO §13.18.54.4 GR7).</summary>
    private static void AccumulateSums(ReportContext ctx)
    {
        foreach (var s in ctx.Sums.Values)
            if (s.Area != null)
                s.Value += DecodeDisplayNumeric(s.Area, s.Offset, s.Size, s.Scale);
    }

    /// <summary>Decode an unsigned DISPLAY numeric (PIC 9 / 9V9) at a storage location into a decimal, using the
    /// low nibble of each byte (ASCII digit / sign overpunch). COMP/COMP-3 SUM addends are a later increment.</summary>
    private static decimal DecodeDisplayNumeric(byte[] area, int offset, int size, int scale)
    {
        long v = 0;
        for (int i = 0; i < size && offset + i < area.Length; i++)
            v = v * 10 + (area[offset + i] & 0x0F);
        if (scale <= 0) return v;
        decimal d = v;
        for (int i = 0; i < scale; i++) d /= 10m;
        return d;
    }

    /// <summary>Format a counter value into a PIC 9(width) image (zero-padded, rightmost digits).</summary>
    private static string FormatNumeric(int value, int width)
    {
        if (width <= 0) return value.ToString();
        string s = value.ToString();
        if (s.Length > width) return s.Substring(s.Length - width);
        return s.PadLeft(width, '0');
    }

    /// <summary>TERMINATE report-name (§14.9.62): present the REPORT FOOTING (after all control footings — a
    /// later increment adds those), then end report processing for this report.</summary>
    public static void TerminateReport(string reportName)
    {
        if (_reports.TryGetValue(reportName, out var ctx))
        {
            ProcessTerminateControls(ctx);   // final control break: all CONTROL FOOTINGs, minor→major
            PresentAutoGroup(ctx, SlotReportFooting);
            _reports.Remove(reportName);
        }
    }

    /// <summary>LINE-COUNTER special register read (§8.4.3.15): current line within the page.</summary>
    public static decimal GetLineCounter(string reportName)
        => _reports.TryGetValue(reportName, out var ctx) ? ctx.LineCounter : 0m;

    /// <summary>PAGE-COUNTER special register read (§8.4.3.15): current page number (1-based).</summary>
    public static decimal GetPageCounter(string reportName)
        => _reports.TryGetValue(reportName, out var ctx) ? ctx.PageCounter : 0m;
}
