// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using Antlr4.Runtime.Tree;
using CobolSharp.Compiler.Generated;
using Microsoft.CodeAnalysis.CSharp;

namespace CobolNet.CodeGen;

using Core = CobolParserCore;

/// <summary>
/// Translates a COBOL parse tree into C# source text. This is the heart of COBOL.NET: COBOL constructs map to
/// idiomatic, typed-native C# — there is no byte-array storage substrate.
/// </summary>
/// <remarks>
/// <para><b>Status:</b> bring-up slice 1 — IDENTIFICATION + PROCEDURE DIVISION with <c>DISPLAY</c> of literals.
/// The data division, the full statement set, and the control-flow engine are added in subsequent slices
/// (tasks G2–G4). The emitter grows against the NIST corpus as the conformance oracle.</para>
/// <para>The generated program is a single <c>Program</c> class whose <c>Main</c> runs the procedure division.
/// As features land this becomes: a class per COBOL program, a record struct per group, native fields per
/// elementary item, and methods per paragraph/section under a control-flow dispatcher.</para>
/// </remarks>
public sealed class CSharpEmitter
{
    /// <summary>
    /// Emit C# source for the first program unit in <paramref name="tree"/>. (Multiple/nested programs and
    /// classes are a later slice.)
    /// </summary>
    public string Emit(Core.CompilationUnitContext tree)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated>");
        w.Line("//   Generated by COBOL.NET — do not edit. A COBOL program compiled to typed-native C#.");
        w.Line("// </auto-generated>");
        w.Line("#nullable enable");
        w.Line();

        Core.ProgramUnitContext? program = tree.compilationGroup()
            .SelectMany(g => g.programUnit())
            .FirstOrDefault();

        using (w.Block("internal static class Program"))
        using (w.Block("private static void Main()"))
        {
            if (program?.procedureDivision() is { } pd)
                EmitProcedureDivision(pd, w);
        }

        return w.ToString();
    }

    /// <summary>Emit the statements of every paragraph/section of the procedure division, in source order.</summary>
    private void EmitProcedureDivision(Core.ProcedureDivisionContext pd, CodeWriter w)
    {
        foreach (var unit in pd.procedureUnit())
        {
            if (unit.paragraphDefinition() is { } para)
                EmitParagraph(para, w);
            else if (unit.sectionDefinition() is { } section)
                foreach (var p in section.paragraphDefinition())
                    EmitParagraph(p, w);
        }
    }

    /// <summary>Emit the statements of one paragraph (a flat sequence for this slice — no PERFORM/GO TO yet).</summary>
    private void EmitParagraph(Core.ParagraphDefinitionContext para, CodeWriter w)
    {
        foreach (var sentence in para.sentence())
            foreach (var statement in sentence.statement())
                EmitStatement(statement, w);
    }

    /// <summary>Emit one statement. Slice 1 handles <c>DISPLAY</c>; unhandled verbs emit a TODO marker comment.</summary>
    private void EmitStatement(Core.StatementContext statement, CodeWriter w)
    {
        if (statement.displayStatement() is { } display)
            EmitDisplay(display, w);
        else if (statement.stopStatement() is not null || statement.gobackStatement() is not null)
            // STOP RUN / GOBACK terminate the run unit. In the slice-1 single-method shape, returning from Main
            // is correct; the control-flow engine (task G4) refines this for sub-programs and nested PERFORMs.
            w.Line("return;");
        else
            w.Line($"// TODO(COBOL.NET): unsupported statement '{FirstToken(statement)}'");
    }

    /// <summary>
    /// Emit a <c>DISPLAY</c>: concatenate the operands' display images and write the line. <c>WITH NO ADVANCING</c>
    /// suppresses the trailing newline (<c>Console.Write</c> vs <c>Console.WriteLine</c>).
    /// </summary>
    private void EmitDisplay(Core.DisplayStatementContext display, CodeWriter w)
    {
        // Operands (literals / data references) appear interleaved in source order, so walk the children in order.
        var parts = new List<string>();
        foreach (IParseTree child in Children(display))
        {
            switch (child)
            {
                case Core.LiteralContext lit:
                    parts.Add(RenderLiteral(lit));
                    break;
                case Core.DataReferenceContext dref:
                    // Data references need the data model (slice G2); emit a placeholder for now.
                    parts.Add(SymbolDisplay.FormatLiteral($"<{dref.GetText()}>", quote: true));
                    break;
            }
        }

        string image = parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
        bool noAdvancing = display.displayNoAdvancing() is not null;
        w.Line(noAdvancing ? $"System.Console.Write({image});" : $"System.Console.WriteLine({image});");
    }

    /// <summary>Render a COBOL literal as a C# <see cref="string"/> expression (its DISPLAY image).</summary>
    private static string RenderLiteral(Core.LiteralContext lit)
    {
        if (lit.nonNumericLiteral()?.STRINGLIT() is { } strlit)
            return SymbolDisplay.FormatLiteral(DecodeCobolString(strlit.GetText()), quote: true);

        // Numeric (and other) literals: emit their source text as a string for now (DISPLAY images them as text).
        return SymbolDisplay.FormatLiteral(lit.GetText(), quote: true);
    }

    /// <summary>
    /// Decode a COBOL <c>STRINGLIT</c> token (<c>"…"</c> with doubled <c>""</c> escapes) to its character value.
    /// </summary>
    private static string DecodeCobolString(string raw) =>
        raw.Length >= 2 && raw[0] == '"' && raw[^1] == '"'
            ? raw[1..^1].Replace("\"\"", "\"")
            : raw;

    /// <summary>The children of a parse-tree node, in source order.</summary>
    private static IEnumerable<IParseTree> Children(IParseTree node)
    {
        for (int i = 0; i < node.ChildCount; i++)
            yield return node.GetChild(i);
    }

    /// <summary>The first token text of a node (for diagnostic TODO markers).</summary>
    private static string FirstToken(IParseTree node) =>
        node.ChildCount > 0 ? node.GetChild(0).GetText() : node.GetText();
}
