// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using Antlr4.Runtime.Tree;
using CobolNet.Binding;
using CobolSharp.Compiler.Generated;
using Microsoft.CodeAnalysis.CSharp;

namespace CobolNet.CodeGen;

using Core = CobolParserCore;

/// <summary>
/// Translates a COBOL parse tree into typed-native C# source. The heart of COBOL.NET: COBOL data is .NET data
/// (native fields, no byte substrate) and COBOL verbs are operations on those typed values, calling the clean
/// <c>CobolNum</c>/<c>CobolString</c> runtime substrates for COBOL-correct semantics.
/// </summary>
/// <remarks>
/// <para><b>Status — bring-up slices G2/G3a:</b> WORKING-STORAGE elementary items (alphanumeric→<c>string</c>,
/// numeric→<c>long</c>/<c>decimal</c>) with VALUE init; <c>DISPLAY</c>, <c>MOVE</c>, <c>ADD</c>, <c>SUBTRACT</c>,
/// <c>STOP RUN</c>/<c>GOBACK</c>. Groups/tables (G2 cont.), the rest of the verb set (G3), and the control-flow
/// engine (G4) follow. Unsupported constructs emit a <c>// TODO</c> marker rather than failing, so a program
/// compiles and its supported parts run while coverage grows against the NIST corpus.</para>
/// </remarks>
public sealed class CSharpEmitter
{
    private DataBinder _data = new();

    /// <summary>Emit C# source for the first program unit in <paramref name="tree"/>.</summary>
    public string Emit(Core.CompilationUnitContext tree)
    {
        Core.ProgramUnitContext? program = tree.compilationGroup().SelectMany(g => g.programUnit()).FirstOrDefault();

        _data = new DataBinder();
        if (program is not null) _data.Bind(program);

        var w = new CodeWriter();
        w.Line("// <auto-generated>");
        w.Line("//   Generated by COBOL.NET — do not edit. A COBOL program compiled to typed-native C#.");
        w.Line("// </auto-generated>");
        w.Line("#nullable enable");
        w.Line("using CobolNet.Runtime;          // CobolNum / CobolString typed-native runtime substrates");
        w.Line();

        using (w.Block("internal static class Program"))
        {
            EmitWorkingStorage(w);
            w.Line();
            using (w.Block("private static void Main()"))
                if (program?.procedureDivision() is { } pd)
                    EmitProcedureDivision(pd, w);
        }

        return w.ToString();
    }

    // ── DATA DIVISION → fields ───────────────────────────────────────────────────────────────────────────

    /// <summary>Emit a static field per WORKING-STORAGE elementary item, initialized to its VALUE (or COBOL default).</summary>
    private void EmitWorkingStorage(CodeWriter w)
    {
        foreach (var item in _data.Roots)
            EmitFieldRecursive(item, w);
    }

    /// <summary>Emit fields for an item and its descendants. (Groups are flattened to their elementary leaves in
    /// this slice; the record-struct representation lands with G2's group support.)</summary>
    private void EmitFieldRecursive(DataItem item, CodeWriter w)
    {
        if (item.IsElementary)
        {
            string init = InitializerFor(item);
            string comment = item.CobolName is { } n ? $"   // {n} {item.Pic!.Category}" : "";
            w.Line($"private static {item.Pic!.ClrType} {item.CsName} = {init};{comment}");
        }
        foreach (var child in item.Children)
            EmitFieldRecursive(child, w);
    }

    /// <summary>The C# initializer expression for an elementary item, from its VALUE clause or the COBOL default.</summary>
    private static string InitializerFor(DataItem item)
    {
        var pic = item.Pic!;
        if (item.RawValue is not { } raw)
            return pic.DefaultInitializer;

        return pic.Category switch
        {
            PicCategory.Alphanumeric or PicCategory.NumericEdited =>
                $"CobolString.Store({CsStringLiteral(DecodeCobolString(raw))}, {pic.Length})",
            PicCategory.Numeric => RenderNumericLiteral(raw, pic.IsDecimal),
            _ => pic.DefaultInitializer,
        };
    }

    // ── PROCEDURE DIVISION → statements ──────────────────────────────────────────────────────────────────

    /// <summary>Emit the statements of every paragraph/section, in source order (flat — control flow is task G4).</summary>
    private void EmitProcedureDivision(Core.ProcedureDivisionContext pd, CodeWriter w)
    {
        foreach (var unit in pd.procedureUnit())
        {
            if (unit.paragraphDefinition() is { } para)
                EmitParagraph(para, w);
            else if (unit.sectionDefinition() is { } section)
                foreach (var p in section.paragraphDefinition())
                    EmitParagraph(p, w);
        }
    }

    private void EmitParagraph(Core.ParagraphDefinitionContext para, CodeWriter w)
    {
        foreach (var sentence in para.sentence())
            foreach (var statement in sentence.statement())
                EmitStatement(statement, w);
    }

    /// <summary>Emit one statement. Unsupported verbs emit a TODO marker (compile, don't crash).</summary>
    private void EmitStatement(Core.StatementContext s, CodeWriter w)
    {
        switch (s)
        {
            case var _ when s.displayStatement() is { } d: EmitDisplay(d, w); break;
            case var _ when s.moveStatement() is { } m: EmitMove(m, w); break;
            case var _ when s.addStatement() is { } a: EmitAdd(a, w); break;
            case var _ when s.subtractStatement() is { } sub: EmitSubtract(sub, w); break;
            case var _ when s.computeStatement() is { } c: EmitCompute(c, w); break;
            case var _ when s.stopStatement() is not null || s.gobackStatement() is not null: w.Line("return;"); break;
            default: w.Line($"// TODO(COBOL.NET): unsupported statement '{FirstToken(s)}'"); break;
        }
    }

    /// <summary>Emit a <c>DISPLAY</c>: concatenate operand display images and write the line.</summary>
    private void EmitDisplay(Core.DisplayStatementContext display, CodeWriter w)
    {
        var parts = new List<string>();
        foreach (IParseTree child in Children(display))
        {
            switch (child)
            {
                case Core.LiteralContext lit: parts.Add(RenderLiteralAsString(lit)); break;
                case Core.DataReferenceContext dref: parts.Add(ReadAsString(dref)); break;
            }
        }

        string image = parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
        bool noAdvancing = display.displayNoAdvancing() is not null;
        w.Line(noAdvancing ? $"System.Console.Write({image});" : $"System.Console.WriteLine({image});");
    }

    /// <summary>Emit a <c>MOVE</c> (single sending operand → one or more targets). CORR is a later slice.</summary>
    private void EmitMove(Core.MoveStatementContext move, CodeWriter w)
    {
        var send = move.moveSendingOperand();
        var phrase = move.moveReceivingPhrase();
        if (send is null || phrase?.dataReferenceList() is not { } targets)
        {
            w.Line("// TODO(COBOL.NET): MOVE CORRESPONDING / unsupported MOVE form");
            return;
        }

        foreach (var target in targets.dataReference())
            if (Resolve(target) is { } t)
                w.Line($"{t.CsName} = {ConvertToTarget(send, t)};");
    }

    /// <summary>Emit <c>ADD … TO …</c> and <c>ADD … GIVING …</c> (numeric). ROUNDED / SIZE ERROR / CORR: later.</summary>
    private void EmitAdd(Core.AddStatementContext add, CodeWriter w)
    {
        if (add.addOperandList() is not { } operands) { w.Line("// TODO(COBOL.NET): ADD CORRESPONDING"); return; }
        string sum = string.Join(" + ", operands.addOperand().Select(RenderArithOperand));

        if (add.addGivingPhrase() is { } giving)
            foreach (var dref in DataRefs(giving))
                EmitArithAssign(dref, sum, w);                       // GIVING t = a + b + …
        else if (add.addToPhrase() is { } to)
            foreach (var dref in DataRefs(to))
                if (Resolve(dref) is { } t)
                    EmitArithAssign(dref, $"{t.CsName} + {sum}", w); // TO t = t + (a + b + …)
    }

    /// <summary>Emit <c>SUBTRACT … FROM …</c> and <c>SUBTRACT … FROM … GIVING …</c> (numeric).</summary>
    private void EmitSubtract(Core.SubtractStatementContext sub, CodeWriter w)
    {
        if (sub.subtractOperandList() is not { } operands) { w.Line("// TODO(COBOL.NET): SUBTRACT CORRESPONDING"); return; }
        string minuends = string.Join(" + ", operands.subtractOperand().Select(RenderArithOperand));

        if (sub.subtractGivingPhrase() is { } giving && sub.subtractFromPhrase()?.subtractFromOperand() is { } from)
        {
            string fromExpr = string.Join(" + ", DataRefs(from).Select(d => Resolve(d)?.CsName ?? d.GetText()));
            foreach (var dref in DataRefs(giving))
                EmitArithAssign(dref, $"{fromExpr} - ({minuends})", w);      // GIVING t = from - (a+b+…)
        }
        else if (sub.subtractFromPhrase()?.subtractFromOperand() is { } fromTargets)
            foreach (var dref in DataRefs(fromTargets))
                if (Resolve(dref) is { } t)
                    EmitArithAssign(dref, $"{t.CsName} - ({minuends})", w);  // FROM t = t - (a+b+…)
    }

    /// <summary>
    /// Emit <c>COMPUTE t [t2 …] = arithmetic-expression</c>. The expression is evaluated in <see cref="decimal"/>
    /// (every operand cast to decimal so division is COBOL-real, not C# integer division), then stored into each
    /// target with its storage type's truncation. ROUNDED / SIZE ERROR land with the full <c>CobolNum</c> store (G3).
    /// </summary>
    private void EmitCompute(Core.ComputeStatementContext compute, CodeWriter w)
    {
        if (compute.arithmeticExpression() is not { } expr) { w.Line("// TODO(COBOL.NET): COMPUTE without expression"); return; }
        string value = RenderArith(expr);
        foreach (var store in compute.computeStore())
            if (store.dataReference() is { } target)
                EmitArithAssign(target, value, w);
    }

    /// <summary>
    /// Translate a COBOL arithmetic expression to an equivalent C# <see cref="decimal"/> expression, preserving
    /// COBOL operator precedence (the grammar already encodes additive &gt; multiplicative &gt; power). Every leaf
    /// operand is cast to <c>decimal</c> so the whole evaluation is decimal (COBOL division is real division).
    /// </summary>
    private string RenderArith(IParseTree node)
    {
        switch (node)
        {
            case Core.ArithmeticExpressionContext a:
                return RenderArith(a.GetChild(0));

            // additive / multiplicative: operands interleaved with addOp/mulOp rule nodes, in order.
            case Core.AdditiveExpressionContext or Core.MultiplicativeExpressionContext:
            {
                var sb = new System.Text.StringBuilder();
                foreach (var child in Children(node))
                    sb.Append(child is Core.AddOpContext or Core.MulOpContext ? $" {child.GetText()} " : RenderArith(child));
                return sb.ToString();
            }

            // power: a ** b ** c → left-folded Math.Pow (in double, re-cast to decimal).
            case Core.PowerExpressionContext p:
            {
                var bases = p.unaryExpression();
                string acc = RenderArith(bases[0]);
                for (int i = 1; i < bases.Length; i++)
                    acc = $"(decimal)System.Math.Pow((double)({acc}), (double)({RenderArith(bases[i])}))";
                return acc;
            }

            case Core.UnaryExpressionContext u:
                return u.primaryExpression() is { } prim
                    ? RenderArith(prim)
                    : $"{u.addOp().GetText()}{RenderArith(u.unaryExpression())}";

            case Core.PrimaryExpressionContext pe:
                if (pe.numericLiteral() is { } num) return RenderNumericLiteral(num.GetText(), asDecimal: true);
                if (pe.ZERO_ARITH() is not null) return "0m";
                if (pe.dataReference() is { } dref) return $"(decimal){(Resolve(dref)?.CsName ?? "0")}";
                if (pe.arithmeticExpression() is { } paren) return $"({RenderArith(paren)})";
                return "0m /* TODO(COBOL.NET): function-call operand */";

            default:
                return RenderArith(node.GetChild(0)); // single pass-through wrapper levels
        }
    }

    /// <summary>Assign an arithmetic result to a numeric target, with the right numeric C# type.</summary>
    private void EmitArithAssign(Core.DataReferenceContext target, string expr, CodeWriter w)
    {
        if (Resolve(target) is not { Pic: { Category: PicCategory.Numeric } pic } t)
        {
            w.Line($"// TODO(COBOL.NET): arithmetic target '{target.GetText()}' is not a simple numeric item");
            return;
        }
        // Cast the result to the target's storage type (truncation/ROUNDED/SIZE-ERROR via CobolNum lands with G3).
        string cast = pic.IsDecimal ? "(decimal)" : "(long)";
        w.Line($"{t.CsName} = {cast}({expr});");
    }

    // ── Operand rendering ────────────────────────────────────────────────────────────────────────────────

    /// <summary>Render an operand (data reference or literal) as a C# numeric expression.</summary>
    private string RenderArithOperand(IParseTree operand) => operand switch
    {
        Core.AddOperandContext a when a.literal() is { } l => RenderNumericLiteral(l.GetText(), IsDecimalLiteral(l.GetText())),
        Core.AddOperandContext a when a.dataReference() is { } d => Resolve(d)?.CsName ?? d.GetText(),
        Core.SubtractOperandContext sub when sub.literal() is { } l => RenderNumericLiteral(l.GetText(), IsDecimalLiteral(l.GetText())),
        Core.SubtractOperandContext sub when sub.dataReference() is { } d => Resolve(d)?.CsName ?? d.GetText(),
        _ => "0",
    };

    /// <summary>Convert a MOVE sending operand to the C# expression assigned into <paramref name="target"/>.</summary>
    private string ConvertToTarget(Core.MoveSendingOperandContext send, DataItem target)
    {
        var pic = target.Pic!;
        return pic.Category switch
        {
            PicCategory.Alphanumeric or PicCategory.NumericEdited =>
                $"CobolString.Store({SendAsString(send)}, {pic.Length})",
            PicCategory.Numeric =>
                pic.IsDecimal ? $"(decimal)({SendAsNumber(send)})" : $"(long)({SendAsNumber(send)})",
            _ => "default",
        };
    }

    /// <summary>A MOVE sending operand rendered as a C# <see cref="string"/> (its display image).</summary>
    private string SendAsString(Core.MoveSendingOperandContext send)
    {
        if (send.literal() is { } lit) return RenderLiteralAsString(lit);
        if (send.dataReference() is { } dref) return ReadAsString(dref);
        return "\"\"";
    }

    /// <summary>A MOVE sending operand rendered as a C# numeric expression.</summary>
    private string SendAsNumber(Core.MoveSendingOperandContext send)
    {
        if (send.literal() is { } lit) return RenderNumericLiteral(lit.GetText(), IsDecimalLiteral(lit.GetText()));
        if (send.dataReference() is { } dref) return Resolve(dref)?.CsName ?? "0";
        return "0";
    }

    /// <summary>Read a data reference as a C# <see cref="string"/> (its DISPLAY image).</summary>
    private string ReadAsString(Core.DataReferenceContext dref)
    {
        if (Resolve(dref) is not { } item) return CsStringLiteral($"<{dref.GetText()}>");
        return item.Pic switch
        {
            { Category: PicCategory.Numeric, IsDecimal: false } p => $"CobolNum.FormatUnsignedDisplay({item.CsName}, {p.Digits})",
            { Category: PicCategory.Numeric } => $"{item.CsName}.ToString()",      // scaled — refine with G3 edited path
            { Category: PicCategory.Alphanumeric or PicCategory.NumericEdited } => item.CsName,
            _ => $"{item.CsName}.ToString()",
        };
    }

    /// <summary>Render a COBOL literal as a C# <see cref="string"/> expression (its display image).</summary>
    private static string RenderLiteralAsString(Core.LiteralContext lit) =>
        lit.nonNumericLiteral()?.STRINGLIT() is { } s
            ? CsStringLiteral(DecodeCobolString(s.GetText()))
            : CsStringLiteral(lit.GetText());

    /// <summary>Render a COBOL numeric literal as a C# numeric literal (<c>long</c> or <c>decimal</c>).</summary>
    private static string RenderNumericLiteral(string text, bool asDecimal)
    {
        string t = text.Trim().TrimStart('+');
        return asDecimal ? $"{t}m" : $"{t}L";
    }

    private static bool IsDecimalLiteral(string text) => text.Contains('.');

    // ── Reference resolution + helpers ───────────────────────────────────────────────────────────────────

    /// <summary>Resolve a (simple, unqualified, unsubscripted) data reference to its bound item.</summary>
    private DataItem? Resolve(Core.DataReferenceContext dref)
    {
        string name = dref.cobolWord()?.GetText() ?? dref.GetText();
        return _data.ByName.GetValueOrDefault(name);
    }

    /// <summary>All <see cref="Core.DataReferenceContext"/> descendants of a node, in source order.</summary>
    private static IEnumerable<Core.DataReferenceContext> DataRefs(IParseTree node)
    {
        for (int i = 0; i < node.ChildCount; i++)
        {
            var child = node.GetChild(i);
            if (child is Core.DataReferenceContext dref) yield return dref;
            else foreach (var inner in DataRefs(child)) yield return inner;
        }
    }

    /// <summary>Decode a COBOL <c>STRINGLIT</c> (<c>"…"</c> with doubled <c>""</c>) to its character value.</summary>
    private static string DecodeCobolString(string raw) =>
        raw.Length >= 2 && raw[0] == '"' && raw[^1] == '"' ? raw[1..^1].Replace("\"\"", "\"") : raw;

    /// <summary>Render a .NET string as a safely-escaped C# string literal.</summary>
    private static string CsStringLiteral(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static IEnumerable<IParseTree> Children(IParseTree node)
    {
        for (int i = 0; i < node.ChildCount; i++) yield return node.GetChild(i);
    }

    private static string FirstToken(IParseTree node) =>
        node.ChildCount > 0 ? node.GetChild(0).GetText() : node.GetText();
}
