# Copyright (c) 2026 Brent Rector. All rights reserved.
# Licensed under the Business Source License 1.1. See LICENSE file in the project root.
#
# gen-constructs.ps1 — generate the construct registry from THE canonical catalogue
# (rearchitecture PHASE 02, P2.5). tests/version-matrix/constructs.json is the SINGLE hand-authored source;
# this script renders it into three committed C# build-outputs, mirroring the gen-reserved-words.ps1 discipline
# (manual regen + committed .g.cs + a drift test — ConstructRegistryDriftTests — asserts they agree; there is no
# MSBuild build hook, so a stale .g.cs is caught by CI, not a silent wrong build).
#
# Input:
#   tests/version-matrix/constructs.json  — 91 rows: id / display / introducedIn / removedIn / obsoleteIn /
#                                           diagnosticCode / citation (+ description / vcr / source / status /
#                                           expectDiagnostic used by the version-matrix tests, not the registry).
# Outputs (ALL committed; ConstructRegistryDriftTests asserts they equal constructs.json):
#   src/Cobol.Net.Editions/ConstructRegistry.g.cs  — the ConstructRegistry.Entries list (a partial).
#   src/Cobol.Net.Editions/Constructs.g.cs         — one `public const string <PascalId> = "<id>";` per row.
#   src/Cobol.Net.Editions/Gating/GateId.cs        — the introduction-gate identity enum (removedIn==null &&
#                                                    introducedIn>85) + the GateId->construct-id map the parser
#                                                    stamps (rearch P2.7 predicate stamping).

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$jsonIn   = Join-Path $repo 'tests/version-matrix/constructs.json'
$regOut   = Join-Path $repo 'src/Cobol.Net.Editions/ConstructRegistry.g.cs'
$idsOut   = Join-Path $repo 'src/Cobol.Net.Editions/Constructs.g.cs'
$gateOut  = Join-Path $repo 'src/Cobol.Net.Editions/Gating/GateId.cs'

function To-Pascal([string]$id) {
    (($id -split '-') | ForEach-Object {
        if ($_.Length -eq 0) { '' } else { $_.Substring(0,1).ToUpper() + $_.Substring(1) }
    }) -join ''
}
function Esc([string]$s) { $s.Replace('\','\\').Replace('"','\"') }
function NullOrInt($v) { if ($null -eq $v) { 'null' } else { [string][int]$v } }

$rows = (Get-Content -Raw -LiteralPath $jsonIn | ConvertFrom-Json).constructs
if ($rows.Count -lt 1) { throw "constructs.json parsed to 0 rows" }

# --- validate: unique ids, unique PascalIds, required fields present ---
$seenId = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
$seenPascal = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($r in $rows) {
    foreach ($f in 'id','display','diagnosticCode','citation','introducedIn') {
        if ($null -eq $r.$f) { throw "row '$($r.id)' is missing required field '$f'" }
    }
    if (-not $seenId.Add($r.id)) { throw "duplicate construct id '$($r.id)'" }
    if (-not $seenPascal.Add((To-Pascal $r.id))) { throw "PascalId collision for '$($r.id)'" }
}

$hdr = @"
// <auto-generated>
// Generated by scripts/gen-constructs.ps1 from tests/version-matrix/constructs.json — DO NOT EDIT; re-run the script.
// tests/version-matrix/constructs.json is THE canonical version-matrix catalogue; ConstructRegistryDriftTests
// asserts this output equals it (a stale file is a CI failure, not a silent wrong build).
// </auto-generated>
"@

# ---- 1. ConstructRegistry.g.cs (the Entries partial) ----
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine($hdr)
[void]$sb.AppendLine('namespace CobolNet.Editions;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('public static partial class ConstructRegistry')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>The in-code rendering of constructs.json (generated). Pending rows (not yet')
[void]$sb.AppendLine('    /// implemented) are REGISTERED — their edition metadata is frozen here.</summary>')
[void]$sb.AppendLine('    public static readonly IReadOnlyList<ConstructDialectStatus> Entries =')
[void]$sb.AppendLine('    [')
foreach ($r in $rows) {
    $line = '        new("{0}", "{1}", {2}, {3}, {4}, "{5}", "{6}"),' -f `
        (Esc $r.id), (Esc $r.display), ([int]$r.introducedIn), (NullOrInt $r.removedIn), (NullOrInt $r.obsoleteIn), `
        (Esc $r.diagnosticCode), (Esc $r.citation)
    [void]$sb.AppendLine($line)
}
[void]$sb.AppendLine('    ];')
[void]$sb.AppendLine('}')
Set-Content -LiteralPath $regOut -Value ($sb.ToString().TrimEnd() + "`n") -NoNewline -Encoding utf8

# ---- 2. Constants.g.cs (compile-checked ids) ----
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine($hdr)
[void]$sb.AppendLine('namespace CobolNet.Editions;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>Compile-checked constructs.json row ids (P2.6): use <c>Constructs.X</c> at every')
[void]$sb.AppendLine('/// <see cref="ConstructRegistry.Check"/> call site so an unregistered id is a COMPILE error.</summary>')
[void]$sb.AppendLine('public static class Constructs')
[void]$sb.AppendLine('{')
foreach ($r in $rows) {
    [void]$sb.AppendLine(('    public const string {0} = "{1}";' -f (To-Pascal $r.id), (Esc $r.id)))
}
[void]$sb.AppendLine('}')
Set-Content -LiteralPath $idsOut -Value ($sb.ToString().TrimEnd() + "`n") -NoNewline -Encoding utf8

# ---- 3. Gating/GateId.cs (introduction-gate identity enum + construct-id map) ----
$gates = @($rows | Where-Object { $null -eq $_.removedIn -and [int]$_.introducedIn -gt 85 })
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine($hdr)
[void]$sb.AppendLine('namespace CobolNet.Editions;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>The strongly-typed identity a failing introduction predicate stamps on the parser base')
[void]$sb.AppendLine('/// (rearch P2.7): one member per introduction-gated construct (removedIn==null, introducedIn>85). The')
[void]$sb.AppendLine('/// grammar''s <c>{Gate(edition, GateId.X)}?</c> predicate records this on rejection so the error strategy')
[void]$sb.AppendLine('/// names the construct directly — replacing the EditionGateHints reverse-engineering table.</summary>')
[void]$sb.AppendLine('public enum GateId')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>No gate stamped (the reset/default state).</summary>')
[void]$sb.AppendLine('    None = 0,')
foreach ($r in $gates) {
    [void]$sb.AppendLine(('    {0},' -f (To-Pascal $r.id)))
}
[void]$sb.AppendLine('}')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>Maps a stamped <see cref="GateId"/> back to its constructs.json id (for')
[void]$sb.AppendLine('/// <see cref="ConstructRegistry.Check"/> / <see cref="ConstructRegistry.Find"/>).</summary>')
[void]$sb.AppendLine('public static class GateIds')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>The constructs.json id the gate guards; throws on <see cref="GateId.None"/>.</summary>')
[void]$sb.AppendLine('    public static string ConstructId(GateId gate) => gate switch')
[void]$sb.AppendLine('    {')
foreach ($r in $gates) {
    [void]$sb.AppendLine(('        GateId.{0} => Constructs.{0},' -f (To-Pascal $r.id)))
}
[void]$sb.AppendLine('        _ => throw new System.ArgumentOutOfRangeException(nameof(gate), gate, "no construct id for GateId.None"),')
[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')
New-Item -ItemType Directory -Force (Split-Path -Parent $gateOut) | Out-Null
Set-Content -LiteralPath $gateOut -Value ($sb.ToString().TrimEnd() + "`n") -NoNewline -Encoding utf8

Write-Host ("gen-constructs: {0} rows -> Entries; {0} ids; {1} GateId members" -f $rows.Count, $gates.Count)
