# Copyright (c) 2026 Brent Rector. All rights reserved.
# Licensed under the Business Source License 1.1. See LICENSE file in the project root.
#
# gen-constructs.ps1 — generate the construct registry from THE canonical catalogue
# (rearchitecture PHASE 02, P2.5). tests/version-matrix/constructs.json is the SINGLE hand-authored source;
# this script renders it into two committed C# build-outputs, mirroring the gen-reserved-words.ps1 discipline
# (manual regen + committed .g.cs + a drift test — ConstructRegistryDriftTests — asserts they agree; there is no
# MSBuild build hook, so a stale .g.cs is caught by CI, not a silent wrong build).
#
# Input:
#   tests/version-matrix/constructs.json  — the canonical rows: id / display / introducedIn / removedIn / obsoleteIn /
#                                           diagnosticCode / citation / directiveWords (+ description / vcr / source /
#                                           status / expectDiagnostic used by the version-matrix tests, not the
#                                           registry). directiveWords (kb/Work PB725) lists the ISO §7.3 compiler-
#                                           directive words the row gates; CompilerDirectiveCatalog inverts them into
#                                           the word → row map the text-manipulation stage gates on, so a new
#                                           directive is ONE row here plus a regen — never a hand-kept name set.
# Outputs (ALL committed; ConstructRegistryDriftTests asserts they equal constructs.json):
#   src/Cobol.Net.Editions/ConstructRegistry.g.cs  — the ConstructRegistry.Entries list (a partial).
#   src/Cobol.Net.Editions/Constructs.g.cs         — one `public const string <PascalId> = "<id>";` per row.

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$jsonIn   = Join-Path $repo 'tests/version-matrix/constructs.json'
$regOut   = Join-Path $repo 'src/Cobol.Net.Editions/ConstructRegistry.g.cs'
$idsOut   = Join-Path $repo 'src/Cobol.Net.Editions/Constructs.g.cs'

function To-Pascal([string]$id) {
    (($id -split '-') | ForEach-Object {
        if ($_.Length -eq 0) { '' } else { $_.Substring(0,1).ToUpper() + $_.Substring(1) }
    }) -join ''
}
function Esc([string]$s) { $s.Replace('\','\\').Replace('"','\"') }
function NullOrInt($v) { if ($null -eq $v) { 'null' } else { [string][int]$v } }

$rows = (Get-Content -Raw -LiteralPath $jsonIn | ConvertFrom-Json).constructs
if ($rows.Count -lt 1) { throw "constructs.json parsed to 0 rows" }

# --- validate: unique ids, unique PascalIds, required fields present ---
$seenId = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
$seenPascal = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($r in $rows) {
    foreach ($f in 'id','display','diagnosticCode','citation','introducedIn') {
        if ($null -eq $r.$f) { throw "row '$($r.id)' is missing required field '$f'" }
    }
    if (-not $seenId.Add($r.id)) { throw "duplicate construct id '$($r.id)'" }
    if (-not $seenPascal.Add((To-Pascal $r.id))) { throw "PascalId collision for '$($r.id)'" }
}

$hdr = @"
// <auto-generated>
// Generated by scripts/gen-constructs.ps1 from tests/version-matrix/constructs.json — DO NOT EDIT; re-run the script.
// tests/version-matrix/constructs.json is THE canonical version-matrix catalogue; ConstructRegistryDriftTests
// asserts this output equals it (a stale file is a CI failure, not a silent wrong build).
// </auto-generated>
"@

# ---- 1. ConstructRegistry.g.cs (the Entries partial) ----
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine($hdr)
[void]$sb.AppendLine('namespace CobolNet.Editions;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('public static partial class ConstructRegistry')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>The in-code rendering of constructs.json (generated). Pending rows (not yet')
[void]$sb.AppendLine('    /// implemented) are REGISTERED — their edition metadata is frozen here.</summary>')
[void]$sb.AppendLine('    public static readonly IReadOnlyList<ConstructDialectStatus> Entries =')
[void]$sb.AppendLine('    [')
foreach ($r in $rows) {
    $line = '        new("{0}", "{1}", {2}, {3}, {4}, "{5}", "{6}")' -f `
        (Esc $r.id), (Esc $r.display), ([int]$r.introducedIn), (NullOrInt $r.removedIn), (NullOrInt $r.obsoleteIn), `
        (Esc $r.diagnosticCode), (Esc $r.citation)
    # The ISO §7.3 directive words this row gates (kb/Work PB725) — an object initializer only on the rows
    # that carry them, so the 200-odd non-directive rows keep their one-line rendering.
    if ($null -ne $r.directiveWords -and @($r.directiveWords).Count -gt 0) {
        $words = (@($r.directiveWords) | ForEach-Object { '"' + (Esc $_) + '"' }) -join ', '
        $line += (' {{ DirectiveWords = [{0}] }}' -f $words)
    }
    [void]$sb.AppendLine($line + ',')
}
[void]$sb.AppendLine('    ];')
[void]$sb.AppendLine('}')
Set-Content -LiteralPath $regOut -Value ($sb.ToString().TrimEnd() + "`n") -NoNewline -Encoding utf8

# ---- 2. Constants.g.cs (compile-checked ids) ----
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine($hdr)
[void]$sb.AppendLine('namespace CobolNet.Editions;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>Compile-checked constructs.json row ids (P2.6): use <c>Constructs.X</c> at every')
[void]$sb.AppendLine('/// <see cref="ConstructRegistry.Check"/> call site so an unregistered id is a COMPILE error.</summary>')
[void]$sb.AppendLine('public static class Constructs')
[void]$sb.AppendLine('{')
foreach ($r in $rows) {
    [void]$sb.AppendLine(('    public const string {0} = "{1}";' -f (To-Pascal $r.id), (Esc $r.id)))
}
[void]$sb.AppendLine('}')
Set-Content -LiteralPath $idsOut -Value ($sb.ToString().TrimEnd() + "`n") -NoNewline -Encoding utf8

# (The former section 3 — Gating/GateId.cs — was DELETED at Exec Step E: the P2.7 forward-stamping
# consumer was abandoned (DEVLOG 679) and the enum had ZERO production consumers; the registry rows +
# Constructs consts are the live outputs.)

Write-Host ("gen-constructs: {0} rows -> Entries; {0} ids" -f $rows.Count)
