// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using System.Buffers.Binary;
using System.IO.Compression;

namespace CobolNet.Runtime.Unicode.Segmentation;

/// <summary>The Grapheme_Cluster_Break property values (UAX #29 Table 2), as the derived table encodes them.</summary>
public enum GraphemeBreakProperty : byte
{
    Other = 0,
    CR = 1,
    LF = 2,
    Control = 3,
    Extend = 4,
    ZWJ = 5,
    RegionalIndicator = 6,
    Prepend = 7,
    SpacingMark = 8,
    /// <summary>Hangul leading consonant jamo.</summary>
    L = 9,
    /// <summary>Hangul vowel jamo.</summary>
    V = 10,
    /// <summary>Hangul trailing consonant jamo.</summary>
    T = 11,
    /// <summary>A precomposed Hangul LV syllable.</summary>
    LV = 12,
    /// <summary>A precomposed Hangul LVT syllable.</summary>
    LVT = 13,
}

/// <summary>The Indic_Conjunct_Break property values (UAX #44; the data behind UAX #29's conjunct rule).</summary>
public enum IndicConjunctBreak : byte
{
    None = 0,
    /// <summary>A consonant of a Brahmic script that can form a conjunct.</summary>
    Consonant = 1,
    /// <summary>A mark that may sit between the consonant and the linker (nukta, ZWJ …).</summary>
    Extend = 2,
    /// <summary>The conjunct linker (virama and its equivalents).</summary>
    Linker = 3,
}

/// <summary>
/// The GRAPHEME CLUSTER SEGMENTATION of COBOL.NET — extended grapheme clusters per UAX #29 (Unicode Text Segmentation)
/// §3, computed from COBOL.NET's OWN derived property table (<c>Unicode/Segmentation/Data/grapheme-break.bin</c>,
/// generated by <c>scripts/unicode/generate-grapheme-table.py</c> from the pinned UCD 17.0.0 files: the
/// Grapheme_Cluster_Break property, Extended_Pictographic, Indic_Conjunct_Break), so every host segments text
/// identically whatever Unicode version its own runtime carries. Where the collation engine and the normalizer answer
/// "how do these texts ORDER" and "are these spellings the SAME text", this answers "how many CHARACTERS does a
/// reader see, and where may a text be cut without breaking one".
/// <para><b>The rules, in the engine's own words</b> (UAX #29 GB1–GB999; the boundary decision between the previous
/// code point P and the current one C, with the state the walk carries):
/// the text's start and end are boundaries; CR followed by LF is not; a control, CR or LF breaks before and after
/// itself; the Hangul jamo sequences L+(L|V|LV|LVT), (LV|V)+(V|T), (LVT|T)+T are not broken; nothing breaks before an
/// Extend or a ZWJ, nor before a SpacingMark, nor after a Prepend; an Indic conjunct — a Consonant, then any Extends
/// and Linkers among which at least one Linker, then a Consonant — is not broken (GB9c); an Extended_Pictographic,
/// then Extends, then a ZWJ, then another Extended_Pictographic is one emoji sequence (GB11); regional indicators pair
/// up from the start of their run (GB12/GB13); everything else is a boundary (GB999).</para>
/// <para>Verified against the full <c>GraphemeBreakTest.txt</c> of the same Unicode version (every line —
/// <c>GraphemeBreakerTests</c>). All members are thread-safe; the table loads once per process.</para>
/// </summary>
public static class GraphemeBreaker
{
    /// <summary>The embedded resource holding the derived property table (LogicalName in Cobol.Net.Runtime.csproj).</summary>
    public const string ResourceName = "Unicode/Segmentation/Data/grapheme-break.bin";

    private const byte GcbMask = 0x0F, ExtendedPictographicBit = 0x10, IncbShift = 5, IncbMask = 0x03;

    private static readonly Lazy<Table> s_table = new(Table.Load, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>The Unicode version the property table was generated from ("17.0.0").</summary>
    public static string UnicodeVersion => s_table.Value.Version;

    /// <summary>The number of property ranges in the table (diagnostics).</summary>
    public static int RangeCount => s_table.Value.RangeCount;

    /// <summary>The Grapheme_Cluster_Break property of a code point.</summary>
    public static GraphemeBreakProperty GetBreakProperty(int codePoint) => (GraphemeBreakProperty)(s_table.Value.Get(codePoint) & GcbMask);

    /// <summary>True for an Extended_Pictographic code point (an emoji base for the ZWJ-sequence rule).</summary>
    public static bool IsExtendedPictographic(int codePoint) => (s_table.Value.Get(codePoint) & ExtendedPictographicBit) != 0;

    /// <summary>The Indic_Conjunct_Break property of a code point.</summary>
    public static IndicConjunctBreak GetIndicConjunctBreak(int codePoint) => (IndicConjunctBreak)((s_table.Value.Get(codePoint) >> IncbShift) & IncbMask);

    /// <summary>The clusters of <paramref name="text"/>, in order (a <c>foreach</c>-able value; also <see cref="IEnumerable{T}"/>).</summary>
    public static GraphemeEnumerator Enumerate(string text) => new(text ?? "");

    /// <summary>The clusters of <paramref name="text"/> as strings.</summary>
    public static string[] Split(string text)
    {
        text ??= "";
        var list = new List<string>(text.Length);
        foreach (var c in Enumerate(text)) list.Add(c.ToString());
        return list.ToArray();
    }

    /// <summary>The number of grapheme clusters in <paramref name="text"/> — the number of user-perceived characters.</summary>
    public static int Count(ReadOnlySpan<char> text)
    {
        int n = 0, i = 0;
        while (i < text.Length) { i = NextBoundary(text, i); n++; }
        return n;
    }

    /// <summary>The first <paramref name="maxClusters"/> clusters of <paramref name="text"/> — a CLUSTER-SAFE truncation
    /// that never cuts a base from its marks, a surrogate pair, a Hangul syllable, an emoji sequence.</summary>
    public static string Truncate(string text, int maxClusters)
    {
        ArgumentNullException.ThrowIfNull(text);
        ArgumentOutOfRangeException.ThrowIfNegative(maxClusters);
        int i = 0, n = 0;
        while (i < text.Length && n < maxClusters) { i = NextBoundary(text, i); n++; }
        return i == text.Length ? text : text[..i];
    }

    /// <summary>Is there a grapheme cluster boundary immediately before code unit <paramref name="index"/>? 0 and
    /// <c>text.Length</c> always are; an index inside a surrogate pair never is. Decided by walking from the start of the
    /// text (the rules carry state — regional-indicator parity, emoji sequences, conjuncts — that no bounded look-behind
    /// can recover in general), so it costs O(index); walk with <see cref="Enumerate"/> or <see cref="NextBoundary"/>
    /// when every boundary is wanted.</summary>
    public static bool IsBoundary(ReadOnlySpan<char> text, int index)
    {
        if ((uint)index > (uint)text.Length) throw new ArgumentOutOfRangeException(nameof(index));
        if (index == 0 || index == text.Length) return true;
        int i = 0;
        while (i < index) i = NextBoundary(text, i);
        return i == index;
    }

    /// <summary>The end (exclusive) of the cluster that starts at code unit <paramref name="start"/> — the next
    /// boundary after it; <c>text.Length</c> for the last cluster. <paramref name="start"/> must be a boundary (the walk
    /// starts fresh there).</summary>
    public static int NextBoundary(ReadOnlySpan<char> text, int start)
    {
        if ((uint)start >= (uint)text.Length) return text.Length;
        var table = s_table.Value;
        int pos = start;
        int prevCp = Decode(text, ref pos);
        byte prevProps = table.Get(prevCp);
        var prev = (GraphemeBreakProperty)(prevProps & GcbMask);
        // Carried state (see the class summary): consecutive regional indicators ending at prev; whether prev is a
        // ZWJ that closes an "Extended_Pictographic Extend*" run (GB11); the conjunct state for GB9c (0 = none,
        // 1 = consonant seen, 2 = consonant then a linker seen).
        int riRun = prev == GraphemeBreakProperty.RegionalIndicator ? 1 : 0;
        bool afterPictographic = (prevProps & ExtendedPictographicBit) != 0;   // EP Extend* so far
        bool zwjAfterPictographic = false;                                     // EP Extend* ZWJ, prev being the ZWJ
        int conjunct = ((prevProps >> IncbShift) & IncbMask) == (byte)IndicConjunctBreak.Consonant ? 1 : 0;

        while (pos < text.Length)
        {
            int next = pos;
            int cp = Decode(text, ref next);
            byte props = table.Get(cp);
            var cur = (GraphemeBreakProperty)(props & GcbMask);
            var incb = (IndicConjunctBreak)((props >> IncbShift) & IncbMask);
            bool curPictographic = (props & ExtendedPictographicBit) != 0;

            bool boundary;
            if (prev == GraphemeBreakProperty.CR && cur == GraphemeBreakProperty.LF) boundary = false;                            // GB3
            else if (prev is GraphemeBreakProperty.Control or GraphemeBreakProperty.CR or GraphemeBreakProperty.LF) boundary = true;   // GB4
            else if (cur is GraphemeBreakProperty.Control or GraphemeBreakProperty.CR or GraphemeBreakProperty.LF) boundary = true;    // GB5
            else if (prev == GraphemeBreakProperty.L && cur is GraphemeBreakProperty.L or GraphemeBreakProperty.V or GraphemeBreakProperty.LV or GraphemeBreakProperty.LVT) boundary = false;   // GB6
            else if (prev is GraphemeBreakProperty.LV or GraphemeBreakProperty.V && cur is GraphemeBreakProperty.V or GraphemeBreakProperty.T) boundary = false;   // GB7
            else if (prev is GraphemeBreakProperty.LVT or GraphemeBreakProperty.T && cur == GraphemeBreakProperty.T) boundary = false;   // GB8
            else if (cur is GraphemeBreakProperty.Extend or GraphemeBreakProperty.ZWJ) boundary = false;                          // GB9
            else if (cur == GraphemeBreakProperty.SpacingMark) boundary = false;                                                 // GB9a
            else if (prev == GraphemeBreakProperty.Prepend) boundary = false;                                                    // GB9b
            else if (incb == IndicConjunctBreak.Consonant && conjunct == 2) boundary = false;                                    // GB9c
            else if (curPictographic && zwjAfterPictographic) boundary = false;                                                 // GB11
            else if (prev == GraphemeBreakProperty.RegionalIndicator && cur == GraphemeBreakProperty.RegionalIndicator && (riRun & 1) == 1) boundary = false;   // GB12/13
            else boundary = true;                                                                                                // GB999

            if (boundary) return pos;

            // Advance the state.
            riRun = cur == GraphemeBreakProperty.RegionalIndicator ? riRun + 1 : 0;
            if (curPictographic) { afterPictographic = true; zwjAfterPictographic = false; }
            else if (cur == GraphemeBreakProperty.Extend && afterPictographic) { zwjAfterPictographic = false; }
            else if (cur == GraphemeBreakProperty.ZWJ && afterPictographic) { zwjAfterPictographic = true; afterPictographic = false; }
            else { afterPictographic = false; zwjAfterPictographic = false; }
            conjunct = incb switch
            {
                IndicConjunctBreak.Consonant => 1,
                IndicConjunctBreak.Linker => conjunct >= 1 ? 2 : 0,
                IndicConjunctBreak.Extend => conjunct,
                _ => 0,
            };
            prev = cur;
            pos = next;
        }
        return text.Length;
    }

    private static int Decode(ReadOnlySpan<char> s, ref int pos)
    {
        char c = s[pos++];
        if (char.IsHighSurrogate(c) && pos < s.Length && char.IsLowSurrogate(s[pos])) return char.ConvertToUtf32(c, s[pos++]);
        return c;   // a BMP character — or an unpaired surrogate walked as its own code unit (property Other)
    }

    // ---- the property table ---------------------------------------------------------------------------------

    /// <summary>The derived table: sorted ranges for the whole code space, and a direct-index byte array for the BMP.</summary>
    private sealed class Table
    {
        private readonly int[] _first, _last;
        private readonly byte[] _value;
        private readonly byte[] _bmp = new byte[0x10000];

        private Table(string version, string sourceTag, int[] first, int[] last, byte[] value)
        {
            Version = version;
            SourceTag = sourceTag;
            _first = first;
            _last = last;
            _value = value;
            for (int i = 0; i < first.Length; i++)
            {
                if (first[i] > 0xFFFF) break;
                int hi = Math.Min(last[i], 0xFFFF);
                for (int cp = first[i]; cp <= hi; cp++) _bmp[cp] = value[i];
            }
        }

        public string Version { get; }
        public string SourceTag { get; }
        public int RangeCount => _first.Length;

        public byte Get(int codePoint)
        {
            if ((uint)codePoint < 0x10000) return _bmp[codePoint];
            int lo = 0, hi = _first.Length - 1;
            while (lo <= hi)
            {
                int mid = (lo + hi) >> 1;
                if (codePoint < _first[mid]) hi = mid - 1;
                else if (codePoint > _last[mid]) lo = mid + 1;
                else return _value[mid];
            }
            return 0;
        }

        public static Table Load()
        {
            using var stream = typeof(GraphemeBreaker).Assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException($"embedded grapheme table '{ResourceName}' is missing from {typeof(GraphemeBreaker).Assembly.GetName().Name}");
            using var ms = new MemoryStream();
            stream.CopyTo(ms);
            return Decode(ms.ToArray());
        }

        /// <summary>Decode a blob written by <c>generate-grapheme-table.py</c>: "CNGB", u32 raw length, raw-deflate
        /// payload; raw = u16 format, str version, str source tag, u32 range count, ranges (i32 first, i32 last, u8 value).</summary>
        public static Table Decode(ReadOnlySpan<byte> blob)
        {
            if (blob.Length < 8 || blob[0] != (byte)'C' || blob[1] != (byte)'N' || blob[2] != (byte)'G' || blob[3] != (byte)'B')
                throw new InvalidDataException("grapheme table: bad magic");
            int rawLength = BinaryPrimitives.ReadInt32LittleEndian(blob[4..]);
            var raw = new byte[rawLength];
            using (var inflate = new DeflateStream(new MemoryStream(blob[8..].ToArray()), CompressionMode.Decompress))
                inflate.ReadExactly(raw, 0, rawLength);
            int p = 0;
            int format = BinaryPrimitives.ReadUInt16LittleEndian(raw.AsSpan(p)); p += 2;
            if (format != 1) throw new InvalidDataException($"grapheme table: unsupported format {format}");
            string version = ReadStr(raw, ref p);
            string source = ReadStr(raw, ref p);
            int n = BinaryPrimitives.ReadInt32LittleEndian(raw.AsSpan(p)); p += 4;
            var first = new int[n]; var last = new int[n]; var value = new byte[n];
            for (int i = 0; i < n; i++)
            {
                first[i] = BinaryPrimitives.ReadInt32LittleEndian(raw.AsSpan(p)); p += 4;
                last[i] = BinaryPrimitives.ReadInt32LittleEndian(raw.AsSpan(p)); p += 4;
                value[i] = raw[p++];
            }
            if (p != raw.Length) throw new InvalidDataException("grapheme table: trailing bytes");
            return new Table(version, source, first, last, value);

            static string ReadStr(byte[] d, ref int pos)
            {
                int len = d[pos++];
                string s = System.Text.Encoding.UTF8.GetString(d, pos, len);
                pos += len;
                return s;
            }
        }
    }

    /// <summary>Decode a table blob (a regenerated file) and report its version and range count — for the drift test.</summary>
    public static (string Version, int RangeCount) Inspect(ReadOnlySpan<byte> blob)
    {
        var t = Table.Decode(blob);
        return (t.Version, t.RangeCount);
    }
}
